// Code generated by "goal build"; DO NOT EDIT.
//line fitpacket.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"fmt"

	"cogentcore.org/core/base/fsx"
	"cogentcore.org/core/math32"
	"cogentcore.org/lab/tensor"
	"github.com/WaveReality/waves/wavesim"
)

const (
	MaxIter = 10

	// MinData ignores data points below this level
	MinData = 0.001
)

var done = false

func FitPacketMain() {
	wavesim.Run(
		func(sim *wavesim.Sim) {
			sim.Config.Equation = wavesim.Wave1D
			sim.Config.Size.Set(1000, 1, 1)
			// sim.Config.Size.Set(80, 1, 1)
		},
		func(sim *wavesim.Sim) {
			if !done {
				FitPacketOpen(sim, "../oned_wvpacket_lg.tsr.gz", 500, 250, 80, 80, 0, 0.5)
				// FitPacketOpen(sim, "../oned_wvpacket.tsr", 40, 25, 8, 8, 0, 1)
				done = true
			}
		})
}

func FitPacketOpen(sim *wavesim.Sim, filename string, maxX int, pos, period, width, phase, amp float32) {
	sim.OpenState(fsx.Filename(filename))
	st := wavesim.State

	FitPacketVar(st, maxX, int(wavesim.WavePos), 0, pos, period, width, phase, amp)
	FitPacketVar(st, maxX, int(wavesim.WavePos), 1, pos, period, width, phase, amp)
	FitPacketVar(st, maxX, int(wavesim.WaveVel), 0, pos, period, width, phase, amp)
	FitPacketVar(st, maxX, int(wavesim.WaveVel), 1, pos, period, width, phase, amp)
}

func FitPacketVar(st *tensor.Float32, maxX int, vidx, curprv int, pos, period, width, phase, amp float32) {
	fmt.Println("\n##### vidx:", vidx, "cur prv:", curprv)
	fmt.Printf("start\tpos: %7.4g\tperiod: %7.4g\t, width: %7.4g\tphase: %7.4g\tamp: %7.4g\n", pos, period, width, phase, amp)

	step := float32(.01)
	rmult := period / 8

	amp = FitPacketAmp(st, maxX, vidx, curprv) // just gets max

	var er float32
	for iter := range MaxIter {
		pos = FitPacketPos(st, maxX, vidx, curprv, pos-4*rmult, pos+4*rmult, 1, period, width, phase, amp)
		phase = FitPacketPhase(st, maxX, vidx, curprv, 0, 1, 0.01, pos, period, width, amp)
		period = FitPacketPeriod(st, maxX, vidx, curprv, period-4*rmult, period+4*rmult, step, pos, width, phase, amp)
		width = FitPacketWidth(st, maxX, vidx, curprv, width-4, width+4, step, pos, period, phase, amp)
		er = FitPacketErr(false, st, maxX, vidx, curprv, pos, period, width, phase, amp)
		fmt.Printf("%d\tpos: %7.4g\tperiod: %7.4g\t, width: %7.4g\tphase: %7.4g\tamp: %7.4g\terr: %7.4g\n", iter, pos, period, width, phase, amp, er)
	}
	// er = FitPacketErr(true, st, maxX, vidx, curprv, pos, period, width, phase, amp)
}

// computes the max
func FitPacketAmp(st *tensor.Float32, maxX, vidx, curprv int) float32 {
	mx := float32(0)
	for x := range maxX {
		v := st.Value(int(1), int(1), int(x), int(vidx), int(curprv))
		mx = max(math32.Abs(v), mx)
	}
	return mx
}

func FitPacketPos(st *tensor.Float32, maxX, vidx, curprv int, minPos, maxPos, stepPos, period, width, phase, amp float32) float32 {
	var best float32
	minerr := float32(math32.MaxFloat32)

	// fmt.Println("p, w, p, a", period, width, phase, amp)

	for pos := minPos; pos <= maxPos; pos += stepPos {
		er := float32(0)
		for x := range maxX {
			v := math32.Abs(st.Value(int(1), int(1), int(x), int(vidx), int(curprv)))
			if v < MinData {
				continue
			}
			d := float32(x-1) - pos
			t := math32.Abs(wavesim.WavePacket(d, d, period, width, phase, amp))
			erd := math32.Abs(v - t)
			er += erd
			//	if math32.Abs(pos - 26.2) < 0.001 {
			//		fmt.Printf("%d\t%14.4g\t%14.4g\t%14.4g\n", x-1, v, t, erd)
			//	}
		}
		if er < minerr {
			best = pos
			minerr = er
		}
	}
	// fmt.Println("pos best, err:", best, minerr)
	return best
}

func FitPacketWidth(st *tensor.Float32, maxX, vidx, curprv int, minWd, maxWd, stepWd, pos, period, phase, amp float32) float32 {
	var best float32
	minerr := float32(math32.MaxFloat32)

	for wd := minWd; wd <= maxWd; wd += stepWd {
		er := float32(0)
		for x := range maxX {
			v := math32.Abs(st.Value(int(1), int(1), int(x), int(vidx), int(curprv)))
			if v < MinData {
				continue
			}
			d := float32(x-1) - pos
			t := math32.Abs(wavesim.WavePacket(d, d, period, wd, phase, amp))
			erd := math32.Abs(v - t)
			er += erd
			//	if math32.Abs(per - 12) < 0.001 {
			//		fmt.Printf("%d\t%14.4g\t%14.4g\t%14.4g\n", x-1, v, t, erd)
			//	}
		}
		if er < minerr {
			best = wd
			minerr = er
		}
	}
	// fmt.Println("width best, err:", best, minerr)
	return best
}

func FitPacketPeriod(st *tensor.Float32, maxX, vidx, curprv int, minPer, maxPer, stepPer, pos, width, phase, amp float32) float32 {
	var best float32
	minerr := float32(math32.MaxFloat32)

	for per := minPer; per <= maxPer; per += stepPer {
		er := float32(0)
		for x := range maxX {
			v := st.Value(int(1), int(1), int(x), int(vidx), int(curprv))
			if v < MinData {
				continue
			}
			d := float32(x-1) - pos
			t := wavesim.WavePacket(d, d, per, width, phase, amp)
			erd := float32(0)
			if math32.Sign(v) != math32.Sign(t) {
				erd = 1
			}
			er += erd
		}
		if er < minerr {
			best = per
			minerr = er
		}
	}
	// fmt.Println("period best, err:", best, minerr)
	return best
}

func FitPacketPhase(st *tensor.Float32, maxX, vidx, curprv int, minPhs, maxPhs, stepPhs, pos, period, width, amp float32) float32 {
	var best float32
	minerr := float32(math32.MaxFloat32)

	for phs := minPhs; phs <= maxPhs; phs += stepPhs {
		er := float32(0)
		for x := range maxX {
			v := st.Value(int(1), int(1), int(x), int(vidx), int(curprv))
			d := float32(x-1) - pos
			t := wavesim.WavePacket(d, d, period, width, phs, amp)
			erd := float32(0)
			if math32.Sign(v) != math32.Sign(t) {
				erd = 1
			}
			er += erd
		}
		if er < minerr {
			best = phs
			minerr = er
		}
	}
	// fmt.Println("phase best, err:", best, minerr)
	return best
}

// FitPacketErr returns raw Abs error for given params
func FitPacketErr(print bool, st *tensor.Float32, maxX, vidx, curprv int, pos, period, width, phase, amp float32) float32 {
	er := float32(0)
	for x := range maxX {
		v := st.Value(int(1), int(1), int(x), int(vidx), int(curprv))
		d := float32(x-1) - pos
		t := wavesim.WavePacket(d, d, period, width, phase, amp)
		erd := math32.Abs(v - t)
		er += erd
		if print {
			fmt.Printf("%d\t%14.4g\t%14.4g\t%14.4g\n", x-1, v, t, erd)
		}
	}
	// fmt.Println("err:", er)
	return er
}
