// Code generated by "gosl"; DO NOT EDIT
// kernel: EdgesWrapKernel

// // Params contains the full set of simulation parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
// // Ctx has the Context state values. 
@group(1) @binding(0)
var<storage, read> Ctx: array<Context>;
@group(1) @binding(1)
var<storage, read_write> State0: array<f32>;
@group(1) @binding(2)
var<storage, read_write> State1: array<f32>;
@group(1) @binding(3)
var<storage, read_write> State2: array<f32>;
@group(1) @binding(4)
var<storage, read_write> State3: array<f32>;
@group(1) @binding(5)
var<storage, read_write> State4: array<f32>;
@group(1) @binding(6)
var<storage, read_write> State5: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	EdgesWrapKernel(idx);
}

fn StateGet(ix: u32) -> f32 {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		return State0[ix];
	}
	case u32(1): {
		return State1[ix - 536870904];
	}
	case u32(2): {
		return State2[ix - 1073741808];
	}
	case u32(3): {
		return State3[ix - 1610612712];
	}
	case u32(4): {
		return State4[ix - 2147483616];
	}
	default: {
		return State5[ix - 2684354520];
	}
	}
}

fn StateSet(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] = vl;
	}
	case u32(1): {
		State1[ix - 536870904] = vl;
	}
	case u32(2): {
		State2[ix - 1073741808] = vl;
	}
	case u32(3): {
		State3[ix - 1610612712] = vl;
	}
	case u32(4): {
		State4[ix - 2147483616] = vl;
	}
	default: {
		State5[ix - 2684354520] = vl;
	}
	}
}

fn StateSetAdd(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] += vl;
	}
	case u32(1): {
		State1[ix - 536870904] += vl;
	}
	case u32(2): {
		State2[ix - 1073741808] += vl;
	}
	case u32(3): {
		State3[ix - 1610612712] += vl;
	}
	case u32(4): {
		State4[ix - 2147483616] += vl;
	}
	default: {
		State5[ix - 2684354520] += vl;
	}
	}
}

fn StateSetSub(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] -= vl;
	}
	case u32(1): {
		State1[ix - 536870904] -= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] -= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] -= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] -= vl;
	}
	default: {
		State5[ix - 2684354520] -= vl;
	}
	}
}

fn StateSetMul(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] *= vl;
	}
	case u32(1): {
		State1[ix - 536870904] *= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] *= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] *= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] *= vl;
	}
	default: {
		State5[ix - 2684354520] *= vl;
	}
	}
}

fn StateSetDiv(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] /= vl;
	}
	case u32(1): {
		State1[ix - 536870904] /= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] /= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] /= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] /= vl;
	}
	default: {
		State5[ix - 2684354520] /= vl;
	}
	}
}

fn Index5D(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, i0: u32, i1: u32, i2: u32, i3: u32, i4: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3 + s4 * i4;
}


//////// import: "vars.go"

//////// import: "context.go"
struct Context {
	Size: vec4<i32>,
	NVars: i32,
	Step: i32,
	CurState: i32,
	pad: i32,
}
fn Context_PrevState(ctx: Context) -> i32 {
	return 1 - ctx.CurState;
}

//////// import: "dirac.go"
alias DiracStates = EMStates; //enums:enum -trim-prefix=Dirac
const  DiracPos1A: DiracStates = DiracStates(EMStatesN) + iota;
const  DiracPos1BDiracStates;
const  DiracPos2ADiracStates;
const  DiracPos2BDiracStates;
const  DiracVel1ADiracStates;
const  DiracVel1BDiracStates;
const  DiracVel2ADiracStates;
const  DiracVel2BDiracStates;
const  DiracCCDiracStates;

//////// import: "edges.go"
alias Edges = i32; //enums:enum -trim-prefix=Edges
const  EdgesFixed: Edges = 0;
const  EdgesWrap: Edges = 1;
const  EdgesDamp: Edges = 2;
fn Context_EdgeCoordsWrap(ctx: Context, idx: u32, x: ptr<function,i32>,y: ptr<function,i32>,z: ptr<function,i32>,xs: ptr<function,i32>,ys: ptr<function,i32>,zs: ptr<function,i32>) -> i32 {
	var i = i32(idx);
	var s = vec3<i32>(ctx.Size.x,ctx.Size.y,ctx.Size.z);
	var p = s+(vec3<i32>(1, 1, 1));
	var xy = p.x * p.y;
	var yz = p.y * p.z;
	var xz = p.x * p.z;
	if (i < 2) { // 6 corner
		if (i == 0) {
			*x = i32(0);
			*y = i32(0);
			*z = i32(0);
			*xs = s.x;
			*ys = s.y;
			*zs = s.z;
		return i32(6);
		}
		*x = p.x;
		*y = p.y;
		*z = p.z;
		*xs = i32(1);
		*ys = i32(1);
		*zs = i32(1);
	return i32(6);
	}
	i -= i32(2);
	if (i < yz) { // 0
		*y = i / p.z;
		*z = 1 + i%p.z;
		*x = i32(0);
		*xs = s.x;
		if (*y == 0 && *z == p.z) {
			*ys = s.y;
			*zs = i32(1);
		return i32(6);
		}
		*ys = *y;
		if (*ys == 0) {
			*ys = s.y;
		}
		*zs = *z;
		if (*zs == p.z) {
			*zs = i32(1);
		}return i32(0);
	}
	i -= yz;
	if (i < xy) { // 1
		*x = i / p.y;
		*y = 1 + i%p.y;
		*z = i32(0);
		*zs = s.z;
		if (*x == 0 && *y == p.y) {
			*xs = s.x;
			*ys = i32(1);
		return i32(6);
		}
		*xs = *x;
		if (*xs == 0) {
			*xs = s.x;
		}
		*ys = *y;
		if (*ys == p.y) {
			*ys = i32(1);
		}return i32(1);
	}
	i -= xy;
	if (i < xz) { // 2
		*x = 1 + i/p.z;
		*z = i % p.z;
		*y = i32(0);
		*ys = s.y;
		if (*x == p.x && *z == 0) {
			*xs = i32(1);
			*zs = s.z;
		return i32(6);
		}
		*xs = *x;
		if (*xs == p.x) {
			*xs = i32(1);
		}
		*zs = *z;
		if (*zs == 0) {
			*zs = s.z;
		}return i32(2);
	}
	i -= xz;
	if (i < yz) { // 3
		*y = 1 + i/p.z;
		*z = i % p.z;
		*x = p.x;
		*xs = i32(1);
		if (*y == p.y && *z == 0) {
			*ys = i32(1);
			*zs = s.z;
		return i32(6);
		}
		*ys = *y;
		if (*ys == p.y) {
			*ys = i32(1);
		}
		*zs = *z;
		if (*zs == 0) {
			*zs = s.z;
		}return i32(3);
	}
	i -= yz;
	if (i < xy) { // 4
		*x = 1 + i/p.y;
		*y = i % p.y;
		*z = p.z;
		*zs = i32(1);
		if (*x == p.x && *y == 0) {
			*xs = i32(1);
			*ys = s.y;
		return i32(6);
		}
		*xs = *x;
		if (*xs == p.x) {
			*xs = i32(1);
		}
		*ys = *y;
		if (*ys == 0) {
			*ys = s.y;
		}return i32(4);
	}
	i -= xy;
	if (i < xz) { // 2
		*x = i / p.z;
		*z = 1 + i%p.z;
		*y = p.y;
		*ys = i32(1);
		if (*x == 0 && *z == p.z) {
			*xs = s.x;
			*zs = i32(1);
		return i32(6);
		}
		*xs = *x;
		if (*xs == 0) {
			*xs = s.x;
		}
		*zs = *z;
		if (*zs == p.z) {
			*zs = i32(1);
		}return i32(5);
	}return -1;
}
fn EdgesWrapKernel(i: u32) { //gosl:kernel
	let ctx = Ctx[0];
	var x: i32;
	var y: i32;
	var z: i32;
	var sx: i32;
	var sy: i32;
	var sz: i32;
	var face = Context_EdgeCoordsWrap(ctx, i, &x, &y, &z, &sx, &sy, &sz);
	if (face < 0) {
		return;
	}
	var cur = ctx.CurState;
	var prv = Context_PrevState(ctx);
	var nvars = ctx.NVars;
	for (var vi=0; vi<nvars; vi++) {
		StateSet(StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(sz), u32(sy), u32(sx), u32(vi), u32(cur))), Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(vi), u32(cur)));
		StateSet(StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(sz), u32(sy), u32(sx), u32(vi), u32(prv))), Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(vi), u32(prv)));
	}
}

//////// import: "enumgen.go"
const DiracStatesN: DiracStates = 27;
const EdgesN: Edges = 3;
const MinusPlusOneN: MinusPlusOne = 2;
const NeighWeightsN: NeighWeights = 3;
const GPUVarsN: GPUVars = 6;
const EMStatesN: EMStates = 18;
const EquationsN: Equations = 6;
const CabStatesN: CabStates = 11;
const ViewModesN: ViewModes = 2;
const CurPrevN: CurPrev = 2;
const NPanelsN: NPanels = 3;
const WaveStatesN: WaveStates = 6;

//////// import: "funcs.go"
alias MinusPlusOne = i32; //enums:enum
const  Minus1: MinusPlusOne = 0;
const  Plus1: MinusPlusOne  = 1;
alias NeighWeights = i32; //enums:enum
const  LaplacianWts: NeighWeights = 0;
const  AverageWts: NeighWeights = 1;
const  Grad18Wts: NeighWeights = 2;
const  Average27Sum = f32(20.104084);
const  OneoAverage27Sum = 0.049741138;

//////// import: "klein-gordon.go"

//////// import: "maxwell.go"
alias EMStates = i32; //enums:enum
const  A0Pos: EMStates = 0;
const  AXPos: EMStates = 1;
const  AYPos: EMStates = 2;
const  AZPos: EMStates = 3;
const  A0Vel: EMStates = 4;
const  AXVel: EMStates = 5;
const  AYVel: EMStates = 6;
const  AZVel: EMStates = 7;
const  EX: EMStates = 8;
const  EY: EMStates = 9;
const  EZ: EMStates = 10;
const  BX: EMStates = 11;
const  BY: EMStates = 12;
const  BZ: EMStates = 13;
const  Charge: EMStates = 14;
const  CurrentX: EMStates = 15;
const  CurrentY: EMStates = 16;
const  CurrentZ: EMStates = 17;

//////// import: "params.go"
alias Equations = i32; //enums:enum
const  Wave: Equations = 0;
const  KleinGordon: Equations = 1;
const  KleinGordonC: Equations = 2;
const  Schrodinger: Equations = 3;
const  Maxwell: Equations = 4;
const  Dirac: Equations = 5;
const  Pi       = 3.14159265358979323846264338327950288419716939937510582097494459;
const  TwoPi    = 2 * Pi;
const  InvTwoPi = 1.0 / TwoPi;
struct Parameters {
	ThreeD: i32,
	Energy: i32,
	C: f32,
	CSq: f32,
	Inv2CSq: f32,
	HBar: f32,
	Mass: f32,
	MassCOverHBarSq: f32,
	HBarSqOver2Mass: f32,
	MassOver2: f32,
	Mu0: f32,
	Eps0: f32,
	OneoEps0: f32,
	Wavelength: f32,
	PacketWidth: f32,
	Edges: Edges,
}

//////// import: "schrodinger.go"
alias CabStates = i32; //enums:enum -trim-prefix=Cab
const  CabPosA: CabStates = 0;
const  CabPosB: CabStates = 1;
const  CabVelA: CabStates = 2;
const  CabVelB: CabStates = 3;
const  CabForceA: CabStates = 4;
const  CabForceB: CabStates = 5;
const  CabV: CabStates = 6;
const  CabCC: CabStates = 7;
const  CabKinetic: CabStates = 8;
const  CabPotential: CabStates = 9;
const  CabEnergy: CabStates = 10;

//////// import: "settings.go"
alias ViewModes = i32; //enums:enum
const  Plane: ViewModes = 0;
const  Bars: ViewModes = 1;
alias CurPrev = i32; //enums:enum
const  Current: CurPrev = 0;
const  Previous: CurPrev = 1;
alias NPanels = i32; //enums:enum -trim-prefix=Panels
const  PanelsOne: NPanels = 0;
const  PanelsTwo: NPanels = 1;
const  PanelsFour: NPanels = 2;

//////// import: "wave.go"
alias WaveStates = i32; //enums:enum -trim-prefix=Wave
const  WavePos: WaveStates = 0;
const  WaveVel: WaveStates = 1;
const  WaveForce: WaveStates = 2;
const  WaveKinetic: WaveStates = 3;
const  WavePotential: WaveStates = 4;
const  WaveEnergy: WaveStates = 5;