// Code generated by "gosl"; DO NOT EDIT
// kernel: ElectroweakKernel

// // Params contains the full set of simulation parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> Params: array<Parameters>;
@group(0) @binding(2)
var<storage, read_write> NeighOffs: array<i32>;
@group(0) @binding(3)
var<storage, read_write> FaceOffs: array<i32>;
@group(0) @binding(4)
var<storage, read_write> NeighWts: array<f32>;
// // Ctx has the Context state values. 
@group(1) @binding(0)
var<storage, read> Ctx: array<Context>;
@group(1) @binding(2)
var<storage, read_write> State0: array<f32>;
@group(1) @binding(3)
var<storage, read_write> State1: array<f32>;
@group(1) @binding(4)
var<storage, read_write> State2: array<f32>;
@group(1) @binding(5)
var<storage, read_write> State3: array<f32>;
@group(1) @binding(6)
var<storage, read_write> State4: array<f32>;
@group(1) @binding(7)
var<storage, read_write> State5: array<f32>;
@group(1) @binding(8)
var<storage, read_write> State6: array<f32>;
@group(1) @binding(9)
var<storage, read_write> State7: array<f32>;
@group(1) @binding(10)
var<storage, read_write> State8: array<f32>;
@group(1) @binding(11)
var<storage, read_write> State9: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	ElectroweakKernel(idx);
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}

fn Index4D(s0: u32, s1: u32, s2: u32, s3: u32, i0: u32, i1: u32, i2: u32, i3: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3;
}

fn StateGet(ix: u32) -> f32 {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		return State0[ix];
	}
	case u32(1): {
		return State1[ix - 536870904];
	}
	case u32(2): {
		return State2[ix - 1073741808];
	}
	case u32(3): {
		return State3[ix - 1610612712];
	}
	case u32(4): {
		return State4[ix - 2147483616];
	}
	case u32(5): {
		return State5[ix - 2684354520];
	}
	case u32(6): {
		return State6[ix - 3221225424];
	}
	case u32(7): {
		return State7[ix - 3758096328];
	}
	case u32(8): {
		return State8[ix - 4294967232];
	}
	default: {
		return State9[ix - 536870840];
	}
	}
}

fn StateSet(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] = vl;
	}
	case u32(1): {
		State1[ix - 536870904] = vl;
	}
	case u32(2): {
		State2[ix - 1073741808] = vl;
	}
	case u32(3): {
		State3[ix - 1610612712] = vl;
	}
	case u32(4): {
		State4[ix - 2147483616] = vl;
	}
	case u32(5): {
		State5[ix - 2684354520] = vl;
	}
	case u32(6): {
		State6[ix - 3221225424] = vl;
	}
	case u32(7): {
		State7[ix - 3758096328] = vl;
	}
	case u32(8): {
		State8[ix - 4294967232] = vl;
	}
	default: {
		State9[ix - 536870840] = vl;
	}
	}
}

fn StateSetAdd(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] += vl;
	}
	case u32(1): {
		State1[ix - 536870904] += vl;
	}
	case u32(2): {
		State2[ix - 1073741808] += vl;
	}
	case u32(3): {
		State3[ix - 1610612712] += vl;
	}
	case u32(4): {
		State4[ix - 2147483616] += vl;
	}
	case u32(5): {
		State5[ix - 2684354520] += vl;
	}
	case u32(6): {
		State6[ix - 3221225424] += vl;
	}
	case u32(7): {
		State7[ix - 3758096328] += vl;
	}
	case u32(8): {
		State8[ix - 4294967232] += vl;
	}
	default: {
		State9[ix - 536870840] += vl;
	}
	}
}

fn StateSetSub(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] -= vl;
	}
	case u32(1): {
		State1[ix - 536870904] -= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] -= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] -= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] -= vl;
	}
	case u32(5): {
		State5[ix - 2684354520] -= vl;
	}
	case u32(6): {
		State6[ix - 3221225424] -= vl;
	}
	case u32(7): {
		State7[ix - 3758096328] -= vl;
	}
	case u32(8): {
		State8[ix - 4294967232] -= vl;
	}
	default: {
		State9[ix - 536870840] -= vl;
	}
	}
}

fn StateSetMul(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] *= vl;
	}
	case u32(1): {
		State1[ix - 536870904] *= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] *= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] *= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] *= vl;
	}
	case u32(5): {
		State5[ix - 2684354520] *= vl;
	}
	case u32(6): {
		State6[ix - 3221225424] *= vl;
	}
	case u32(7): {
		State7[ix - 3758096328] *= vl;
	}
	case u32(8): {
		State8[ix - 4294967232] *= vl;
	}
	default: {
		State9[ix - 536870840] *= vl;
	}
	}
}

fn StateSetDiv(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] /= vl;
	}
	case u32(1): {
		State1[ix - 536870904] /= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] /= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] /= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] /= vl;
	}
	case u32(5): {
		State5[ix - 2684354520] /= vl;
	}
	case u32(6): {
		State6[ix - 3221225424] /= vl;
	}
	case u32(7): {
		State7[ix - 3758096328] /= vl;
	}
	case u32(8): {
		State8[ix - 4294967232] /= vl;
	}
	default: {
		State9[ix - 536870840] /= vl;
	}
	}
}

fn Index5D(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, i0: u32, i1: u32, i2: u32, i3: u32, i4: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3 + s4 * i4;
}


//////// import: "vars.go"

//////// import: "context.go"
struct Context {
	Size: vec4<i32>,
	NVars: i32,
	Step: i32,
	CurState: i32,
	pad: i32,
	RandCounter: RandCounter,
}
fn Context_StateCoords(ctx: Context, idx: u32, x: ptr<function,i32>,y: ptr<function,i32>,z: ptr<function,i32>) -> bool {
	var szxy = ctx.Size.x * ctx.Size.y;
	*z = i32(idx) / szxy;
	var rz = i32(idx) % szxy;
	var szx = ctx.Size.x;
	*y = rz / szx;
	*x = rz % szx;
	if (*z >= ctx.Size.z || *y >= ctx.Size.y || *x >= ctx.Size.x) {
		return false;
	}
	*z += i32(1);
	*y += i32(1);
	*x += i32(1);
return true;
}
fn Context_PrevState(ctx: Context) -> i32 {
	return 1 - ctx.CurState;
}

//////// import: "dirac.go"
alias DiracStates = EMStates; //enums:enum -trim-prefix=Dirac
const  DiracPos1A: DiracStates = 18;
const  DiracPos1B: DiracStates = 19;
const  DiracPos2A: DiracStates = 20;
const  DiracPos2B: DiracStates = 21;
const  DiracVel1A: DiracStates = 22;
const  DiracVel1B: DiracStates = 23;
const  DiracVel2A: DiracStates = 24;
const  DiracVel2B: DiracStates = 25;
const  DiracCC: DiracStates = 26;

//////// import: "edges.go"
alias Edges = i32; //enums:enum -trim-prefix=Edges
const  EdgesFixed: Edges = 0;
const  EdgesWrap: Edges = 1;
const  EdgesDamp: Edges = 2;

//////// import: "electroweak.go"
alias EWStates = EMStates; //enums:enum -trim-prefix=EW
const  EWHsCa: EWStates = 18;
const  EWHsCb: EWStates = 19;
const  EWHs0a: EWStates = 20;
const  EWHs0b: EWStates = 21;
const  EWHvCa: EWStates = 22;
const  EWHvCb: EWStates = 23;
const  EWHv0a: EWStates = 24;
const  EWHv0b: EWStates = 25;
const  EWHmag: EWStates = 26;
const  EWHV: EWStates = 27;
const  EWB0s: EWStates = 28;
const  EWBXs: EWStates = 29;
const  EWBYs: EWStates = 30;
const  EWBZs: EWStates = 31;
const  EWB0v: EWStates = 32;
const  EWBXv: EWStates = 33;
const  EWBYv: EWStates = 34;
const  EWBZv: EWStates = 35;
const  EWW10s: EWStates = 36;
const  EWW1Xs: EWStates = 37;
const  EWW1Ys: EWStates = 38;
const  EWW1Zs: EWStates = 39;
const  EWW10v: EWStates = 40;
const  EWW1Xv: EWStates = 41;
const  EWW1Yv: EWStates = 42;
const  EWW1Zv: EWStates = 43;
const  EWW20s: EWStates = 44;
const  EWW2Xs: EWStates = 45;
const  EWW2Ys: EWStates = 46;
const  EWW2Zs: EWStates = 47;
const  EWW20v: EWStates = 48;
const  EWW2Xv: EWStates = 49;
const  EWW2Yv: EWStates = 50;
const  EWW2Zv: EWStates = 51;
const  EWW30s: EWStates = 52;
const  EWW3Xs: EWStates = 53;
const  EWW3Ys: EWStates = 54;
const  EWW3Zs: EWStates = 55;
const  EWW30v: EWStates = 56;
const  EWW3Xv: EWStates = 57;
const  EWW3Yv: EWStates = 58;
const  EWW3Zv: EWStates = 59;
const YPhi = 0.5;
fn EWGaugeAct(w1: f32,w2: f32,w3: f32,b: f32, psi: vec4<f32>) -> vec4<f32> {
	var hg = 0.5 * Params[0].GW;
	var gy = Params[0].GpW * YPhi;
	var du = hg*w3 + gy*b;
	var dd = -hg*w3 + gy*b;
	var or = hg * w1;
	var oi = -hg * w2;
	var o: vec4<f32>;
	o.x = du*psi.y + or*psi.w + oi*psi.z;
	o.y = -(du*psi.x + or*psi.z - oi*psi.w);
	o.z = or*psi.y - oi*psi.x + dd*psi.w;
	o.w = -(or*psi.x + oi*psi.y + dd*psi.z);
return o;
}
fn EWCurrent(psi: vec4<f32>,d: vec4<f32>) -> vec4<f32> {
	var hg = 0.5 * Params[0].GW;
	var gy = Params[0].GpW * YPhi;
	var j: vec4<f32>;
	j.x = hg * ((psi.x*d.w - psi.y*d.z) + (psi.z*d.y - psi.w*d.x));
	j.y = hg * (-(psi.x*d.z + psi.y*d.w) + (psi.z*d.x + psi.w*d.y));
	j.z = hg * ((psi.x*d.y - psi.y*d.x) - (psi.z*d.w - psi.w*d.z));
	j.w = gy * ((psi.x*d.y - psi.y*d.x) + (psi.z*d.w - psi.w*d.z));
return j;
}
fn EWDiv(x: i32,y: i32,z: i32,vX: i32,tidx: i32) -> f32 {
	var gx = Gradient18(x, y, z, vX, tidx);
	var gy = Gradient18(x, y, z, vX+1, tidx);
	var gz = Gradient18(x, y, z, vX+2, tidx);
return gx.x + gy.y + gz.z;
}
fn ElectroweakKernel(i: u32) { //gosl:kernel
	let ctx = Ctx[0];
	var x: i32;
	var y: i32;
	var z: i32;
	var ok = Context_StateCoords(ctx, i, &x, &y, &z);
	if (!ok) {
		return;
	}
	var cur = ctx.CurState;
	var prv = Context_PrevState(ctx);
	var csq = Params[0].CSq;
	var oc = 1.0 / Params[0].C;
	var musq = Params[0].HiggsMuSq;
	var lambda = Params[0].HiggsLambda;
	var psi = vec4<f32>(StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHsCa), u32(prv))), StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHsCb), u32(prv))),
		StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHs0a), u32(prv))), StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHs0b), u32(prv))));
	var psv = vec4<f32>(StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHvCa), u32(prv))), StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHvCb), u32(prv))),
		StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHv0a), u32(prv))), StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42],
		TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHv0b), u32(prv))));
	var w10 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW10s), u32(prv)));
	var w1x = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW1Xs), u32(prv)));
	var w1y = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW1Ys), u32(prv)));
	var w1z = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW1Zs), u32(prv)));
	var w20 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW20s), u32(prv)));
	var w2x = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW2Xs), u32(prv)));
	var w2y = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW2Ys), u32(prv)));
	var w2z = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW2Zs), u32(prv)));
	var w30 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW30s), u32(prv)));
	var w3x = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW3Xs), u32(prv)));
	var w3y = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW3Ys), u32(prv)));
	var w3z = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW3Zs), u32(prv)));
	var b0 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWB0s), u32(prv)));
	var bx = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWBXs), u32(prv)));
	var by = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWBYs), u32(prv)));
	var bz = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42],
	TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWBZs), u32(prv)));
	var gCa = Gradient18(x, y, z, i32(EWHsCa), prv);
	var gCb = Gradient18(x, y, z, i32(EWHsCb), prv);
	var g0a = Gradient18(x, y, z, i32(EWHs0a), prv);
	var g0b = Gradient18(x, y, z, i32(EWHs0b), prv);
	var dxp = vec4<f32>(gCa.x, gCb.x, g0a.x, g0b.x); // d_x Psi
	var dyp = vec4<f32>(gCa.y, gCb.y, g0a.y, g0b.y);
	var dzp = vec4<f32>(gCa.z, gCb.z, g0a.z, g0b.z);
	var ax = EWGaugeAct(w1x, w2x, w3x, bx, psi);
	var ay = EWGaugeAct(w1y, w2y, w3y, by, psi);
	var az = EWGaugeAct(w1z, w2z, w3z, bz, psi);
	var a0 = EWGaugeAct(w10, w20, w30, b0, psi);
	var dX = dxp+(ax);
	var dY = dyp+(ay);
	var dZ = dzp+(az);
	var dtp = vec4<f32>(oc*psv.x, oc*psv.y, oc*psv.z, oc*psv.w);
	var d0 = dtp+(a0);
	var dvW1 = EWDiv(x, y, z, i32(EWW1Xs), prv);
	var dvW2 = EWDiv(x, y, z, i32(EWW2Xs), prv);
	var dvW3 = EWDiv(x, y, z, i32(EWW3Xs), prv);
	var dvB = EWDiv(x, y, z, i32(EWBXs), prv);
	var lap = vec4<f32>(Laplacian26(x, y, z, i32(EWHsCa), prv, psi.x),
		Laplacian26(x, y, z, i32(EWHsCb), prv, psi.y),
		Laplacian26(x, y, z, i32(EWHs0a), prv, psi.z),
		Laplacian26(x, y, z, i32(EWHs0b), prv, psi.w));
	var cov = lap+(EWGaugeAct(dvW1, dvW2, dvW3, dvB, psi));
	cov = cov+(EWGaugeAct(w1x, w2x, w3x, bx, dxp+(dX)));
	cov = cov+(EWGaugeAct(w1y, w2y, w3y, by, dyp+(dY)));
	cov = cov+(EWGaugeAct(w1z, w2z, w3z, bz, dzp+(dZ)));
	var w10v = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW10v), u32(prv)));
	var w20v = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW20v), u32(prv)));
	var w30v = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW30v), u32(prv)));
	var b0v = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWB0v), u32(prv)));
	var q0 = EWGaugeAct(oc*w10v, oc*w20v, oc*w30v, oc*b0v, psi);
	var q1 = EWGaugeAct(w10, w20, w30, b0, dtp);
	var q2 = EWGaugeAct(w10, w20, w30, b0, d0);
	cov = vec4<f32>(cov.x-q0.x-q1.x-q2.x, cov.y-q0.y-q1.y-q2.y,
		cov.z-q0.z-q1.z-q2.z, cov.w-q0.w-q1.w-q2.w);
	var mag = psi.x*psi.x + psi.y*psi.y + psi.z*psi.z + psi.w*psi.w;
	var vfac = musq - lambda*mag;
	var hf = vec4<f32>(csq*(cov.x+vfac*psi.x), csq*(cov.y+vfac*psi.y),
		csq*(cov.z+vfac*psi.z), csq*(cov.w+vfac*psi.w));
	var j0 = EWCurrent(psi, d0);
	var jx = EWCurrent(psi, dX);
	var jy = EWCurrent(psi, dY);
	var jz = EWCurrent(psi, dZ);
	EWGaugeStep(x, y, z, cur, prv, i32(EWW10s), csq, j0.x, jx.x, jy.x, jz.x);
	EWGaugeStep(x, y, z, cur, prv, i32(EWW20s), csq, j0.y, jx.y, jy.y, jz.y);
	EWGaugeStep(x, y, z, cur, prv, i32(EWW30s), csq, j0.z, jx.z, jy.z, jz.z);
	EWGaugeStep(x, y, z, cur, prv, i32(EWB0s), csq, j0.w, jx.w, jy.w, jz.w);
	var hvCaN = psv.x + hf.x;
	var hvCbN = psv.y + hf.y;
	var hv0aN = psv.z + hf.z;
	var hv0bN = psv.w + hf.w;
	StateSet(psi.x + hvCaN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHsCa), u32(cur)));
	StateSet(psi.y + hvCbN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHsCb), u32(cur)));
	StateSet(psi.z + hv0aN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHs0a), u32(cur)));
	StateSet(psi.w + hv0bN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHs0b), u32(cur)));
	StateSet(hvCaN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHvCa), u32(cur)));
	StateSet(hvCbN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHvCb), u32(cur)));
	StateSet(hv0aN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHv0a), u32(cur)));
	StateSet(hv0bN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHv0b), u32(cur)));
	StateSet(mag, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHmag), u32(cur)));
	StateSet(-0.5*musq*mag + 0.25*lambda*mag*mag, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42],
	TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHV), u32(cur)));
}
fn EWGaugeStep(x: i32,y: i32,z: i32,cur: i32,prv: i32,v0: i32, csq: f32,j0: f32,jx: f32,jy: f32,jz: f32) {
	for (var ki=0; ki<4; ki++) {
		var k = i32(ki);
		var vs = v0 + k;
		var vv = v0 + 4 + k;
		var jc: f32;
		switch (ki) {
		case 0: {
			jc = j0;
		}
		case 1: {
			jc = jx;
		}
		case 2: {
			jc = jy;
		}
		default: {
			jc = jz;
		}
		}
		var ps = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs), u32(prv)));
		var vp = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv), u32(prv)));
		var f = csq * (Laplacian26(x, y, z, vs, prv, ps) + jc);
		var vc = vp + f;
		StateSet(vc, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv), u32(cur)));
		StateSet(ps + vc, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs), u32(cur)));
	}
}

//////// import: "enumgen.go"
const DiracStatesN: DiracStates = 27;
const EdgesN: Edges = 3;
const EWStatesN: EWStates = 60;
const MinusPlusOneN: MinusPlusOne = 2;
const NeighWeightsN: NeighWeights = 3;
const GPUVarsN: GPUVars = 7;
const CabStatesN: CabStates = 15;
const EMStatesN: EMStates = 18;
const EquationsN: Equations = 9;
const ParticleVarsN: ParticleVars = 10;
const ViewModesN: ViewModes = 3;
const CurPrevN: CurPrev = 2;
const CurPrevBothN: CurPrevBoth = 3;
const NPanelsN: NPanels = 3;
const SpinfieldStatesN: SpinfieldStates = 34;
const StdStatesN: StdStates = 37;
const WaveStatesN: WaveStates = 7;

//////// import: "funcs.go"
alias MinusPlusOne = i32; //enums:enum
const  Minus1: MinusPlusOne = 0;
const  Plus1: MinusPlusOne  = 1;
alias NeighWeights = i32; //enums:enum
const  LaplacianWts: NeighWeights = 0;
const  AverageWts: NeighWeights = 1;
const  Grad18Wts: NeighWeights = 2;
const  Average27Sum = f32(20.104084);
const  OneoAverage27Sum = 0.049741138;
fn Laplacian26(x: i32,y: i32,z: i32,vidx: i32,tidx: i32, ctr: f32) -> f32 {
	var avg = f32(0);
	for (var j=0; j<26; j++) {
		var xo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(0))];
		var yo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(1))];
		var zo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(2))];
		var nv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z + zo), u32(y + yo), u32(x + xo), u32(vidx), u32(tidx)));
		avg += NeighWts[Index2D(TensorStrides[20], TensorStrides[21], u32(LaplacianWts), u32(j))] * (nv - ctr);
	}return avg;
}
fn Gradient18(x: i32,y: i32,z: i32,vidx: i32,tidx: i32) -> vec3<f32> {
	var g: vec3<f32>;
	for (var xyz=0; xyz<3; xyz++) {
		var sum = f32(0);
		for (var j=0; j<9; j++) {
			var xp = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Plus1), u32(j), u32(0))];
			var xm = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Minus1), u32(j), u32(0))];
			var yp = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Plus1), u32(j), u32(1))];
			var ym = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Minus1), u32(j), u32(1))];
			var zp = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Plus1), u32(j), u32(2))];
			var zm = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Minus1), u32(j), u32(2))];
			var grad = NeighWts[Index2D(TensorStrides[20], TensorStrides[21], u32(Grad18Wts), u32(j))] * (StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z + zp), u32(y + yp), u32(x + xp), u32(vidx), u32(tidx))) - StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z + zm), u32(y + ym), u32(x + xm), u32(vidx), u32(tidx))));
			sum += grad;
		}
		switch (xyz) {
		case 0: {
			g.x = sum;
		}
		case 1: {
			g.y = sum;
		}
		case 2: {
			g.z = sum;
		}
		default: {
		}
		}
	}return g;
}

//////// import: "klein-gordon.go"
alias CabStates = i32; //enums:enum -trim-prefix=Cab
const  CabPosA: CabStates = 0;
const  CabPosB: CabStates = 1;
const  CabVelA: CabStates = 2;
const  CabVelB: CabStates = 3;
const  CabForceA: CabStates = 4;
const  CabForceB: CabStates = 5;
const  CabV: CabStates = 6;
const  CabCC: CabStates = 7;
const  CabCharge: CabStates = 8;
const  CabCurrentX: CabStates = 9;
const  CabCurrentY: CabStates = 10;
const  CabCurrentZ: CabStates = 11;
const  CabKinetic: CabStates = 12;
const  CabPotential: CabStates = 13;
const  CabEnergy: CabStates = 14;

//////// import: "maxwell.go"
alias EMStates = i32; //enums:enum
const  A0s: EMStates = 0;
const  AXs: EMStates = 1;
const  AYs: EMStates = 2;
const  AZs: EMStates = 3;
const  A0v: EMStates = 4;
const  AXv: EMStates = 5;
const  AYv: EMStates = 6;
const  AZv: EMStates = 7;
const  EX: EMStates = 8;
const  EY: EMStates = 9;
const  EZ: EMStates = 10;
const  BX: EMStates = 11;
const  BY: EMStates = 12;
const  BZ: EMStates = 13;
const  Charge: EMStates = 14;
const  CurrentX: EMStates = 15;
const  CurrentY: EMStates = 16;
const  CurrentZ: EMStates = 17;

//////// import: "params.go"
alias Equations = i32; //enums:enum
const  Wave: Equations = 0;
const  KleinGordon: Equations = 1;
const  KleinGordonC: Equations = 2;
const  Schrodinger: Equations = 3;
const  Maxwell: Equations = 4;
const  Dirac: Equations = 5;
const  Electroweak: Equations = 6;
const  Spinfield: Equations = 7;
const  ParticleMove: Equations = 8;
const  Pi       = 3.14159265358979323846264338327950288419716939937510582097494459;
const  TwoPi    = 2 * Pi;
const  InvTwoPi = 1.0 / TwoPi;
struct Parameters {
	ThreeD: i32,
	Edges: Edges,
	Energy: i32,
	C: f32,
	Hbar: f32,
	Mass: f32,
	VPotential: f32,
	EM: i32,
	A0NoWave: i32,
	E: f32,
	Mu0: f32,
	Move: i32,
	HiggsMu: f32,
	HiggsLambda: f32,
	GW: f32,
	GpW: f32,
	Diff: f32,
	Decay: f32,
	CSq: f32,
	Inv2CSq: f32,
	MOverHSq: f32,
	HSqOver2M: f32,
	HEOver2MCSq: f32,
	Omega0: f32,
	HOverMC: f32,
	MOver2: f32,
	MCSq: f32,
	C6M2: f32,
	Eps0: f32,
	OneoEps0: f32,
	E2OverH: f32,
	EOverHSq: f32,
	HiggsMuSq: f32,
	HiggsV: f32,
	MW: f32,
	MZ: f32,
}

//////// import: "particle.go"
const NParticles = 4;
alias ParticleVars = i32; //enums:enum -trim-prefix=Particle
const  ParticleType: ParticleVars = 0;
const  ParticleMass: ParticleVars = 1;
const  ParticlePosX: ParticleVars = 2;
const  ParticlePosY: ParticleVars = 3;
const  ParticlePosZ: ParticleVars = 4;
const  ParticleVelX: ParticleVars = 5;
const  ParticleVelY: ParticleVars = 6;
const  ParticleVelZ: ParticleVars = 7;
const  ParticleLorentz: ParticleVars = 8;
const  ParticleESq: ParticleVars = 9;

//////// import: "schrodinger.go"

//////// import: "settings.go"
alias ViewModes = i32; //enums:enum
const  Plane: ViewModes = 0;
const  Bars: ViewModes = 1;
const  Vectors: ViewModes = 2;
alias CurPrev = i32; //enums:enum
const  Current: CurPrev = 0;
const  Previous: CurPrev = 1;
alias CurPrevBoth = i32; //enums:enum
const  CurOnly: CurPrevBoth = 0;
const  PrevOnly: CurPrevBoth = 1;
const  Both: CurPrevBoth = 2;
alias NPanels = i32; //enums:enum -trim-prefix=Panels
const  PanelsOne: NPanels = 0;
const  PanelsTwo: NPanels = 1;
const  PanelsFour: NPanels = 2;

//////// import: "slmath-math.go"
const SLPi = 3.141592653589793;

//////// import: "slmath-matrix3.go"

//////// import: "slmath-quaternion.go"

//////// import: "slmath-vector2.go"

//////// import: "slmath-vector3.go"

//////// import: "spinfield.go"
alias SpinfieldStates = CabStates; //enums:enum -trim-prefix=Spinfield
const  SpinfieldParticle: SpinfieldStates = 15;
const  SpinfieldPvelX: SpinfieldStates = 16;
const  SpinfieldPvelY: SpinfieldStates = 17;
const  SpinfieldPvelZ: SpinfieldStates = 18;
const  SpinfieldPESq: SpinfieldStates = 19;
const  SpinfieldDist: SpinfieldStates = 20;
const  SpinfieldDrive: SpinfieldStates = 21;
const  SpinfieldHiggs0a: SpinfieldStates = 22;
const  SpinfieldHiggs0b: SpinfieldStates = 23;
const  SpinfieldHiggs1a: SpinfieldStates = 24;
const  SpinfieldHiggs1b: SpinfieldStates = 25;
const  Spinfield0a: SpinfieldStates = 26;
const  Spinfield0b: SpinfieldStates = 27;
const  SpinfieldXa: SpinfieldStates = 28;
const  SpinfieldXb: SpinfieldStates = 29;
const  SpinfieldYa: SpinfieldStates = 30;
const  SpinfieldYb: SpinfieldStates = 31;
const  SpinfieldZa: SpinfieldStates = 32;
const  SpinfieldZb: SpinfieldStates = 33;

//////// import: "standard.go"
alias StdStates = EMStates; //enums:enum -trim-prefix=Std
const  StdCs0a: StdStates = 18;
const  StdCs0b: StdStates = 19;
const  StdCs1a: StdStates = 20;
const  StdCs1b: StdStates = 21;
const  StdCv0a: StdStates = 22;
const  StdCv0b: StdStates = 23;
const  StdCv1a: StdStates = 24;
const  StdCv1b: StdStates = 25;
const  StdHs0a: StdStates = 26;
const  StdHs0b: StdStates = 27;
const  StdHs1a: StdStates = 28;
const  StdH1b: StdStates = 29;
const  StdHv0a: StdStates = 30;
const  StdHv0b: StdStates = 31;
const  StdHv1a: StdStates = 32;
const  StdHv1b: StdStates = 33;
const  StdWp: StdStates = 34;
const  StdWn: StdStates = 35;
const  StdZ0: StdStates = 36;

//////// import: "wave.go"
alias WaveStates = i32; //enums:enum -trim-prefix=Wave
const  WavePos: WaveStates = 0;
const  WaveVel: WaveStates = 1;
const  WaveForce: WaveStates = 2;
const  WaveV: WaveStates = 3;
const  WaveKinetic: WaveStates = 4;
const  WavePotential: WaveStates = 5;
const  WaveEnergy: WaveStates = 6;

//////// import: "slrand.wgsl"
fn Philox2x32round(counter: su64, key: u32) -> su64 {
	let mul = Uint32Mul64(u32(0xD256D193), counter.x);
	var ctr: su64;
	ctr.x = mul.y ^ key ^ counter.y;
	ctr.y = mul.x;
	return ctr;
}
fn Philox2x32bumpkey(key: u32) -> u32 {
	return key + u32(0x9E3779B9);
}
fn Philox2x32(counter: su64, key: u32) -> vec2<u32> {
	var ctr = Philox2x32round(counter, key); // 1
	var ky = Philox2x32bumpkey(key);
	ctr = Philox2x32round(ctr, ky); // 2
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 3
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 4
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 5
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 6
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 7
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 8
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 9
	ky = Philox2x32bumpkey(ky);
	return Philox2x32round(ctr, ky); // 10
}
fn RandUint32Vec2(counter: su64, funcIndex: u32, key: u32) -> vec2<u32> {
	return Philox2x32(Uint64Add32(counter, funcIndex), key);
}
fn RandUint32(counter: su64, funcIndex: u32, key: u32) -> u32 {
	return Philox2x32(Uint64Add32(counter, funcIndex), key).x;
}
fn RandFloat32Vec2(counter: su64, funcIndex: u32, key: u32) -> vec2<f32> {
	return Uint32ToFloat32Vec2(RandUint32Vec2(counter, funcIndex, key));
}
fn RandFloat32(counter: su64, funcIndex: u32, key: u32) -> f32 { 
	return Uint32ToFloat32(RandUint32(counter, funcIndex, key));
}
fn RandFloat32Range11Vec2(counter: su64, funcIndex: u32, key: u32) -> vec2<f32> {
	return Uint32ToFloat32Vec2(RandUint32Vec2(counter, funcIndex, key));
}
fn RandFloat32Range11(counter: su64, funcIndex: u32, key: u32) -> f32 { 
	return Uint32ToFloat32Range11(RandUint32(counter, funcIndex, key));
}
fn RandBoolP(counter: su64, funcIndex: u32, key: u32, p: f32) -> bool { 
	return (RandFloat32(counter, funcIndex, key) < p);
}
fn sincospi(x: f32) -> vec2<f32> {
	let PIf = 3.1415926535897932;
	var r: vec2<f32>;
	r.x = cos(PIf*x);
	r.y = sin(PIf*x);
	return r;
}
fn RandFloat32NormVec2(counter: su64, funcIndex: u32, key: u32) -> vec2<f32> { 
	let ur = RandUint32Vec2(counter, funcIndex, key);
	var f = sincospi(Uint32ToFloat32Range11(ur.x));
	let r = sqrt(-2.0 * log(Uint32ToFloat32(ur.y))); // guaranteed to avoid 0.
	return f * r;
}
fn RandFloat32Norm(counter: su64, funcIndex: u32, key: u32) -> f32 { 
	return RandFloat32Vec2(counter, funcIndex, key).x;
}
fn RandUint32N(counter: su64, funcIndex: u32, key: u32, n: u32) -> u32 { 
	let v = RandFloat32(counter, funcIndex, key);
	return u32(v * f32(n));
}
struct RandCounter {
	Counter: su64,
	HiSeed: u32,
	pad: u32,
}
fn RandCounter_Reset(ct: ptr<function,RandCounter>) {
	(*ct).Counter.x = u32(0);
	(*ct).Counter.y = (*ct).HiSeed;
}
fn RandCounter_Seed(ct: ptr<function,RandCounter>, seed: u32) {
	(*ct).HiSeed = seed;
	RandCounter_Reset(ct);
}
fn RandCounter_Add(ct: ptr<function,RandCounter>, inc: u32) {
	(*ct).Counter = Uint64Add32((*ct).Counter, inc);
}

//////// import: "sltype.wgsl"
alias su64 = vec2<u32>;
fn Uint32Mul64(a: u32, b: u32) -> su64 {
	let LOMASK = (((u32(1))<<16)-1);
	var r: su64;
	r.x = a * b;               /* full low multiply */
	let ahi = a >> 16;
	let alo = a & LOMASK;
	let bhi = b >> 16;
	let blo = b & LOMASK;
	let ahbl = ahi * blo;
	let albh = alo * bhi;
	let ahbl_albh = ((ahbl&LOMASK) + (albh&LOMASK));
	var hit = ahi*bhi + (ahbl>>16) +  (albh>>16);
	hit += ahbl_albh >> 16; /* carry from the sum of lo(ahbl) + lo(albh) ) */
	/* carry from the sum with alo*blo */
	if ((r.x >> u32(16)) < (ahbl_albh&LOMASK)) {
		hit += u32(1);
	}
	r.y = hit; 
	return r;
}
/*
fn Uint32Mul64(a: u32, b: u32) -> su64 {
	return su64(a) * su64(b);
}
*/
fn Uint64Add32(a: su64, b: u32) -> su64 {
	if (b == 0) {
		return a;
	}
	var s = a;
	if (s.x > u32(0xffffffff) - b) {
		s.y++;
		s.x = (b - 1) - (u32(0xffffffff) - s.x);
	} else {
		s.x += b;
	}
	return s;
}
fn Uint64Incr(a: su64) -> su64 {
	var s = a;
	if(s.x == 0xffffffff) {
		s.y++;
		s.x = u32(0);
	} else {
		s.x++;
	}
	return s;
}
fn Uint32ToFloat32(val: u32) -> f32 {
	let factor = f32(1.0) / (f32(u32(0xffffffff)) + f32(1.0));
	let halffactor = f32(0.5) * factor;
	var f = f32(val) * factor + halffactor;
	if (f == 1.0) { // exclude 1
		return bitcast<f32>(0x3F7FFFFF);
	}
	return f;
}
fn Uint32ToFloat32Vec2(val: vec2<u32>) -> vec2<f32> {
	var r: vec2<f32>;
	r.x = Uint32ToFloat32(val.x);
	r.y = Uint32ToFloat32(val.y);
	return r;
}
fn Uint32ToFloat32Range11(val: u32) -> f32 {
	let factor = f32(1.0) / (f32(i32(0x7fffffff)) + f32(1.0));
	let halffactor = f32(0.5) * factor;
	return (f32(val) * factor + halffactor);
}
fn Uint32ToFloat32Range11Vec2(val: vec2<u32>) -> vec2<f32> {
	var r: vec2<f32>;
	r.x = Uint32ToFloat32Range11(val.x);
	r.y = Uint32ToFloat32Range11(val.y);
	return r;
}