// Code generated by "gosl"; DO NOT EDIT
// kernel: ElectroweakKernel

// // Params contains the full set of simulation parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> Params: array<Parameters>;
@group(0) @binding(2)
var<storage, read_write> NeighOffs: array<i32>;
@group(0) @binding(3)
var<storage, read_write> FaceOffs: array<i32>;
@group(0) @binding(4)
var<storage, read_write> NeighWts: array<f32>;
// // Ctx has the Context state values. 
@group(1) @binding(0)
var<storage, read> Ctx: array<Context>;
@group(1) @binding(2)
var<storage, read_write> State0: array<f32>;
@group(1) @binding(3)
var<storage, read_write> State1: array<f32>;
@group(1) @binding(4)
var<storage, read_write> State2: array<f32>;
@group(1) @binding(5)
var<storage, read_write> State3: array<f32>;
@group(1) @binding(6)
var<storage, read_write> State4: array<f32>;
@group(1) @binding(7)
var<storage, read_write> State5: array<f32>;
@group(1) @binding(8)
var<storage, read_write> State6: array<f32>;
@group(1) @binding(9)
var<storage, read_write> State7: array<f32>;
@group(1) @binding(10)
var<storage, read_write> State8: array<f32>;
@group(1) @binding(11)
var<storage, read_write> State9: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	ElectroweakKernel(idx);
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}

fn Index4D(s0: u32, s1: u32, s2: u32, s3: u32, i0: u32, i1: u32, i2: u32, i3: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3;
}

fn StateGet(ix: u32) -> f32 {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		return State0[ix];
	}
	case u32(1): {
		return State1[ix - 536870904];
	}
	case u32(2): {
		return State2[ix - 1073741808];
	}
	case u32(3): {
		return State3[ix - 1610612712];
	}
	case u32(4): {
		return State4[ix - 2147483616];
	}
	case u32(5): {
		return State5[ix - 2684354520];
	}
	case u32(6): {
		return State6[ix - 3221225424];
	}
	case u32(7): {
		return State7[ix - 3758096328];
	}
	case u32(8): {
		return State8[ix - 4294967232];
	}
	default: {
		return State9[ix - 536870840];
	}
	}
}

fn StateSet(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] = vl;
	}
	case u32(1): {
		State1[ix - 536870904] = vl;
	}
	case u32(2): {
		State2[ix - 1073741808] = vl;
	}
	case u32(3): {
		State3[ix - 1610612712] = vl;
	}
	case u32(4): {
		State4[ix - 2147483616] = vl;
	}
	case u32(5): {
		State5[ix - 2684354520] = vl;
	}
	case u32(6): {
		State6[ix - 3221225424] = vl;
	}
	case u32(7): {
		State7[ix - 3758096328] = vl;
	}
	case u32(8): {
		State8[ix - 4294967232] = vl;
	}
	default: {
		State9[ix - 536870840] = vl;
	}
	}
}

fn StateSetAdd(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] += vl;
	}
	case u32(1): {
		State1[ix - 536870904] += vl;
	}
	case u32(2): {
		State2[ix - 1073741808] += vl;
	}
	case u32(3): {
		State3[ix - 1610612712] += vl;
	}
	case u32(4): {
		State4[ix - 2147483616] += vl;
	}
	case u32(5): {
		State5[ix - 2684354520] += vl;
	}
	case u32(6): {
		State6[ix - 3221225424] += vl;
	}
	case u32(7): {
		State7[ix - 3758096328] += vl;
	}
	case u32(8): {
		State8[ix - 4294967232] += vl;
	}
	default: {
		State9[ix - 536870840] += vl;
	}
	}
}

fn StateSetSub(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] -= vl;
	}
	case u32(1): {
		State1[ix - 536870904] -= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] -= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] -= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] -= vl;
	}
	case u32(5): {
		State5[ix - 2684354520] -= vl;
	}
	case u32(6): {
		State6[ix - 3221225424] -= vl;
	}
	case u32(7): {
		State7[ix - 3758096328] -= vl;
	}
	case u32(8): {
		State8[ix - 4294967232] -= vl;
	}
	default: {
		State9[ix - 536870840] -= vl;
	}
	}
}

fn StateSetMul(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] *= vl;
	}
	case u32(1): {
		State1[ix - 536870904] *= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] *= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] *= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] *= vl;
	}
	case u32(5): {
		State5[ix - 2684354520] *= vl;
	}
	case u32(6): {
		State6[ix - 3221225424] *= vl;
	}
	case u32(7): {
		State7[ix - 3758096328] *= vl;
	}
	case u32(8): {
		State8[ix - 4294967232] *= vl;
	}
	default: {
		State9[ix - 536870840] *= vl;
	}
	}
}

fn StateSetDiv(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] /= vl;
	}
	case u32(1): {
		State1[ix - 536870904] /= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] /= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] /= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] /= vl;
	}
	case u32(5): {
		State5[ix - 2684354520] /= vl;
	}
	case u32(6): {
		State6[ix - 3221225424] /= vl;
	}
	case u32(7): {
		State7[ix - 3758096328] /= vl;
	}
	case u32(8): {
		State8[ix - 4294967232] /= vl;
	}
	default: {
		State9[ix - 536870840] /= vl;
	}
	}
}

fn Index5D(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, i0: u32, i1: u32, i2: u32, i3: u32, i4: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3 + s4 * i4;
}


//////// import: "vars.go"

//////// import: "context.go"
struct Context {
	Size: vec4<i32>,
	NVars: i32,
	Step: i32,
	CurState: i32,
	pad: i32,
	RandCounter: RandCounter,
}
fn Context_StateCoords(ctx: Context, idx: u32, x: ptr<function,i32>,y: ptr<function,i32>,z: ptr<function,i32>) -> bool {
	var szxy = ctx.Size.x * ctx.Size.y;
	*z = i32(idx) / szxy;
	var rz = i32(idx) % szxy;
	var szx = ctx.Size.x;
	*y = rz / szx;
	*x = rz % szx;
	if (*z >= ctx.Size.z || *y >= ctx.Size.y || *x >= ctx.Size.x) {
		return false;
	}
	*z += i32(1);
	*y += i32(1);
	*x += i32(1);
return true;
}
fn Context_PrevState(ctx: Context) -> i32 {
	return 1 - ctx.CurState;
}

//////// import: "dirac.go"
alias DiracStates = EMStates; //enums:enum -trim-prefix=Dirac
const  Dirac1As: DiracStates = 18;
const  Dirac1Bs: DiracStates = 19;
const  Dirac2As: DiracStates = 20;
const  Dirac2Bs: DiracStates = 21;
const  Dirac1Av: DiracStates = 22;
const  Dirac1Bv: DiracStates = 23;
const  Dirac2Av: DiracStates = 24;
const  Dirac2Bv: DiracStates = 25;
const  DiracV: DiracStates = 26;
const  DiracMag: DiracStates = 27;
const  DiracL1As: DiracStates = 28;
const  DiracL1Bs: DiracStates = 29;
const  DiracL2As: DiracStates = 30;
const  DiracL2Bs: DiracStates = 31;
const  DiracLMag: DiracStates = 32;

//////// import: "edges.go"
alias Edges = i32; //enums:enum -trim-prefix=Edges
const  EdgesFixed: Edges = 0;
const  EdgesWrap: Edges = 1;
const  EdgesDamp: Edges = 2;

//////// import: "electroweak.go"
alias EWStates = EMStates; //enums:enum -trim-prefix=EW
const  EWHsCa: EWStates = 18;
const  EWHsCb: EWStates = 19;
const  EWHs0a: EWStates = 20;
const  EWHs0b: EWStates = 21;
const  EWHvCa: EWStates = 22;
const  EWHvCb: EWStates = 23;
const  EWHv0a: EWStates = 24;
const  EWHv0b: EWStates = 25;
const  EWHmag: EWStates = 26;
const  EWHV: EWStates = 27;
const  EWB0s: EWStates = 28;
const  EWBXs: EWStates = 29;
const  EWBYs: EWStates = 30;
const  EWBZs: EWStates = 31;
const  EWB0v: EWStates = 32;
const  EWBXv: EWStates = 33;
const  EWBYv: EWStates = 34;
const  EWBZv: EWStates = 35;
const  EWW10s: EWStates = 36;
const  EWW1Xs: EWStates = 37;
const  EWW1Ys: EWStates = 38;
const  EWW1Zs: EWStates = 39;
const  EWW10v: EWStates = 40;
const  EWW1Xv: EWStates = 41;
const  EWW1Yv: EWStates = 42;
const  EWW1Zv: EWStates = 43;
const  EWW20s: EWStates = 44;
const  EWW2Xs: EWStates = 45;
const  EWW2Ys: EWStates = 46;
const  EWW2Zs: EWStates = 47;
const  EWW20v: EWStates = 48;
const  EWW2Xv: EWStates = 49;
const  EWW2Yv: EWStates = 50;
const  EWW2Zv: EWStates = 51;
const  EWW30s: EWStates = 52;
const  EWW3Xs: EWStates = 53;
const  EWW3Ys: EWStates = 54;
const  EWW3Zs: EWStates = 55;
const  EWW30v: EWStates = 56;
const  EWW3Xv: EWStates = 57;
const  EWW3Yv: EWStates = 58;
const  EWW3Zv: EWStates = 59;
const  EWZ0: EWStates = 60;
const  EWZX: EWStates = 61;
const  EWZY: EWStates = 62;
const  EWZZ: EWStates = 63;
const  EWWPr0: EWStates = 64;
const  EWWPrX: EWStates = 65;
const  EWWPrY: EWStates = 66;
const  EWWPrZ: EWStates = 67;
const  EWWPi0: EWStates = 68;
const  EWWPiX: EWStates = 69;
const  EWWPiY: EWStates = 70;
const  EWWPiZ: EWStates = 71;
const  EWWMag: EWStates = 72;
const YPhi = 0.5;
const InvSqrt2 = 0.70710678118654752440;
fn EWGaugeAct(w1: f32,w2: f32,w3: f32,b: f32, psi: vec4<f32>) -> vec4<f32> {
	var hg = 0.5 * Params[0].GW;
	var gy = Params[0].GpW * YPhi;
	var du = hg*w3 + gy*b;
	var dd = -hg*w3 + gy*b;
	var or = hg * w1;
	var oi = -hg * w2;
	var o: vec4<f32>;
	o.x = du*psi.y + or*psi.w + oi*psi.z;
	o.y = -(du*psi.x + or*psi.z - oi*psi.w);
	o.z = or*psi.y - oi*psi.x + dd*psi.w;
	o.w = -(or*psi.x + oi*psi.y + dd*psi.z);
return o;
}
fn EWCurrent(psi: vec4<f32>,d: vec4<f32>) -> vec4<f32> {
	var hg = 0.5 * Params[0].GW;
	var gy = Params[0].GpW * YPhi;
	var j: vec4<f32>;
	j.x = hg * ((psi.x*d.w - psi.y*d.z) + (psi.z*d.y - psi.w*d.x));
	j.y = hg * (-(psi.x*d.z + psi.y*d.w) + (psi.z*d.x + psi.w*d.y));
	j.z = hg * ((psi.x*d.y - psi.y*d.x) - (psi.z*d.w - psi.w*d.z));
	j.w = gy * ((psi.x*d.y - psi.y*d.x) + (psi.z*d.w - psi.w*d.z));
return j;
}
fn EWDiv(x: i32,y: i32,z: i32,vX: i32,tidx: i32) -> f32 {
	var gx = Gradient10(x, y, z, vX, tidx);
	var gy = Gradient10(x, y, z, vX+1, tidx);
	var gz = Gradient10(x, y, z, vX+2, tidx);
return gx.x + gy.y + gz.z;
}
fn EWCrossUp(a0: vec3<f32>,ax: vec3<f32>,ay: vec3<f32>,az: vec3<f32>,b0: vec3<f32>,bx: vec3<f32>,by: vec3<f32>,bz: vec3<f32>) -> vec3<f32> {
	var r = Cross3(a0, b0);
	r = r+(Cross3(ax, bx));
	r = r+(Cross3(ay, by));
	r = r+(Cross3(az, bz));
return r;
}
fn EWCrossLor(a0: vec3<f32>,ax: vec3<f32>,ay: vec3<f32>,az: vec3<f32>,b0: vec3<f32>,bx: vec3<f32>,by: vec3<f32>,bz: vec3<f32>) -> vec3<f32> {
	var r = Cross3(a0, b0);
	r = r-(Cross3(ax, bx));
	r = r-(Cross3(ay, by));
	r = r-(Cross3(az, bz));
return r;
}
fn EWBorisRot3(v: vec3<f32>,om: vec3<f32>) -> vec3<f32> {
	var t = om*(0.5);
	var vp = v+(Cross3(v, t));
	var s = t*(2.0 / (1.0 + LengthSquared3(t)));
return v+(Cross3(vp, s));
}
fn EWBorisPhase(w1: f32,w2: f32,w3: f32,b: f32,theta: f32, v: vec4<f32>) -> vec4<f32> {
	var hg = 0.5 * Params[0].GW;
	var m = vec3<f32>(hg*w1, hg*w2, hg*w3);
	var al = Params[0].GpW * YPhi * b;
	var mag = Length3(m);
	var nx: f32;
	var ny: f32;
	var nz: f32;
	var sn: f32;
	if (mag > 1.0e-12) {
		nx = m.x / mag;
		ny = m.y / mag;
		nz = m.z / mag;
		sn = sin(theta * mag);
	}
	var cs = cos(theta * mag);
	var p1r = nz*v.x + nx*v.z + ny*v.w;
	var p1i = nz*v.y + nx*v.w - ny*v.z;
	var p2r = nx*v.x - ny*v.y - nz*v.z;
	var p2i = nx*v.y + ny*v.x - nz*v.w;
	var q1r = cs*v.x - sn*p1i;
	var q1i = cs*v.y + sn*p1r;
	var q2r = cs*v.z - sn*p2i;
	var q2i = cs*v.w + sn*p2r;
	var ca = cos(theta * al);
	var sa = sin(theta * al);
return vec4<f32>(ca*q1r-sa*q1i, ca*q1i+sa*q1r, ca*q2r-sa*q2i, ca*q2i+sa*q2r);
}
fn ElectroweakKernel(i: u32) { //gosl:kernel
	let ctx = Ctx[0];
	var x: i32;
	var y: i32;
	var z: i32;
	var ok = Context_StateCoords(ctx, i, &x, &y, &z);
	if (!ok) {
		return;
	}
	var cur = ctx.CurState;
	var prv = Context_PrevState(ctx);
	var csq = Params[0].CSq;
	var oc = 1.0 / Params[0].C;
	var boris = Params[0].Boris == 1;
	var musq = Params[0].HiggsMuSq;
	var lambda = Params[0].HiggsLambda;
	var psi = vec4<f32>(StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHsCa), u32(prv))), StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHsCb), u32(prv))),
		StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHs0a), u32(prv))), StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHs0b), u32(prv))));
	var psv = vec4<f32>(StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHvCa), u32(prv))), StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHvCb), u32(prv))),
		StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHv0a), u32(prv))), StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42],
		TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHv0b), u32(prv))));
	var w10 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW10s), u32(prv)));
	var w1x = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW1Xs), u32(prv)));
	var w1y = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW1Ys), u32(prv)));
	var w1z = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW1Zs), u32(prv)));
	var w20 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW20s), u32(prv)));
	var w2x = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW2Xs), u32(prv)));
	var w2y = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW2Ys), u32(prv)));
	var w2z = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW2Zs), u32(prv)));
	var w30 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW30s), u32(prv)));
	var w3x = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW3Xs), u32(prv)));
	var w3y = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW3Ys), u32(prv)));
	var w3z = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW3Zs), u32(prv)));
	var b0 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWB0s), u32(prv)));
	var bx = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWBXs), u32(prv)));
	var by = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWBYs), u32(prv)));
	var bz = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42],
	TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWBZs), u32(prv)));
	var gCa = Gradient10(x, y, z, i32(EWHsCa), prv);
	var gCb = Gradient10(x, y, z, i32(EWHsCb), prv);
	var g0a = Gradient10(x, y, z, i32(EWHs0a), prv);
	var g0b = Gradient10(x, y, z, i32(EWHs0b), prv);
	var dxp = vec4<f32>(gCa.x, gCb.x, g0a.x, g0b.x); // d_x Psi
	var dyp = vec4<f32>(gCa.y, gCb.y, g0a.y, g0b.y);
	var dzp = vec4<f32>(gCa.z, gCb.z, g0a.z, g0b.z);
	var ax = EWGaugeAct(w1x, w2x, w3x, bx, psi);
	var ay = EWGaugeAct(w1y, w2y, w3y, by, psi);
	var az = EWGaugeAct(w1z, w2z, w3z, bz, psi);
	var a0 = EWGaugeAct(w10, w20, w30, b0, psi);
	var dX = dxp+(ax);
	var dY = dyp+(ay);
	var dZ = dzp+(az);
	var dtp = vec4<f32>(oc*psv.x, oc*psv.y, oc*psv.z, oc*psv.w);
	var d0 = dtp+(a0);
	var g10 = Gradient10(x, y, z, i32(EWW10s), prv);
	var g1x = Gradient10(x, y, z, i32(EWW1Xs), prv);
	var g1y = Gradient10(x, y, z, i32(EWW1Ys), prv);
	var g1z = Gradient10(x, y, z, i32(EWW1Zs), prv);
	var g20 = Gradient10(x, y, z, i32(EWW20s), prv);
	var g2x = Gradient10(x, y, z, i32(EWW2Xs), prv);
	var g2y = Gradient10(x, y, z, i32(EWW2Ys), prv);
	var g2z = Gradient10(x, y, z, i32(EWW2Zs), prv);
	var g30 = Gradient10(x, y, z, i32(EWW30s), prv);
	var g3x = Gradient10(x, y, z, i32(EWW3Xs), prv);
	var g3y = Gradient10(x, y, z, i32(EWW3Ys), prv);
	var g3z = Gradient10(x, y, z, i32(EWW3Zs), prv);
	var dvW1 = g1x.x + g1y.y + g1z.z;
	var dvW2 = g2x.x + g2y.y + g2z.z;
	var dvW3 = g3x.x + g3y.y + g3z.z;
	var dvB = EWDiv(x, y, z, i32(EWBXs), prv);
	var lap = vec4<f32>(Laplacian19(x, y, z, i32(EWHsCa), prv, psi.x),
		Laplacian19(x, y, z, i32(EWHsCb), prv, psi.y),
		Laplacian19(x, y, z, i32(EWHs0a), prv, psi.z),
		Laplacian19(x, y, z, i32(EWHs0b), prv, psi.w));
	var cov = lap+(EWGaugeAct(dvW1, dvW2, dvW3, dvB, psi));
	cov = cov+(EWGaugeAct(w1x, w2x, w3x, bx, dxp+(dX)));
	cov = cov+(EWGaugeAct(w1y, w2y, w3y, by, dyp+(dY)));
	cov = cov+(EWGaugeAct(w1z, w2z, w3z, bz, dzp+(dZ)));
	var w1xv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW1Xv), u32(prv)));
	var w1yv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW1Yv), u32(prv)));
	var w1zv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW1Zv), u32(prv)));
	var w2xv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW2Xv), u32(prv)));
	var w2yv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW2Yv), u32(prv)));
	var w2zv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW2Zv), u32(prv)));
	var w3xv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW3Xv), u32(prv)));
	var w3yv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW3Yv), u32(prv)));
	var w3zv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW3Zv), u32(prv)));
	var w10v = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW10v), u32(prv)));
	var w20v = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW20v), u32(prv)));
	var w30v = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWW30v), u32(prv)));
	var b0v = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42],
	TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWB0v), u32(prv)));
	var q0 = EWGaugeAct(oc*w10v, oc*w20v, oc*w30v, oc*b0v, psi);
	var qa = EWGaugeAct(w10, w20, w30, b0, a0);
	cov = cov-(q0)-(qa);
	if (!boris) {
		var qv = EWGaugeAct(w10, w20, w30, b0, dtp);
		cov = cov-(qv)-(qv);
	}
	var mag = psi.x*psi.x + psi.y*psi.y + psi.z*psi.z + psi.w*psi.w;
	var vfac = musq - lambda*mag;
	var hf = vec4<f32>(csq*(cov.x+vfac*psi.x), csq*(cov.y+vfac*psi.y),
		csq*(cov.z+vfac*psi.z), csq*(cov.w+vfac*psi.w));
	var j0 = EWCurrent(psi, d0);
	var jx = EWCurrent(psi, dX);
	var jy = EWCurrent(psi, dY);
	var jz = EWCurrent(psi, dZ);
	var ym0: vec3<f32>;
	var ymx: vec3<f32>;
	var ymy: vec3<f32>;
	var ymz: vec3<f32>;
	if (Params[0].YangMills == 1) {
		var gw = Params[0].GW;
		var w0 = vec3<f32>(w10, w20, w30);
		var wb = w0;
		if (boris) {
			wb = vec3<f32>(0, 0, 0);
		}
		var wx = vec3<f32>(w1x, w2x, w3x);
		var wy = vec3<f32>(w1y, w2y, w3y);
		var wz = vec3<f32>(w1z, w2z, w3z);
		var t0 = vec3<f32>(w10v, w20v, w30v)*(oc);
		var tx = vec3<f32>(w1xv, w2xv, w3xv)*(oc);
		var ty = vec3<f32>(w1yv, w2yv, w3yv)*(oc);
		var tz = vec3<f32>(w1zv, w2zv, w3zv)*(oc);
		var x0 = vec3<f32>(g10.x, g20.x, g30.x);
		var y0 = vec3<f32>(g10.y, g20.y, g30.y);
		var z0 = vec3<f32>(g10.z, g20.z, g30.z);
		var xx = vec3<f32>(g1x.x, g2x.x, g3x.x);
		var yx = vec3<f32>(g1x.y, g2x.y, g3x.y);
		var zx = vec3<f32>(g1x.z, g2x.z, g3x.z);
		var xy = vec3<f32>(g1y.x, g2y.x, g3y.x);
		var yy = vec3<f32>(g1y.y, g2y.y, g3y.y);
		var zy = vec3<f32>(g1y.z, g2y.z, g3y.z);
		var xz = vec3<f32>(g1z.x, g2z.x, g3z.x);
		var yz = vec3<f32>(g1z.y, g2z.y, g3z.y);
		var zz = vec3<f32>(g1z.z, g2z.z, g3z.z);
		var dv = t0+(xx)+(yy)+(zz);
		ym0 = EWCrossUp(wb, wx, wy, wz, t0, x0, y0, z0)*(2 * gw);
		ym0 = ym0-(EWCrossLor(w0, wx, wy, wz, t0, tx, ty, tz)*(gw));
		ym0 = ym0-(EWCrossLor(w0, wx, wy, wz,
			Cross3(w0, w0), Cross3(wx, w0),
			Cross3(wy, w0), Cross3(wz, w0))*(gw * gw));
		ym0 = ym0+(Cross3(dv, w0)*(gw));
		ymx = EWCrossUp(wb, wx, wy, wz, tx, xx, yx, zx)*(2 * gw);
		ymx = ymx+(EWCrossLor(w0, wx, wy, wz, x0, xx, xy, xz)*(gw));
		ymx = ymx-(EWCrossLor(w0, wx, wy, wz,
			Cross3(w0, wx), Cross3(wx, wx),
			Cross3(wy, wx), Cross3(wz, wx))*(gw * gw));
		ymx = ymx+(Cross3(dv, wx)*(gw));
		ymy = EWCrossUp(wb, wx, wy, wz, ty, xy, yy, zy)*(2 * gw);
		ymy = ymy+(EWCrossLor(w0, wx, wy, wz, y0, yx, yy, yz)*(gw));
		ymy = ymy-(EWCrossLor(w0, wx, wy, wz,
			Cross3(w0, wy), Cross3(wx, wy),
			Cross3(wy, wy), Cross3(wz, wy))*(gw * gw));
		ymy = ymy+(Cross3(dv, wy)*(gw));
		ymz = EWCrossUp(wb, wx, wy, wz, tz, xz, yz, zz)*(2 * gw);
		ymz = ymz+(EWCrossLor(w0, wx, wy, wz, z0, zx, zy, zz)*(gw));
		ymz = ymz-(EWCrossLor(w0, wx, wy, wz,
			Cross3(w0, wz), Cross3(wx, wz),
			Cross3(wy, wz), Cross3(wz, wz))*(gw * gw));
		ymz = ymz+(Cross3(dv, wz)*(gw));
	}
	var omW = vec3<f32>(w10, w20, w30)*(-2 * Params[0].GW * Params[0].C);
	var nw = Params[0].A0NoWave == 1;
	EWWStep(x, y, z, cur, prv, i32(i32(0)), csq, omW, vec3<f32>(j0.x+ym0.x, j0.y+ym0.y, j0.z+ym0.z), boris, nw);
	EWWStep(x, y, z, cur, prv, i32(i32(1)), csq, omW, vec3<f32>(jx.x+ymx.x, jx.y+ymx.y, jx.z+ymx.z), boris, nw);
	EWWStep(x, y, z, cur, prv, i32(i32(2)), csq, omW, vec3<f32>(jy.x+ymy.x, jy.y+ymy.y, jy.z+ymy.z), boris, nw);
	EWWStep(x, y, z, cur, prv, i32(i32(3)), csq, omW, vec3<f32>(jz.x+ymz.x, jz.y+ymz.y, jz.z+ymz.z), boris, nw);
	EWGaugeStep(x, y, z, cur, prv, i32(EWB0s), csq, j0.w, jx.w, jy.w, jz.w, nw);
	var hvN: vec4<f32>;
	if (boris) {
		var hh = hf*(0.5);
		hvN = EWBorisPhase(w10, w20, w30, b0, 2*Params[0].C, psv+(hh))+(hh);
	} else {
		hvN = psv+(hf);
	}
	var hvCaN = hvN.x;
	var hvCbN = hvN.y;
	var hv0aN = hvN.z;
	var hv0bN = hvN.w;
	StateSet(psi.x + hvCaN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHsCa), u32(cur)));
	StateSet(psi.y + hvCbN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHsCb), u32(cur)));
	StateSet(psi.z + hv0aN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHs0a), u32(cur)));
	StateSet(psi.w + hv0bN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHs0b), u32(cur)));
	StateSet(hvCaN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHvCa), u32(cur)));
	StateSet(hvCbN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHvCb), u32(cur)));
	StateSet(hv0aN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHv0a), u32(cur)));
	StateSet(hv0bN, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42],
	TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHv0b), u32(cur)));
	var sw = Params[0].SinThetaW;
	var cw = Params[0].CosThetaW;
	for (var k=0; k<4; k++) {
		var ki = i32(k);
		var w3s = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWW30s) + ki), u32(cur)));
		var w3v = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWW30v) + ki), u32(cur)));
		var bs = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWB0s) + ki), u32(cur)));
		var bv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWB0v) + ki), u32(cur)));
		StateSet(sw*w3s + cw*bs, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(A0s) + ki), u32(cur)));
		StateSet(sw*w3v + cw*bv, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(A0v) + ki), u32(cur)));
		StateSet(cw*w3s - sw*bs, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWZ0) + ki), u32(cur)));
		var w1s = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWW10s) + ki), u32(cur)));
		var w2s = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWW20s) + ki), u32(cur)));
		StateSet(w1s * InvSqrt2, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWWPr0) + ki), u32(cur)));
		StateSet(-w2s * InvSqrt2, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWWPi0) + ki), u32(cur)));
	}
	var wm = f32(0);
	for (var k=0; k<4; k++) {
		var ki = i32(k);
		var w1s = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWW10s) + ki), u32(cur)));
		var w2s = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(i32(EWW20s) + ki), u32(cur)));
		wm += 0.5 * (w1s*w1s + w2s*w2s);
	}
	StateSet(wm, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWWMag), u32(cur)));
	StateSet(mag, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHmag), u32(cur)));
	StateSet(-0.5*musq*mag + 0.25*lambda*mag*mag, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42],
	TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(EWHV), u32(cur)));
}
fn EWWStep(x: i32,y: i32,z: i32,cur: i32,prv: i32,nu: i32, csq: f32, om: vec3<f32>,src: vec3<f32>, boris: bool,noWave: bool) {
	var vs = i32(EWW10s) + nu;
	var vv = i32(EWW10v) + nu;
	var p1 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs), u32(prv)));
	var p2 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs + 8), u32(prv)));
	var p3 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs + 16), u32(prv)));
	var l1 = Laplacian19(x, y, z, vs, prv, p1);
	var l2 = Laplacian19(x, y, z, vs+8, prv, p2);
	var l3 = Laplacian19(x, y, z, vs+16, prv, p3);
	var f = vec3<f32>(csq*(l1+src.x), csq*(l2+src.y), csq*(l3+src.z));
	var q1 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv), u32(prv)));
	var q2 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv + 8), u32(prv)));
	var q3 = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv + 16), u32(prv)));
	var v = vec3<f32>(q1, q2, q3);
	var vn: vec3<f32>;
	if (noWave && nu == 0) {
		vn = f;
	} else if (boris) {
		var h = f*(0.5);
		vn = EWBorisRot3(v+(h), om)+(h);
	} else {
		vn = v+(f);
	}
	StateSet(vn.x, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv), u32(cur)));
	StateSet(vn.y, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv + 8), u32(cur)));
	StateSet(vn.z, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv + 16), u32(cur)));
	StateSet(p1 + vn.x, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs), u32(cur)));
	StateSet(p2 + vn.y, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs + 8), u32(cur)));
	StateSet(p3 + vn.z, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42],
	TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs + 16), u32(cur)));
}
fn EWGaugeStep(x: i32,y: i32,z: i32,cur: i32,prv: i32,v0: i32, csq: f32,j0: f32,jx: f32,jy: f32,jz: f32, noWave: bool) {
	for (var ki=0; ki<4; ki++) {
		var k = i32(ki);
		var vs = v0 + k;
		var vv = v0 + 4 + k;
		var jc: f32;
		switch (ki) {
		case 0: {
			jc = j0;
		}
		case 1: {
			jc = jx;
		}
		case 2: {
			jc = jy;
		}
		default: {
			jc = jz;
		}
		}
		var ps = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs), u32(prv)));
		var vp = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv), u32(prv)));
		var f = csq * (Laplacian19(x, y, z, vs, prv, ps) + jc);
		var vc = vp + f;
		if (noWave && ki == 0) {
			vc = f; // see EWWStep: the scalar potential is the gauge direction
		}
		StateSet(vc, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vv), u32(cur)));
		StateSet(ps + vc, Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z), u32(y), u32(x), u32(vs), u32(cur)));
	}
}

//////// import: "enumgen.go"
const DiracStatesN: DiracStates = 33;
const EdgesN: Edges = 3;
const EWStatesN: EWStates = 73;
const MinusPlusOneN: MinusPlusOne = 2;
const NeighWeightsN: NeighWeights = 3;
const GPUVarsN: GPUVars = 7;
const CabStatesN: CabStates = 24;
const EMStatesN: EMStates = 18;
const EquationsN: Equations = 12;
const ParticleVarsN: ParticleVars = 10;
const ViewModesN: ViewModes = 3;
const CurPrevN: CurPrev = 2;
const CurPrevBothN: CurPrevBoth = 3;
const NPanelsN: NPanels = 3;
const SpinfieldStatesN: SpinfieldStates = 43;
const WaveStatesN: WaveStates = 7;
const WaveCStatesN: WaveCStates = 3;
const WeylStatesN: WeylStates = 29;

//////// import: "funcs.go"
alias MinusPlusOne = i32; //enums:enum
const  Minus1: MinusPlusOne = 0;
const  Plus1: MinusPlusOne  = 1;
alias NeighWeights = i32; //enums:enum
const  NNeigh = 26;
const  NLapNeigh = 18;
const  NGradPair = 5;
const  LaplacianWts: NeighWeights = 0;
const  AverageWts: NeighWeights = 1;
const  Grad10Wts: NeighWeights = 2;
const  Average27Sum = f32(20.104084);
const  OneoAverage27Sum = 0.049741138;
fn Laplacian19(x: i32,y: i32,z: i32,vidx: i32,tidx: i32, ctr: f32) -> f32 {
	var avg = f32(0);
	for (var j=0; j<NLapNeigh; j++) {
		var xo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(0))];
		var yo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(1))];
		var zo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(2))];
		var nv = StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z + zo), u32(y + yo), u32(x + xo), u32(vidx), u32(tidx)));
		avg += NeighWts[Index2D(TensorStrides[20], TensorStrides[21], u32(LaplacianWts), u32(j))] * (nv - ctr);
	}return avg;
}
fn Gradient10(x: i32,y: i32,z: i32,vidx: i32,tidx: i32) -> vec3<f32> {
	var g: vec3<f32>;
	for (var xyz=0; xyz<3; xyz++) {
		var sum = f32(0);
		for (var j=0; j<NGradPair; j++) {
			var xp = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Plus1), u32(j), u32(0))];
			var xm = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Minus1), u32(j), u32(0))];
			var yp = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Plus1), u32(j), u32(1))];
			var ym = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Minus1), u32(j), u32(1))];
			var zp = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Plus1), u32(j), u32(2))];
			var zm = FaceOffs[Index4D(TensorStrides[10], TensorStrides[11], TensorStrides[12], TensorStrides[13], u32(xyz), u32(Minus1), u32(j), u32(2))];
			var grad = NeighWts[Index2D(TensorStrides[20], TensorStrides[21], u32(Grad10Wts), u32(j))] * (StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z + zp), u32(y + yp), u32(x + xp), u32(vidx), u32(tidx))) - StateGet(Index5D(TensorStrides[40], TensorStrides[41], TensorStrides[42], TensorStrides[43], TensorStrides[44], u32(z + zm), u32(y + ym), u32(x + xm), u32(vidx), u32(tidx))));
			sum += grad;
		}
		switch (xyz) {
		case 0: {
			g.x = sum;
		}
		case 1: {
			g.y = sum;
		}
		case 2: {
			g.z = sum;
		}
		default: {
		}
		}
	}return g;
}

//////// import: "klein-gordon.go"
alias CabStates = EMStates; //enums:enum -trim-prefix=Cab
const  CabAs: CabStates = 18;
const  CabBs: CabStates = 19;
const  CabAv: CabStates = 20;
const  CabBv: CabStates = 21;
const  CabV: CabStates = 22;
const  CabMag: CabStates = 23;

//////// import: "maxwell.go"
alias EMStates = i32; //enums:enum
const  A0s: EMStates = 0;
const  AXs: EMStates = 1;
const  AYs: EMStates = 2;
const  AZs: EMStates = 3;
const  A0v: EMStates = 4;
const  AXv: EMStates = 5;
const  AYv: EMStates = 6;
const  AZv: EMStates = 7;
const  EX: EMStates = 8;
const  EY: EMStates = 9;
const  EZ: EMStates = 10;
const  BX: EMStates = 11;
const  BY: EMStates = 12;
const  BZ: EMStates = 13;
const  Charge: EMStates = 14;
const  CurrentX: EMStates = 15;
const  CurrentY: EMStates = 16;
const  CurrentZ: EMStates = 17;

//////// import: "params.go"
alias Equations = i32; //enums:enum
const  Wave: Equations = 0;
const  WaveC: Equations = 1;
const  WaveCDir: Equations = 2;
const  KleinGordon: Equations = 3;
const  KleinGordonC: Equations = 4;
const  Schrodinger: Equations = 5;
const  Maxwell: Equations = 6;
const  Dirac: Equations = 7;
const  Weyl: Equations = 8;
const  Electroweak: Equations = 9;
const  Spinfield: Equations = 10;
const  ParticleMove: Equations = 11;
const  Pi       = 3.14159265358979323846264338327950288419716939937510582097494459;
const  TwoPi    = 2 * Pi;
const  InvTwoPi = 1.0 / TwoPi;
struct Parameters {
	ThreeD: i32,
	Edges: Edges,
	Energy: i32,
	C: f32,
	Hbar: f32,
	Mass: f32,
	VPotential: f32,
	SelfField: i32,
	EM: i32,
	A0NoWave: i32,
	E: f32,
	Mu0: f32,
	Move: i32,
	HiggsMu: f32,
	HiggsLambda: f32,
	Temp: f32,
	TempCrit: f32,
	ThermalC: f32,
	GW: f32,
	GpW: f32,
	YangMills: i32,
	Boris: i32,
	Diff: f32,
	Decay: f32,
	CSq: f32,
	Inv2CSq: f32,
	MOverHSq: f32,
	HSqOver2M: f32,
	HEOverMCSq: f32,
	Omega0: f32,
	HOverMC: f32,
	MOver2: f32,
	MCSq: f32,
	C6M2: f32,
	Eps0: f32,
	OneoEps0: f32,
	E2OverH: f32,
	EOverHSq: f32,
	SigmaF: f32,
	EsqOverMCSq: f32,
	HiggsMuSq: f32,
	HiggsV: f32,
	MW: f32,
	MZ: f32,
	SinThetaW: f32,
	CosThetaW: f32,
	WeylQ: f32,
	WaveDir: f32,
}

//////// import: "particle.go"
const NParticles = 4;
alias ParticleVars = i32; //enums:enum -trim-prefix=Particle
const  ParticleType: ParticleVars = 0;
const  ParticleMass: ParticleVars = 1;
const  ParticlePosX: ParticleVars = 2;
const  ParticlePosY: ParticleVars = 3;
const  ParticlePosZ: ParticleVars = 4;
const  ParticleVelX: ParticleVars = 5;
const  ParticleVelY: ParticleVars = 6;
const  ParticleVelZ: ParticleVars = 7;
const  ParticleLorentz: ParticleVars = 8;
const  ParticleESq: ParticleVars = 9;

//////// import: "schrodinger.go"

//////// import: "settings.go"
alias ViewModes = i32; //enums:enum
const  Plane: ViewModes = 0;
const  Bars: ViewModes = 1;
const  Vectors: ViewModes = 2;
alias CurPrev = i32; //enums:enum
const  Current: CurPrev = 0;
const  Previous: CurPrev = 1;
alias CurPrevBoth = i32; //enums:enum
const  CurOnly: CurPrevBoth = 0;
const  PrevOnly: CurPrevBoth = 1;
const  Both: CurPrevBoth = 2;
alias NPanels = i32; //enums:enum -trim-prefix=Panels
const  PanelsOne: NPanels = 0;
const  PanelsTwo: NPanels = 1;
const  PanelsFour: NPanels = 2;

//////// import: "slmath-math.go"
const SLPi = 3.141592653589793;

//////// import: "slmath-matrix3.go"

//////// import: "slmath-quaternion.go"

//////// import: "slmath-vector2.go"

//////// import: "slmath-vector3.go"
fn Length3(v: vec3<f32>) -> f32 {
	return sqrt(v.x*v.x + v.y*v.y + v.z*v.z);
}
fn LengthSquared3(v: vec3<f32>) -> f32 {
	return v.x*v.x + v.y*v.y + v.z*v.z;
}
fn Cross3(v: vec3<f32>,o: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(v.y*o.z-v.z*o.y, v.z*o.x-v.x*o.z, v.x*o.y-v.y*o.x);
}

//////// import: "spinfield.go"
alias SpinfieldStates = CabStates; //enums:enum -trim-prefix=Spinfield
const  SpinfieldParticle: SpinfieldStates = 24;
const  SpinfieldPvelX: SpinfieldStates = 25;
const  SpinfieldPvelY: SpinfieldStates = 26;
const  SpinfieldPvelZ: SpinfieldStates = 27;
const  SpinfieldPESq: SpinfieldStates = 28;
const  SpinfieldDist: SpinfieldStates = 29;
const  SpinfieldDrive: SpinfieldStates = 30;
const  SpinfieldHiggs0a: SpinfieldStates = 31;
const  SpinfieldHiggs0b: SpinfieldStates = 32;
const  SpinfieldHiggs1a: SpinfieldStates = 33;
const  SpinfieldHiggs1b: SpinfieldStates = 34;
const  Spinfield0a: SpinfieldStates = 35;
const  Spinfield0b: SpinfieldStates = 36;
const  SpinfieldXa: SpinfieldStates = 37;
const  SpinfieldXb: SpinfieldStates = 38;
const  SpinfieldYa: SpinfieldStates = 39;
const  SpinfieldYb: SpinfieldStates = 40;
const  SpinfieldZa: SpinfieldStates = 41;
const  SpinfieldZb: SpinfieldStates = 42;

//////// import: "wave.go"
alias WaveStates = i32; //enums:enum -trim-prefix=Wave
const  WavePos: WaveStates = 0;
const  WaveVel: WaveStates = 1;
const  WaveForce: WaveStates = 2;
const  WaveV: WaveStates = 3;
const  WaveKinetic: WaveStates = 4;
const  WavePotential: WaveStates = 5;
const  WaveEnergy: WaveStates = 6;
alias WaveCStates = i32; //enums:enum -trim-prefix=Wave
const  WaveCa: WaveCStates = 0;
const  WaveCb: WaveCStates = 1;
const  WaveCMag: WaveCStates = 2;

//////// import: "weyl.go"
alias WeylStates = EMStates; //enums:enum -trim-prefix=Weyl
const  WeylL1a: WeylStates = 18;
const  WeylL1b: WeylStates = 19;
const  WeylL2a: WeylStates = 20;
const  WeylL2b: WeylStates = 21;
const  WeylR1a: WeylStates = 22;
const  WeylR1b: WeylStates = 23;
const  WeylR2a: WeylStates = 24;
const  WeylR2b: WeylStates = 25;
const  WeylV: WeylStates = 26;
const  WeylLMag: WeylStates = 27;
const  WeylRMag: WeylStates = 28;

//////// import: "slrand.wgsl"
fn Philox2x32round(counter: su64, key: u32) -> su64 {
	let mul = Uint32Mul64(u32(0xD256D193), counter.x);
	var ctr: su64;
	ctr.x = mul.y ^ key ^ counter.y;
	ctr.y = mul.x;
	return ctr;
}
fn Philox2x32bumpkey(key: u32) -> u32 {
	return key + u32(0x9E3779B9);
}
fn Philox2x32(counter: su64, key: u32) -> vec2<u32> {
	var ctr = Philox2x32round(counter, key); // 1
	var ky = Philox2x32bumpkey(key);
	ctr = Philox2x32round(ctr, ky); // 2
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 3
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 4
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 5
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 6
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 7
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 8
	ky = Philox2x32bumpkey(ky);
	ctr = Philox2x32round(ctr, ky); // 9
	ky = Philox2x32bumpkey(ky);
	return Philox2x32round(ctr, ky); // 10
}
fn RandUint32Vec2(counter: su64, funcIndex: u32, key: u32) -> vec2<u32> {
	return Philox2x32(Uint64Add32(counter, funcIndex), key);
}
fn RandUint32(counter: su64, funcIndex: u32, key: u32) -> u32 {
	return Philox2x32(Uint64Add32(counter, funcIndex), key).x;
}
fn RandFloat32Vec2(counter: su64, funcIndex: u32, key: u32) -> vec2<f32> {
	return Uint32ToFloat32Vec2(RandUint32Vec2(counter, funcIndex, key));
}
fn RandFloat32(counter: su64, funcIndex: u32, key: u32) -> f32 { 
	return Uint32ToFloat32(RandUint32(counter, funcIndex, key));
}
fn RandFloat32Range11Vec2(counter: su64, funcIndex: u32, key: u32) -> vec2<f32> {
	return Uint32ToFloat32Vec2(RandUint32Vec2(counter, funcIndex, key));
}
fn RandFloat32Range11(counter: su64, funcIndex: u32, key: u32) -> f32 { 
	return Uint32ToFloat32Range11(RandUint32(counter, funcIndex, key));
}
fn RandBoolP(counter: su64, funcIndex: u32, key: u32, p: f32) -> bool { 
	return (RandFloat32(counter, funcIndex, key) < p);
}
fn sincospi(x: f32) -> vec2<f32> {
	let PIf = 3.1415926535897932;
	var r: vec2<f32>;
	r.x = cos(PIf*x);
	r.y = sin(PIf*x);
	return r;
}
fn RandFloat32NormVec2(counter: su64, funcIndex: u32, key: u32) -> vec2<f32> { 
	let ur = RandUint32Vec2(counter, funcIndex, key);
	var f = sincospi(Uint32ToFloat32Range11(ur.x));
	let r = sqrt(-2.0 * log(Uint32ToFloat32(ur.y))); // guaranteed to avoid 0.
	return f * r;
}
fn RandFloat32Norm(counter: su64, funcIndex: u32, key: u32) -> f32 { 
	return RandFloat32Vec2(counter, funcIndex, key).x;
}
fn RandUint32N(counter: su64, funcIndex: u32, key: u32, n: u32) -> u32 { 
	let v = RandFloat32(counter, funcIndex, key);
	return u32(v * f32(n));
}
struct RandCounter {
	Counter: su64,
	HiSeed: u32,
	pad: u32,
}
fn RandCounter_Reset(ct: ptr<function,RandCounter>) {
	(*ct).Counter.x = u32(0);
	(*ct).Counter.y = (*ct).HiSeed;
}
fn RandCounter_Seed(ct: ptr<function,RandCounter>, seed: u32) {
	(*ct).HiSeed = seed;
	RandCounter_Reset(ct);
}
fn RandCounter_Add(ct: ptr<function,RandCounter>, inc: u32) {
	(*ct).Counter = Uint64Add32((*ct).Counter, inc);
}

//////// import: "sltype.wgsl"
alias su64 = vec2<u32>;
fn Uint32Mul64(a: u32, b: u32) -> su64 {
	let LOMASK = (((u32(1))<<16)-1);
	var r: su64;
	r.x = a * b;               /* full low multiply */
	let ahi = a >> 16;
	let alo = a & LOMASK;
	let bhi = b >> 16;
	let blo = b & LOMASK;
	let ahbl = ahi * blo;
	let albh = alo * bhi;
	let ahbl_albh = ((ahbl&LOMASK) + (albh&LOMASK));
	var hit = ahi*bhi + (ahbl>>16) +  (albh>>16);
	hit += ahbl_albh >> 16; /* carry from the sum of lo(ahbl) + lo(albh) ) */
	/* carry from the sum with alo*blo */
	if ((r.x >> u32(16)) < (ahbl_albh&LOMASK)) {
		hit += u32(1);
	}
	r.y = hit; 
	return r;
}
/*
fn Uint32Mul64(a: u32, b: u32) -> su64 {
	return su64(a) * su64(b);
}
*/
fn Uint64Add32(a: su64, b: u32) -> su64 {
	if (b == 0) {
		return a;
	}
	var s = a;
	if (s.x > u32(0xffffffff) - b) {
		s.y++;
		s.x = (b - 1) - (u32(0xffffffff) - s.x);
	} else {
		s.x += b;
	}
	return s;
}
fn Uint64Incr(a: su64) -> su64 {
	var s = a;
	if(s.x == 0xffffffff) {
		s.y++;
		s.x = u32(0);
	} else {
		s.x++;
	}
	return s;
}
fn Uint32ToFloat32(val: u32) -> f32 {
	let factor = f32(1.0) / (f32(u32(0xffffffff)) + f32(1.0));
	let halffactor = f32(0.5) * factor;
	var f = f32(val) * factor + halffactor;
	if (f == 1.0) { // exclude 1
		return bitcast<f32>(0x3F7FFFFF);
	}
	return f;
}
fn Uint32ToFloat32Vec2(val: vec2<u32>) -> vec2<f32> {
	var r: vec2<f32>;
	r.x = Uint32ToFloat32(val.x);
	r.y = Uint32ToFloat32(val.y);
	return r;
}
fn Uint32ToFloat32Range11(val: u32) -> f32 {
	let factor = f32(1.0) / (f32(i32(0x7fffffff)) + f32(1.0));
	let halffactor = f32(0.5) * factor;
	return (f32(val) * factor + halffactor);
}
fn Uint32ToFloat32Range11Vec2(val: vec2<u32>) -> vec2<f32> {
	var r: vec2<f32>;
	r.x = Uint32ToFloat32Range11(val.x);
	r.y = Uint32ToFloat32Range11(val.y);
	return r;
}