// Code generated by "gosl"; DO NOT EDIT
// kernel: SchrodingerKernel

// // Params contains the full set of simulation parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> Params: array<Parameters>;
@group(0) @binding(2)
var<storage, read_write> NeighOffs: array<i32>;
@group(0) @binding(4)
var<storage, read_write> NeighWts: array<f32>;
// // Ctx has the Context state values. 
@group(1) @binding(0)
var<storage, read> Ctx: array<Context>;
@group(1) @binding(1)
var<storage, read_write> State0: array<f32>;
@group(1) @binding(2)
var<storage, read_write> State1: array<f32>;
@group(1) @binding(3)
var<storage, read_write> State2: array<f32>;
@group(1) @binding(4)
var<storage, read_write> State3: array<f32>;
@group(1) @binding(5)
var<storage, read_write> State4: array<f32>;
@group(1) @binding(6)
var<storage, read_write> State5: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	SchrodingerKernel(idx);
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}

fn StateGet(ix: u32) -> f32 {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		return State0[ix];
	}
	case u32(1): {
		return State1[ix - 536870904];
	}
	case u32(2): {
		return State2[ix - 1073741808];
	}
	case u32(3): {
		return State3[ix - 1610612712];
	}
	case u32(4): {
		return State4[ix - 2147483616];
	}
	default: {
		return State5[ix - 2684354520];
	}
	}
}

fn StateSet(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] = vl;
	}
	case u32(1): {
		State1[ix - 536870904] = vl;
	}
	case u32(2): {
		State2[ix - 1073741808] = vl;
	}
	case u32(3): {
		State3[ix - 1610612712] = vl;
	}
	case u32(4): {
		State4[ix - 2147483616] = vl;
	}
	default: {
		State5[ix - 2684354520] = vl;
	}
	}
}

fn StateSetAdd(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] += vl;
	}
	case u32(1): {
		State1[ix - 536870904] += vl;
	}
	case u32(2): {
		State2[ix - 1073741808] += vl;
	}
	case u32(3): {
		State3[ix - 1610612712] += vl;
	}
	case u32(4): {
		State4[ix - 2147483616] += vl;
	}
	default: {
		State5[ix - 2684354520] += vl;
	}
	}
}

fn StateSetSub(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] -= vl;
	}
	case u32(1): {
		State1[ix - 536870904] -= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] -= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] -= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] -= vl;
	}
	default: {
		State5[ix - 2684354520] -= vl;
	}
	}
}

fn StateSetMul(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] *= vl;
	}
	case u32(1): {
		State1[ix - 536870904] *= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] *= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] *= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] *= vl;
	}
	default: {
		State5[ix - 2684354520] *= vl;
	}
	}
}

fn StateSetDiv(vl: f32, ix: u32) {
	let ii = ix / 536870904;
	switch ii {
	case u32(0): {
		State0[ix] /= vl;
	}
	case u32(1): {
		State1[ix - 536870904] /= vl;
	}
	case u32(2): {
		State2[ix - 1073741808] /= vl;
	}
	case u32(3): {
		State3[ix - 1610612712] /= vl;
	}
	case u32(4): {
		State4[ix - 2147483616] /= vl;
	}
	default: {
		State5[ix - 2684354520] /= vl;
	}
	}
}

fn Index5D(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, i0: u32, i1: u32, i2: u32, i3: u32, i4: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3 + s4 * i4;
}


//////// import: "vars.go"

//////// import: "context.go"
struct Context {
	Size: vec4<i32>,
	NVars: i32,
	Step: i32,
	CurState: i32,
	pad: i32,
}
fn Context_StateCoords(ctx: Context, idx: u32, x: ptr<function,i32>,y: ptr<function,i32>,z: ptr<function,i32>) -> bool {
	var szxy = ctx.Size.x * ctx.Size.y;
	*z = i32(idx) / szxy;
	var rz = i32(idx) % szxy;
	var szx = ctx.Size.x;
	*y = rz / szx;
	*x = rz % szx;
	if (*z >= ctx.Size.z || *y >= ctx.Size.y || *x >= ctx.Size.x) {
		return false;
	}
	*z += i32(1);
	*y += i32(1);
	*x += i32(1);
return true;
}
fn Context_PrevState(ctx: Context) -> i32 {
	return 1 - ctx.CurState;
}

//////// import: "dirac.go"
alias DiracStates = EMStates; //enums:enum -trim-prefix=Dirac
const  DiracPos1A: DiracStates = 18;
const  DiracPos1B: DiracStates = 19;
const  DiracPos2A: DiracStates = 20;
const  DiracPos2B: DiracStates = 21;
const  DiracVel1A: DiracStates = 22;
const  DiracVel1B: DiracStates = 23;
const  DiracVel2A: DiracStates = 24;
const  DiracVel2B: DiracStates = 25;
const  DiracCC: DiracStates = 26;

//////// import: "edges.go"
alias Edges = i32; //enums:enum -trim-prefix=Edges
const  EdgesFixed: Edges = 0;
const  EdgesWrap: Edges = 1;
const  EdgesDamp: Edges = 2;

//////// import: "enumgen.go"
const DiracStatesN: DiracStates = 27;
const EdgesN: Edges = 3;
const MinusPlusOneN: MinusPlusOne = 2;
const NeighWeightsN: NeighWeights = 3;
const GPUVarsN: GPUVars = 6;
const CabStatesN: CabStates = 15;
const EMStatesN: EMStates = 18;
const EquationsN: Equations = 7;
const ParticleKGCStatesN: ParticleKGCStates = 30;
const ViewModesN: ViewModes = 2;
const CurPrevN: CurPrev = 2;
const CurPrevBothN: CurPrevBoth = 3;
const NPanelsN: NPanels = 3;
const WaveStatesN: WaveStates = 6;

//////// import: "funcs.go"
alias MinusPlusOne = i32; //enums:enum
const  Minus1: MinusPlusOne = 0;
const  Plus1: MinusPlusOne  = 1;
alias NeighWeights = i32; //enums:enum
const  LaplacianWts: NeighWeights = 0;
const  AverageWts: NeighWeights = 1;
const  Grad18Wts: NeighWeights = 2;
const  Average27Sum = f32(20.104084);
const  OneoAverage27Sum = 0.049741138;
fn Laplacian1D(x: i32,y: i32,z: i32,vidx: i32,tidx: i32, ctr: f32) -> f32 {
	var m1 = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x - 1), u32(vidx), u32(tidx)));
	var p1 = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34],
	u32(z), u32(y), u32(x + 1), u32(vidx), u32(tidx)));
return (m1 + p1) - 2*ctr;
}
fn Laplacian26(x: i32,y: i32,z: i32,vidx: i32,tidx: i32, ctr: f32) -> f32 {
	var avg = f32(0);
	for (var j=0; j<26; j++) {
		var xo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(0))];
		var yo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(1))];
		var zo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(2))];
		var nv = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z + zo), u32(y + yo), u32(x + xo), u32(vidx), u32(tidx)));
		avg += NeighWts[Index2D(TensorStrides[20], TensorStrides[21], u32(LaplacianWts), u32(j))] * (nv - ctr);
	}return avg;
}

//////// import: "klein-gordon.go"
alias CabStates = i32; //enums:enum -trim-prefix=Cab
const  CabPosA: CabStates = 0;
const  CabPosB: CabStates = 1;
const  CabVelA: CabStates = 2;
const  CabVelB: CabStates = 3;
const  CabForceA: CabStates = 4;
const  CabForceB: CabStates = 5;
const  CabV: CabStates = 6;
const  CabCC: CabStates = 7;
const  CabCharge: CabStates = 8;
const  CabCurrentX: CabStates = 9;
const  CabCurrentY: CabStates = 10;
const  CabCurrentZ: CabStates = 11;
const  CabKinetic: CabStates = 12;
const  CabPotential: CabStates = 13;
const  CabEnergy: CabStates = 14;

//////// import: "maxwell.go"
alias EMStates = i32; //enums:enum
const  A0Pos: EMStates = 0;
const  AXPos: EMStates = 1;
const  AYPos: EMStates = 2;
const  AZPos: EMStates = 3;
const  A0Vel: EMStates = 4;
const  AXVel: EMStates = 5;
const  AYVel: EMStates = 6;
const  AZVel: EMStates = 7;
const  EX: EMStates = 8;
const  EY: EMStates = 9;
const  EZ: EMStates = 10;
const  BX: EMStates = 11;
const  BY: EMStates = 12;
const  BZ: EMStates = 13;
const  Charge: EMStates = 14;
const  CurrentX: EMStates = 15;
const  CurrentY: EMStates = 16;
const  CurrentZ: EMStates = 17;

//////// import: "params.go"
alias Equations = i32; //enums:enum
const  Wave: Equations = 0;
const  KleinGordon: Equations = 1;
const  KleinGordonC: Equations = 2;
const  Schrodinger: Equations = 3;
const  Maxwell: Equations = 4;
const  Dirac: Equations = 5;
const  ParticleKGC: Equations = 6;
const  Pi       = 3.14159265358979323846264338327950288419716939937510582097494459;
const  TwoPi    = 2 * Pi;
const  InvTwoPi = 1.0 / TwoPi;
struct Parameters {
	ThreeD: i32,
	Energy: i32,
	C: f32,
	CSq: f32,
	Inv2CSq: f32,
	HBar: f32,
	Mass: f32,
	MassCOverHBarSq: f32,
	HBarSqOver2Mass: f32,
	MassOver2: f32,
	Mu0: f32,
	Eps0: f32,
	OneoEps0: f32,
	Wavelength: f32,
	PacketWidth: f32,
	Edges: Edges,
}

//////// import: "particle-kg.go"
alias ParticleKGCStates = CabStates; //enums:enum -trim-prefix=PKGC
const  PKGCMomX: ParticleKGCStates = 15;
const  PKGCMomY: ParticleKGCStates = 16;
const  PKGCMomZ: ParticleKGCStates = 17;
const  PKGCMomXP: ParticleKGCStates = 18;
const  PKGCMomXPv: ParticleKGCStates = 19;
const  PKGCMomXN: ParticleKGCStates = 20;
const  PKGCMomXNv: ParticleKGCStates = 21;
const  PKGCMomYP: ParticleKGCStates = 22;
const  PKGCMomYPv: ParticleKGCStates = 23;
const  PKGCMomYN: ParticleKGCStates = 24;
const  PKGCMomYNv: ParticleKGCStates = 25;
const  PKGCMomZP: ParticleKGCStates = 26;
const  PKGCMomZPv: ParticleKGCStates = 27;
const  PKGCMomZN: ParticleKGCStates = 28;
const  PKGCMomZNv: ParticleKGCStates = 29;

//////// import: "schrodinger.go"
fn SchrodingerKernel(i: u32) { //gosl:kernel
	let ctx = Ctx[0];
	var x: i32;
	var y: i32;
	var z: i32;
	var ok = Context_StateCoords(ctx, i, &x, &y, &z);
	if (!ok) {
		return;
	}
	var cur = ctx.CurState;
	var prv = Context_PrevState(ctx);
	var pposA = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabPosA), u32(prv)));
	var pposB = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabPosB), u32(prv)));
	var pvelA = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabVelA), u32(prv)));
	var pvelB = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabVelB), u32(prv)));
	var vpot = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32],
	TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabV), u32(prv)));
	var forceA: f32;
	var velA: f32;
	var posA: f32;
	var forceB: f32;
	var velB: f32;
	var posB: f32;
	if (cur == 0) {
		if (Params[0].ThreeD == 1) {
			forceA = Laplacian26(x, y, z, i32(CabPosB), prv, pposB); // A driven by B
		} else {
			forceA = Laplacian1D(x, y, z, i32(CabPosB), prv, pposB); // A driven by B
		}
		forceA *= -Params[0].HBarSqOver2Mass + vpot*pposB; // note neg here, not in B
		velA = forceA;                                     // first order, not +=
		posA = pposA + velA;
		forceB = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabForceB), u32(prv)));
		velB = pvelB;
		posB = pposB;
	} else {
		if (Params[0].ThreeD == 1) {
			forceB = Laplacian26(x, y, z, i32(CabPosA), prv, pposA); // B driven by A
		} else {
			forceB = Laplacian1D(x, y, z, i32(CabPosA), prv, pposA); // B driven by A
		}
		forceB *= Params[0].HBarSqOver2Mass + vpot*pposA; // todo: not sure about this!!
		velB = forceB;                                    // first order, not +=
		posB = pposB + velB;
		forceA = StateGet(Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabForceA), u32(prv)));
		velA = pvelA;
		posA = pposA;
	}
	if (Params[0].Energy == 1) {
		var cc = posA*posA + posB*posB;
		var midVel = 0.25 * (pvelA + velA + pvelB + velB);
		var kinetic = Params[0].MassOver2 * midVel * midVel;
		StateSet(cc, Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabCC), u32(cur)));
		StateSet(kinetic, Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabKinetic), u32(cur)));
		StateSet(kinetic + vpot, Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabEnergy), u32(cur)));
	}
	StateSet(forceA, Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabForceA), u32(cur)));
	StateSet(velA, Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabVelA), u32(cur)));
	StateSet(posA, Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabPosA), u32(cur)));
	StateSet(forceB, Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabForceB), u32(cur)));
	StateSet(velB, Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabVelB), u32(cur)));
	StateSet(posB, Index5D(TensorStrides[30], TensorStrides[31], TensorStrides[32], TensorStrides[33], TensorStrides[34], u32(z), u32(y), u32(x), u32(CabPosB), u32(cur)));
}

//////// import: "settings.go"
alias ViewModes = i32; //enums:enum
const  Plane: ViewModes = 0;
const  Bars: ViewModes = 1;
alias CurPrev = i32; //enums:enum
const  Current: CurPrev = 0;
const  Previous: CurPrev = 1;
alias CurPrevBoth = i32; //enums:enum
const  CurOnly: CurPrevBoth = 0;
const  PrevOnly: CurPrevBoth = 1;
const  Both: CurPrevBoth = 2;
alias NPanels = i32; //enums:enum -trim-prefix=Panels
const  PanelsOne: NPanels = 0;
const  PanelsTwo: NPanels = 1;
const  PanelsFour: NPanels = 2;

//////// import: "wave.go"
alias WaveStates = i32; //enums:enum -trim-prefix=Wave
const  WavePos: WaveStates = 0;
const  WaveVel: WaveStates = 1;
const  WaveForce: WaveStates = 2;
const  WaveKinetic: WaveStates = 3;
const  WavePotential: WaveStates = 4;
const  WaveEnergy: WaveStates = 5;