// Code generated by "gosl"; DO NOT EDIT
// kernel: Wave3DKernel

// // Params contains the full set of simulation parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> Params: array<Parameters>;
@group(0) @binding(2)
var<storage, read_write> NeighOffs: array<i32>;
@group(0) @binding(3)
var<storage, read_write> LaplacianWts: array<f32>;
// // Ctx has the Context state values. 
@group(1) @binding(0)
var<storage, read_write> Ctx: array<Context>;
@group(1) @binding(1)
var<storage, read_write> State: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	Wave3DKernel(idx);
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}

fn Index1D(s0: u32, i0: u32) -> u32 {
	return s0 * i0;
}

fn Index5D(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, i0: u32, i1: u32, i2: u32, i3: u32, i4: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3 + s4 * i4;
}


//////// import: "vars.go"

//////// import: "context.go"
struct Context {
	Size: vec4<i32>,
	Step: i32,
	CurState: i32,
	pad: i32,
	pad1: i32,
}
fn Context_StateCoords(ctx: Context, idx: u32, x: ptr<function,i32>,y: ptr<function,i32>,z: ptr<function,i32>) -> bool {
	var szxy = ctx.Size.x * ctx.Size.y;
	*z = i32(idx) / szxy;
	var rz = i32(idx) % szxy;
	var szx = ctx.Size.x;
	*y = rz / szx;
	*x = rz % szx;
	if (*z >= ctx.Size.z || *y >= ctx.Size.y || *x >= ctx.Size.x) {
		return false;
	}
	*z += i32(1);
	*y += i32(1);
	*x += i32(1);
return true;
}
fn Context_PrevState(ctx: Context) -> i32 {
	return 1 - ctx.CurState;
}

//////// import: "enumgen.go"
const GPUVarsN: GPUVars = 5;
const EquationsN: Equations = 2;
const EdgesN: Edges = 2;
const ViewModesN: ViewModes = 2;
const WaveStatesN: WaveStates = 6;

//////// import: "funcs.go"
fn Laplacian26(xx: i32,yy: i32,zz: i32,vidx: i32,tidx: i32, ctr: f32) -> f32 {
	var avg = f32(0);
	for (var j=0; j<26; j++) {
		var xo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(0))];
		var yo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(1))];
		var zo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(2))];
		var nv = State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(zz + zo), u32(yy + yo), u32(xx + xo), u32(vidx), u32(tidx))];
		avg += LaplacianWts[Index1D(TensorStrides[10], u32(j))] * (nv - ctr);
	}return avg;
}
fn PotentialEnergy26(x: i32,y: i32,z: i32,vidx: i32,tidx: i32, ctr: f32) -> f32 {
	var avg = f32(0);
	for (var j=0; j<26; j++) {
		var xo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(0))];
		var yo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(1))];
		var zo = NeighOffs[Index2D(TensorStrides[0], TensorStrides[1], u32(j), u32(2))];
		var nv = State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z + zo), u32(y + yo), u32(x + xo), u32(vidx), u32(tidx))];
		var dv = (nv - ctr);
		avg += LaplacianWts[Index1D(TensorStrides[10], u32(j))] * dv * dv;
	}return avg;
}

//////// import: "params.go"
alias Equations = i32; //enums:enum
const  Wave1D: Equations = 0;
const  Wave3D: Equations = 1;
alias Edges = i32; //enums:enum
const  EdgesFixed: Edges = 0;
const  EdgesWrap: Edges = 1;
struct Parameters {
	Edges: Edges,
	DoEnergy: i32,
	pad: i32,
	pad1: i32,
	Units: Units,
}
struct Display {
	On: bool,
	Interval: i32,
}
struct Units {
	C: f32,
	CSq: f32,
	Inv2CSq: f32,
	pad: f32,
}

//////// import: "view.go"
alias ViewModes = i32; //enums:enum
const  Plane: ViewModes = 0;
const  Bars: ViewModes = 1;

//////// import: "wave.go"
alias WaveStates = i32; //enums:enum -trim-prefix=Wave
const  WavePos: WaveStates = 0;
const  WaveVel: WaveStates = 1;
const  WaveForce: WaveStates = 2;
const  WaveKinetic: WaveStates = 3;
const  WavePotential: WaveStates = 4;
const  WaveEnergy: WaveStates = 5;
fn Wave3DKernel(i: u32) { //gosl:kernel
var ctx = Ctx[0];; var x: i32;
var y: i32;
var z: i32;; var ok = Context_StateCoords(ctx, i, &x, &y, &z);
; if (!ok) {
	return;
}; var cur = ctx.CurState;
; var prv = Context_PrevState(ctx);
; var ppos = State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WavePos), u32(prv))];
; var pvel = State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveVel), u32(prv))];
; var force = Laplacian26(x, y, z, i32(WavePos), prv, ppos);
; var vel = pvel + Params[0].Units.CSq*force;
; var pos = ppos + vel;
; if (Params[0].DoEnergy == 1) {
	var midVel = 0.5 * (pvel + vel);
	var kinetic = Params[0].Units.Inv2CSq * midVel * midVel;
	var potential = PotentialEnergy26(x, y, z, i32(WavePos), prv, ppos);
	State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveKinetic), u32(cur))] = kinetic;
	State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WavePotential), u32(cur))] = potential;
	State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveEnergy), u32(cur))] = kinetic + potential;
}; State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveForce), u32(cur))] = force;; State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveVel), u32(cur))] = vel;; State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WavePos), u32(cur))] = pos; }