// Code generated by "gosl"; DO NOT EDIT
// kernel: Wave1DKernel

// // Params contains the full set of simulation parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> Params: array<Parameters>;
// // Ctx has the Context state values. 
@group(1) @binding(0)
var<storage, read> Ctx: array<Context>;
@group(1) @binding(1)
var<storage, read_write> State: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	Wave1DKernel(idx);
}

fn Index5D(s0: u32, s1: u32, s2: u32, s3: u32, s4: u32, i0: u32, i1: u32, i2: u32, i3: u32, i4: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2 + s3 * i3 + s4 * i4;
}


//////// import: "vars.go"

//////// import: "context.go"
struct Context {
	Size: vec4<i32>,
	Step: i32,
	CurState: i32,
	pad: i32,
	pad1: i32,
}
fn Context_StateCoords(ctx: Context, idx: u32, x: ptr<function,i32>,y: ptr<function,i32>,z: ptr<function,i32>) -> bool {
	var szxy = ctx.Size.x * ctx.Size.y;
	*z = i32(idx) / szxy;
	var rz = i32(idx) % szxy;
	var szx = ctx.Size.x;
	*y = rz / szx;
	*x = rz % szx;
	if (*z >= ctx.Size.z || *y >= ctx.Size.y || *x >= ctx.Size.x) {
		return false;
	}
	*z += i32(1);
	*y += i32(1);
	*x += i32(1);
return true;
}
fn Context_PrevState(ctx: Context) -> i32 {
	return 1 - ctx.CurState;
}

//////// import: "enumgen.go"
const GPUVarsN: GPUVars = 5;
const EquationsN: Equations = 3;
const EdgesN: Edges = 2;
const ViewModesN: ViewModes = 2;
const CurPrevN: CurPrev = 2;
const NPanelsN: NPanels = 3;
const WaveStatesN: WaveStates = 6;

//////// import: "funcs.go"

//////// import: "klein-gordon.go"

//////// import: "params.go"
alias Equations = i32; //enums:enum
const  Wave1D: Equations = 0;
const  Wave3D: Equations = 1;
const  KleinGordon: Equations = 2;
alias Edges = i32; //enums:enum
const  EdgesFixed: Edges = 0;
const  EdgesWrap: Edges = 1;
const  Pi       = 3.14159265358979323846264338327950288419716939937510582097494459;
const  TwoPi    = 2 * Pi;
const  InvTwoPi = 1.0 / TwoPi;
struct Parameters {
	Edges: Edges,
	DoEnergy: i32,
	C: f32,
	CSq: f32,
	Inv2CSq: f32,
	HBar: f32,
	Mass: f32,
	MassCOverHBarSq: f32,
}

//////// import: "settings.go"
alias ViewModes = i32; //enums:enum
const  Plane: ViewModes = 0;
const  Bars: ViewModes = 1;
alias CurPrev = i32; //enums:enum
const  Current: CurPrev = 0;
const  Previous: CurPrev = 1;
alias NPanels = i32; //enums:enum -trim-prefix=Panels
const  PanelsOne: NPanels = 0;
const  PanelsTwo: NPanels = 1;
const  PanelsFour: NPanels = 2;

//////// import: "wave.go"
alias WaveStates = i32; //enums:enum -trim-prefix=Wave
const  WavePos: WaveStates = 0;
const  WaveVel: WaveStates = 1;
const  WaveForce: WaveStates = 2;
const  WaveKinetic: WaveStates = 3;
const  WavePotential: WaveStates = 4;
const  WaveEnergy: WaveStates = 5;
fn Wave1DKernel(i: u32) { //gosl:kernel
let ctx = Ctx[0];; var x: i32;
var y: i32;
var z: i32;; var ok = Context_StateCoords(ctx, i, &x, &y, &z);
; if (!ok) {
	return;
}; var cur = ctx.CurState;
; var prv = Context_PrevState(ctx);
; var ppos = State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WavePos), u32(prv))];
; var pvel = State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveVel), u32(prv))];
; var posm1 = State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x - 1), u32(WavePos), u32(prv))];
; var posp1 = State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x + 1), u32(WavePos), u32(prv))];
; var force = (posm1 + posp1) - 2*ppos;
; var vel = pvel + Params[0].CSq*force;
; var pos = ppos + vel;
; if (Params[0].DoEnergy == 1) {
	var midVel = 0.5 * (pvel + vel);
	var kinetic = Params[0].Inv2CSq * midVel * midVel;
	var pm1d = posm1 - ppos;
	var pp1d = posp1 - ppos;
	var potential = 0.5 * (pm1d*pm1d + pp1d*pp1d);
	State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveKinetic), u32(cur))] = kinetic;
	State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WavePotential), u32(cur))] = potential;
	State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveEnergy), u32(cur))] = kinetic + potential;
}; State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveForce), u32(cur))] = force;; State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WaveVel), u32(cur))] = vel;; State[Index5D(TensorStrides[20], TensorStrides[21], TensorStrides[22], TensorStrides[23], TensorStrides[24], u32(z), u32(y), u32(x), u32(WavePos), u32(cur))] = pos; }