// Code generated by "goal build"; DO NOT EDIT.
//line dirac.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

//gosl:start

// DiracKernel is the kernel for computing the Dirac equations,
// on scalar state values (WaveStates).
func DiracKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	ppos := State.Value(int(z), int(y), int(x), int(WavePos), int(prv))
	pvel := State.Value(int(z), int(y), int(x), int(WaveVel), int(prv))
	var force float32
	if Params[0].ThreeD.IsTrue() {
		force = Laplacian26(x, y, z, int32(WavePos), prv, ppos)
	} else {
		force = Laplacian1D(x, y, z, int32(WavePos), prv, ppos)
	}
	force -= Params[0].MassCOverHBarSq * ppos // this is the only diff from standard Wave
	vel := pvel + Params[0].CSq*force
	pos := ppos + vel

	if Params[0].Energy.IsTrue() {
		midVel := 0.5 * (pvel + vel)
		kinetic := Params[0].Inv2CSq * midVel * midVel
		var potential float32
		if Params[0].ThreeD.IsTrue() {
			potential = PotentialEnergy26(x, y, z, int32(WavePos), prv, ppos)
		} else {
			potential = PotentialEnergy1D(x, y, z, int32(WavePos), prv, ppos)
		}

		State.Set(kinetic, int(z), int(y), int(x), int(WaveKinetic), int(cur))
		State.Set(potential, int(z), int(y), int(x), int(WavePotential), int(cur))
		State.Set(kinetic+potential, int(z), int(y), int(x), int(WaveEnergy), int(cur))
	}
	State.Set(force, int(z), int(y), int(x), int(WaveForce), int(cur))
	State.Set(vel, int(z), int(y), int(x), int(WaveVel), int(cur))
	State.Set(pos, int(z), int(y), int(x), int(WavePos), int(cur))
}

//gosl:end

func (ss *Sim) DiracConfig() {
	ParamsShouldDisplay = DiracShouldDisplay
	ss.StateVars = WaveStatesN
	ss.ViewInit(func(view *View) {
		view.SetVar(WavePos, -1)
	})
}

// DiracShouldDisplay determines which Parameters fields to display.
var DiracShouldDisplay = []string{"Edges", "Energy", "C", "HBar", "Mass", "Wavelength", "PacketWidth"}
