// Code generated by "goal build"; DO NOT EDIT.
//line edges.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import (
	"cogentcore.org/core/math32"
)

// see fig_cube_sides_edges_labeled.svg for graphical version
//
//   |  /
// Y | / Z
//   |/
//   +-----
//     X
//
//       1 +----45----+
//   Z   / |      4XY/|
//     05  | 5XZ    / |
//    /   04      35  34
// 0 +-----15---+/ 3  |
// 1 | 0   +--24|-----+
//   |YZ / 1XY  | YZ/
// Y 01 02     13 23
//   |/     2XZ |/
// 0 +----12----+
//   0     X    1
//
// edges: rule is that can't have n,n,0,0 or m,m,1,1 in same edge
// 01[x0,z1] 02[x1,y0] 04[x1,zn] 05[ym,x0] 12[y1,z0] 13[xm,z0]
// 15[yn,z1] 23[xn,y1] 24[y0,zm] 34[xm,zn] 35[xm,yn] 45[ym,zn]

// convert to starting coords: 0 = m, 1 = n
// 01[x0,z1] 02[x1,y0] 04[x1,z1] 05[y0,x0] 12[y1,z0] 13[x0,z0]
// 15[y1,z1] 23[x1,y1] 24[y0,z0] 34[x0,z1] 35[x0,y1] 45[y0,z1]

// 0=Y[0-m],Z[1-n] 1=X[0-m],Y[1-n] 2=X[1-n],Z[0-m]
// 3=Y[1-n],Z[0-m] 4=X[1-n],Y[0-m] 5=X[0-m],Z[1-n]
// 6 = 8 corners

//gosl:start

// Edges determines how to handle the edges.
type Edges int32 //enums:enum -trim-prefix=Edges

const (
	// EdgesFixed keeps the edge values fixed at initial values
	EdgesFixed Edges = iota

	// EdgesWrap copies edge values from other side, effectively wrapping
	// the space around on itself like a torus.
	EdgesWrap

	// EdgesDamp implements damping of edge values.
	EdgesDamp
)

// EdgesN returns the number of points along the edges (and corners).
func (ctx *Context) EdgesN() int32 {
	p := ctx.SizePlus1()
	return 2 + 2*(p.Y*p.Z+p.X*p.Y+p.X*p.Z)
}

// EdgeCoords returns the x,y,z coordinates for given index into
// the edge state, using non-shared edge patterns per above.
// returns the face / corner number we're at (0-6) or -1 for none
func (ctx *Context) EdgeCoords(idx uint32, x, y, z *int32) int32 {
	i := int32(idx)
	p := ctx.SizePlus1()
	xy := p.X * p.Y
	yz := p.Y * p.Z
	xz := p.X * p.Z

	if i < 2 { // 6 corner
		if i == 0 {
			*x = 0
			*y = 0
			*z = 0
			return 6
		}
		*x = p.X
		*y = p.Y
		*z = p.Z
		return 6
	}
	i -= 2
	if i < yz { // 0
		*y = i / p.Z
		*z = 1 + i%p.Z
		*x = 0
		if *y == 0 && *z == p.Z {
			return 6
		}
		return 0
	}
	i -= yz
	if i < xy { // 1
		*x = i / p.Y
		*y = 1 + i%p.Y
		*z = 0
		if *x == 0 && *y == p.Y {
			return 6
		}
		return 1
	}
	i -= xy
	if i < xz { // 2
		*x = 1 + i/p.Z
		*z = i % p.Z
		*y = 0
		if *x == p.X && *z == 0 {
			return 6
		}
		return 2
	}
	i -= xz
	if i < yz { // 3
		*y = 1 + i/p.Z
		*z = i % p.Z
		*x = p.X
		if *y == p.Y && *z == 0 {
			return 6
		}
		return 3
	}
	i -= yz
	if i < xy { // 4
		*x = 1 + i/p.Y
		*y = i % p.Y
		*z = p.Z
		if *x == p.X && *y == 0 {
			return 6
		}
		return 4
	}
	i -= xy
	if i < xz { // 2
		*x = i / p.Z
		*z = 1 + i%p.Z
		*y = p.Y
		if *x == 0 && *z == p.Z {
			return 6
		}
		return 5
	}
	return -1
}

// EdgeCoordsWrap returns the x,y,z coordinates for given index into
// the edge state, using non-shared edge patterns per above,
// and also the source state for wrapping the value around as in a torus.
// returns the face / corner number we're at (0-6) or -1 for none
func (ctx *Context) EdgeCoordsWrap(idx uint32, x, y, z, xs, ys, zs *int32) int32 {
	i := int32(idx)
	s := ctx.Size.V()
	p := s.Add(math32.Vec3i(1, 1, 1))
	xy := p.X * p.Y
	yz := p.Y * p.Z
	xz := p.X * p.Z

	if i < 2 { // 6 corner
		if i == 0 {
			*x = 0
			*y = 0
			*z = 0
			*xs = s.X
			*ys = s.Y
			*zs = s.Z
			return 6
		}
		*x = p.X
		*y = p.Y
		*z = p.Z
		*xs = 1
		*ys = 1
		*zs = 1
		return 6
	}
	i -= 2
	if i < yz { // 0
		*y = i / p.Z
		*z = 1 + i%p.Z
		*x = 0
		*xs = s.X
		if *y == 0 && *z == p.Z {
			*ys = s.Y
			*zs = 1
			return 6
		}
		*ys = *y
		if *ys == 0 {
			*ys = s.Y
		}
		*zs = *z
		if *zs == p.Z {
			*zs = 1
		}
		return 0
	}
	i -= yz
	if i < xy { // 1
		*x = i / p.Y
		*y = 1 + i%p.Y
		*z = 0
		*zs = s.Z
		if *x == 0 && *y == p.Y {
			*xs = s.X
			*ys = 1
			return 6
		}
		*xs = *x
		if *xs == 0 {
			*xs = s.X
		}
		*ys = *y
		if *ys == p.Y {
			*ys = 1
		}
		return 1
	}
	i -= xy
	if i < xz { // 2
		*x = 1 + i/p.Z
		*z = i % p.Z
		*y = 0
		*ys = s.Y
		if *x == p.X && *z == 0 {
			*xs = 1
			*zs = s.Z
			return 6
		}
		*xs = *x
		if *xs == p.X {
			*xs = 1
		}
		*zs = *z
		if *zs == 0 {
			*zs = s.Z
		}
		return 2
	}
	i -= xz
	if i < yz { // 3
		*y = 1 + i/p.Z
		*z = i % p.Z
		*x = p.X
		*xs = 1
		if *y == p.Y && *z == 0 {
			*ys = 1
			*zs = s.Z
			return 6
		}
		*ys = *y
		if *ys == p.Y {
			*ys = 1
		}
		*zs = *z
		if *zs == 0 {
			*zs = s.Z
		}
		return 3
	}
	i -= yz
	if i < xy { // 4
		*x = 1 + i/p.Y
		*y = i % p.Y
		*z = p.Z
		*zs = 1
		if *x == p.X && *y == 0 {
			*xs = 1
			*ys = s.Y
			return 6
		}
		*xs = *x
		if *xs == p.X {
			*xs = 1
		}
		*ys = *y
		if *ys == 0 {
			*ys = s.Y
		}
		return 4
	}
	i -= xy
	if i < xz { // 2
		*x = i / p.Z
		*z = 1 + i%p.Z
		*y = p.Y
		*ys = 1
		if *x == 0 && *z == p.Z {
			*xs = s.X
			*zs = 1
			return 6
		}
		*xs = *x
		if *xs == 0 {
			*xs = s.X
		}
		*zs = *z
		if *zs == p.Z {
			*zs = 1
		}
		return 5
	}
	return -1
}

// EdgesWrapKernel is the kernel for wrapping edge values
func EdgesWrapKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z, sx, sy, sz int32
	face := ctx.EdgeCoordsWrap(i, &x, &y, &z, &sx, &sy, &sz)
	if face < 0 {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	nvars := ctx.NVars
	for vi := range nvars {
		State.Set(State.Value(int(sz), int(sy), int(sx), int(vi), int(cur)), int(z), int(y), int(x), int(vi), int(cur))
		State.Set(State.Value(int(sz), int(sy), int(sx), int(vi), int(prv)), int(z), int(y), int(x), int(vi), int(prv))
	}
}

//gosl:end
