// Code generated by "goal build"; DO NOT EDIT.
//line electroweak.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

//gosl:start
//gosl:import "cogentcore.org/lab/gosl/slmath"

// EWStates are the state variables for the Electroweak Model.
type EWStates EMStates //enums:enum -trim-prefix=EW

const (
	// EWHsCa is the Higgs doublet charged state Ca (real)
	EWHsCa EWStates = EWStates(EMStatesN) + iota

	// EWHsCb is the Higgs doublet charged state Cb (imaginary)
	EWHsCb

	// EWHs0a is the Higgs doublet neutral state 0a (real)
	EWHs0a

	// EWHs0b is the Higgs doublet neutral state 0b (imaginary)
	EWHs0b

	// EWHvCa is the Higgs doublet charged vel 0a (real)
	EWHvCa

	// EWHvCb is the Higgs doublet charged vel 0b (imaginary)
	EWHvCb

	// EWHv0a is the Higgs doublet neutral vel 0a (real)
	EWHv0a

	// EWHv0b is the Higgs doublet neutral vel 0b (imaginary)
	EWHv0b

	// EWHmag is the Higgs magnitude (h.c. * state = squared magnitude)
	EWHmag

	// EWV is the Higgs potential as a function of Hmag
	EWHV

	// EWB0s is the B weak hypercharge scalar potential 0 component.
	EWB0s

	// EWBXs is the B weak hypercharge vector potential X component.
	EWBXs

	// EWBYs is the B weak hypercharge vector potential Y component.
	EWBYs

	// EWBZs is the B weak hypercharge vector potential Z component.
	EWBZs

	// EWB0v is the B weak hypercharge scalar potential 0 velocity.
	EWB0v

	// EWBXv is the B weak hypercharge vector potential X velocity.
	EWBXv

	// EWBYv is the B weak hypercharge vector potential Y velocity.
	EWBYv

	// EWBZv is the B weak hypercharge vector potential Z velocity.
	EWBZv

	// EWW10s is the W weak isospin 1 scalar potential 0 component.
	EWW10s

	// EWW1Xs is the W weak isospin 1 vector potential X component.
	EWW1Xs

	// EWW1Ys is the W weak isospin 1 vector potential Y component.
	EWW1Ys

	// EWW1Zs is the W weak isospin 1 vector potential Z component.
	EWW1Zs

	// EWW10v is the W weak isospin 1 scalar potential 0 velocity.
	EWW10v

	// EWW1Xv is the W weak isospin 1 vector potential X velocity.
	EWW1Xv

	// EWW1Yv is the W weak isospin 1 vector potential Y velocity.
	EWW1Yv

	// EWW1Zv is the W weak isospin 1 vector potential Z velocity.
	EWW1Zv

	// EWW20s is the W weak isospin 2 scalar potential 0 component.
	EWW20s

	// EWW2Xs is the W weak isospin 2 vector potential X component.
	EWW2Xs

	// EWW2Ys is the W weak isospin 2 vector potential Y component.
	EWW2Ys

	// EWW2Zs is the W weak isospin 2 vector potential Z component.
	EWW2Zs

	// EWW20v is the W weak isospin 2 scalar potential 0 velocity.
	EWW20v

	// EWW2Xv is the W weak isospin 2 vector potential X velocity.
	EWW2Xv

	// EWW2Yv is the W weak isospin 2 vector potential Y velocity.
	EWW2Yv

	// EWW2Zv is the W weak isospin 2 vector potential Z velocity.
	EWW2Zv

	// EWW30s is the W weak isospin 3 scalar potential 0 component.
	EWW30s

	// EWW3Xs is the W weak isospin 3 vector potential X component.
	EWW3Xs

	// EWW3Ys is the W weak isospin 3 vector potential Y component.
	EWW3Ys

	// EWW3Zs is the W weak isospin 3 vector potential Z component.
	EWW3Zs

	// EWW30v is the W weak isospin 3 scalar potential 0 velocity.
	EWW30v

	// EWW3Xv is the W weak isospin 3 vector potential X velocity.
	EWW3Xv

	// EWW3Yv is the W weak isospin 3 vector potential Y velocity.
	EWW3Yv

	// EWW3Zv is the W weak isospin 3 vector potential Z velocity.
	EWW3Zv
)

// ElectroweakKernel is the kernel for computing Electroweak model.
// Only supports 3D.
//
// The Higgs doublet is carried as four real fields:
//
//	Phi = (1/sqrt2) * ( hsCa + i hsCb , hs0a + i hs0b )^T
//
// so that mag = hsCa^2 + hsCb^2 + hs0a^2 + hs0b^2 = 2 Phi^dag Phi, and the
// vacuum <Phi> = (0, v/sqrt2)^T corresponds to hs0a = v with the other three
// zero. The VEV must sit in the NEUTRAL (lower) component: that is what makes
// the unbroken generator Q = T^3 + Y annihilate the vacuum, and hence what
// leaves the photon massless.
//
// All quantities are in inverse cube units (1/cube), which is what makes
// lambda (and later g, g') dimensionless Standard Model values needing no
// conversion. See Units.Update.
func ElectroweakKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	// sz := ctx.Size.V()
	cur := ctx.CurState
	prv := ctx.PrevState()
	csq := Params[0].CSq
	// e2h := Params[0].E2OverH
	// e := Params[0].E
	// c := Params[0].C
	// ehsq := Params[0].EOverHSq
	// em := Params[0].EM.IsTrue()
	musq := Params[0].HiggsMuSq
	lambda := Params[0].HiggsLambda

	// a0 := State[z, y, x, A0s, prv]
	// aX := State[z, y, x, AXs, prv]
	// aY := State[z, y, x, AYs, prv]
	// aZ := State[z, y, x, AZs, prv]

	// aV := math32.Vec3(aX, aY, aZ)
	// a0sq := a0 * a0
	// aVsq := slmath.LengthSquared3(aV)
	// aSqD := ehsq * (a0sq - aVsq)

	hsCa := State.Value(int(z), int(y), int(x), int(EWHsCa), int(prv))
	hsCb := State.Value(int(z), int(y), int(x), int(EWHsCb), int(prv))
	hs0a := State.Value(int(z), int(y), int(x), int(EWHs0a), int(prv))
	hs0b := State.Value(int(z), int(y), int(x), int(EWHs0b), int(prv))

	hvCa := State.Value(int(z), int(y), int(x), int(EWHvCa), int(prv))
	hvCb := State.Value(int(z), int(y), int(x), int(EWHvCb), int(prv))
	hv0a := State.Value(int(z), int(y), int(x), int(EWHv0a), int(prv))
	hv0b := State.Value(int(z), int(y), int(x), int(EWHv0b), int(prv))

	// hsCaG := Gradient18(x, y, z, int32(hsCa), prv)
	// hsCbG := Gradient18(x, y, z, int32(hsCb), prv)

	// mag = 2 Phi^dag Phi: the SQUARED RADIUS in the 4D field space. The
	// potential depends on this and nothing else, which is exactly why it is
	// a Mexican hat rather than four independent wells.
	mag := hsCa*hsCa + hsCb*hsCb + hs0a*hs0a + hs0b*hs0b

	// V = -(1/2) mu^2 mag + (1/4) lambda mag^2
	// force_i = -dV/dphi_i = (mu^2 - lambda*mag) * phi_i
	//
	// The SAME radial factor multiplies EACH component. That is what makes the
	// force point along the field vector and depend only on |Phi|, leaving the
	// phase directions exactly flat -- the Goldstone modes. Applying a single
	// shared additive term instead would break the symmetry and destroy the
	// mechanism. At the VEV, mag = mu^2/lambda so vfac = 0 and the vacuum is
	// exactly stationary.
	vfac := musq - lambda*mag

	hfCa := Laplacian26(x, y, z, int32(EWHsCa), prv, hsCa) // force
	hfCa += vfac * hsCa
	hfCa *= csq
	//	if em {
	//		vd := hsCbG.Mul(aV)
	//		hsCaF += e2h*(a0*hv0b+c*(vd.X+vd.Y+vd.Z)) + hsCa*aSqD
	//	}
	hvCaN := hvCa + hfCa
	hsCaN := hsCa + hvCaN

	hfCb := Laplacian26(x, y, z, int32(EWHsCb), prv, hsCb)
	hfCb += vfac * hsCb
	hfCb *= csq
	//	if em {
	//		vd := hsCaG.Mul(aV)
	//		hsCbF += e2h*(a0*hv0aC+c*(vd.X+vd.Y+vd.Z)) + hsCb*aSqD // note: cur hv0aC
	//	}
	hvCbN := hvCb + hfCb
	hsCbN := hsCb + hvCbN

	hf0a := Laplacian26(x, y, z, int32(EWHs0a), prv, hs0a)
	hf0a += vfac * hs0a
	hf0a *= csq
	hv0aN := hv0a + hf0a
	hs0aN := hs0a + hv0aN

	hf0b := Laplacian26(x, y, z, int32(EWHs0b), prv, hs0b)
	hf0b += vfac * hs0b
	hf0b *= csq
	hv0bN := hv0b + hf0b
	hs0bN := hs0b + hv0bN

	State.Set(hsCaN, int(z), int(y), int(x), int(EWHsCa), int(cur))
	State.Set(hsCbN, int(z), int(y), int(x), int(EWHsCb), int(cur))
	State.Set(hs0aN, int(z), int(y), int(x), int(EWHs0a), int(cur))
	State.Set(hs0bN, int(z), int(y), int(x), int(EWHs0b), int(cur))

	State.Set(hvCaN, int(z), int(y), int(x), int(EWHvCa), int(cur))
	State.Set(hvCbN, int(z), int(y), int(x), int(EWHvCb), int(cur))
	State.Set(hv0aN, int(z), int(y), int(x), int(EWHv0a), int(cur))
	State.Set(hv0bN, int(z), int(y), int(x), int(EWHv0b), int(cur))

	State.Set(mag, int(z), int(y), int(x), int(EWHmag), int(cur))
	State.Set(-0.5*musq*mag+0.25*lambda*mag*mag, int(z), int(y), int(x), int(EWHV), int(cur))
}

//gosl:end

func (ss *Sim) ElectroweakConfig() {
	ParamsShouldDisplay = ElectroweakDisplay
	ss.StateVars = EWStatesN
	ss.ViewInit(func(view *View) {
		view.SetVar(EWHs0a, -1)
	})
}

// ElectroweakViewAll configures the View to display Electroweak values
func ElectroweakViewAll(view *View) {
	view.Settings.NPanels = PanelsFour
	view.Settings.Camera = 2
	view.Settings.Height = 0.8
	view.Panels[0].Var = EWHs0a
	view.Panels[1].Var = A0s
	// view.SetCurPrev(Previous, 1)
	view.Panels[2].Var = EWHmag
	// view.SetCurPrev(Previous, 3)
	view.Panels[3].Var = EWHV
	// view.Settings.TrackParticle = 0
}

func (ss *Sim) ElectroweakStats() {
	ss.AddStat(ss.StatStep())
	ss.AddStat(ss.StatSum(EWHmag))
	ss.AddStat(ss.StatSum(EWHV))
	// ss.AddStat(ss.StatParticle(0))
	// ss.AddStat(ss.StatParticle(0))
}

func (ss *Sim) ElectroweakInit() {
	// The vacuum is <Phi> = (0, v/sqrt2)^T, i.e. the NEUTRAL (lower) component
	// holds the VEV, with magnitude v = mu/sqrt(lambda) -- not mu. Putting it
	// in the charged component instead would leave Q = T^3 + Y broken and give
	// the photon a mass.
	ss.Fill(EWHs0a, Both, ss.Params.HiggsV)
	ctx := GetCtx(0)
	ne := int(ctx.EdgesN())
	RunEdgesWrapKernel(ne)
}

// ElectroweakDisplay determines which Parameters fields to display.
var ElectroweakDisplay = []string{"Edges", "Energy", "C", "Hbar", "Mass", "EM", "A0NoWave", "E", "Mu0", "HiggsMu", "HiggsLambda"}
