// Code generated by "core generate -add-types -add-funcs -gosl"; DO NOT EDIT.

package wavesim

import (
	"cogentcore.org/core/enums"
)

var _GPUVarsValues = []GPUVars{0, 1, 2, 3, 4}

// GPUVarsN is the highest valid value for type GPUVars, plus one.
//
//gosl:start
const GPUVarsN GPUVars = 5

//gosl:end

var _GPUVarsValueMap = map[string]GPUVars{`ParamsVar`: 0, `NeighOffsVar`: 1, `LaplacianWtsVar`: 2, `CtxVar`: 3, `StateVar`: 4}

var _GPUVarsDescMap = map[GPUVars]string{0: ``, 1: ``, 2: ``, 3: ``, 4: ``}

var _GPUVarsMap = map[GPUVars]string{0: `ParamsVar`, 1: `NeighOffsVar`, 2: `LaplacianWtsVar`, 3: `CtxVar`, 4: `StateVar`}

// String returns the string representation of this GPUVars value.
func (i GPUVars) String() string { return enums.String(i, _GPUVarsMap) }

// SetString sets the GPUVars value from its string representation,
// and returns an error if the string is invalid.
func (i *GPUVars) SetString(s string) error {
	return enums.SetString(i, s, _GPUVarsValueMap, "GPUVars")
}

// Int64 returns the GPUVars value as an int64.
func (i GPUVars) Int64() int64 { return int64(i) }

// SetInt64 sets the GPUVars value from an int64.
func (i *GPUVars) SetInt64(in int64) { *i = GPUVars(in) }

// Desc returns the description of the GPUVars value.
func (i GPUVars) Desc() string { return enums.Desc(i, _GPUVarsDescMap) }

// GPUVarsValues returns all possible values for the type GPUVars.
func GPUVarsValues() []GPUVars { return _GPUVarsValues }

// Values returns all possible values for the type GPUVars.
func (i GPUVars) Values() []enums.Enum { return enums.Values(_GPUVarsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i GPUVars) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *GPUVars) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "GPUVars") }

var _EquationsValues = []Equations{0, 1, 2, 3, 4, 5}

// EquationsN is the highest valid value for type Equations, plus one.
//
//gosl:start
const EquationsN Equations = 6

//gosl:end

var _EquationsValueMap = map[string]Equations{`Wave1D`: 0, `Wave3D`: 1, `KleinGordon1D`: 2, `KleinGordon3D`: 3, `Schrodinger1D`: 4, `Schrodinger3D`: 5}

var _EquationsDescMap = map[Equations]string{0: `Wave1D is the basic wave equation in one dimension (X).`, 1: `Wave3D is the basic wave equation in three dimensions.`, 2: `KleinGordon is the 1D Klein-Gordon massive particle wave function.`, 3: `KleinGordon3D is the 3D Klein-Gordon massive particle wave function.`, 4: `Schrodinger is the 1D Schrodinger wave function.`, 5: `Schrodinger is the 3D Schrodinger wave function.`}

var _EquationsMap = map[Equations]string{0: `Wave1D`, 1: `Wave3D`, 2: `KleinGordon1D`, 3: `KleinGordon3D`, 4: `Schrodinger1D`, 5: `Schrodinger3D`}

// String returns the string representation of this Equations value.
func (i Equations) String() string { return enums.String(i, _EquationsMap) }

// SetString sets the Equations value from its string representation,
// and returns an error if the string is invalid.
func (i *Equations) SetString(s string) error {
	return enums.SetString(i, s, _EquationsValueMap, "Equations")
}

// Int64 returns the Equations value as an int64.
func (i Equations) Int64() int64 { return int64(i) }

// SetInt64 sets the Equations value from an int64.
func (i *Equations) SetInt64(in int64) { *i = Equations(in) }

// Desc returns the description of the Equations value.
func (i Equations) Desc() string { return enums.Desc(i, _EquationsDescMap) }

// EquationsValues returns all possible values for the type Equations.
func EquationsValues() []Equations { return _EquationsValues }

// Values returns all possible values for the type Equations.
func (i Equations) Values() []enums.Enum { return enums.Values(_EquationsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Equations) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Equations) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "Equations")
}

var _EdgesValues = []Edges{0, 1}

// EdgesN is the highest valid value for type Edges, plus one.
//
//gosl:start
const EdgesN Edges = 2

//gosl:end

var _EdgesValueMap = map[string]Edges{`EdgesFixed`: 0, `EdgesWrap`: 1}

var _EdgesDescMap = map[Edges]string{0: `EdgesFixed keeps the edge values fixed at initial values`, 1: `EdgesWrap copies edge values from other side, effectively wrapping the space around on itself like a torus.`}

var _EdgesMap = map[Edges]string{0: `EdgesFixed`, 1: `EdgesWrap`}

// String returns the string representation of this Edges value.
func (i Edges) String() string { return enums.String(i, _EdgesMap) }

// SetString sets the Edges value from its string representation,
// and returns an error if the string is invalid.
func (i *Edges) SetString(s string) error { return enums.SetString(i, s, _EdgesValueMap, "Edges") }

// Int64 returns the Edges value as an int64.
func (i Edges) Int64() int64 { return int64(i) }

// SetInt64 sets the Edges value from an int64.
func (i *Edges) SetInt64(in int64) { *i = Edges(in) }

// Desc returns the description of the Edges value.
func (i Edges) Desc() string { return enums.Desc(i, _EdgesDescMap) }

// EdgesValues returns all possible values for the type Edges.
func EdgesValues() []Edges { return _EdgesValues }

// Values returns all possible values for the type Edges.
func (i Edges) Values() []enums.Enum { return enums.Values(_EdgesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Edges) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Edges) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "Edges") }

var _CabStatesValues = []CabStates{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

// CabStatesN is the highest valid value for type CabStates, plus one.
//
//gosl:start
const CabStatesN CabStates = 10

//gosl:end

var _CabStatesValueMap = map[string]CabStates{`PosA`: 0, `PosB`: 1, `VelA`: 2, `VelB`: 3, `ForceA`: 4, `ForceB`: 5, `V`: 6, `CompConj`: 7, `Kinetic`: 8, `Energy`: 9}

var _CabStatesDescMap = map[CabStates]string{0: `CabPosA is the position (height) wave state variable for the real complex component A.`, 1: `CabPosB is the position (height) wave state variable for the imaginary complex component B.`, 2: `CabVelA is the velocity of wave state variable for the real complex component A.`, 3: `CabVelB is the velocity of wave state variable for the imaginary complex component B.`, 4: `CabForceA is the net force computed from neighbors for the real complex component A.`, 5: `CabForceB is the net force computed from neighbors for the imaginary complex component B.`, 6: `CabV is an external potential energy factor, that can be used to push particles around.`, 7: `CabCompConj is the complex conjugate (&#34;squared&#34;) wave value, which represents the total probability or a conserved charge value.`, 8: `CabKinetic is the total kinetic energy across components.`, 9: `CabEnergy is the total kinetic + potential energy.`}

var _CabStatesMap = map[CabStates]string{0: `PosA`, 1: `PosB`, 2: `VelA`, 3: `VelB`, 4: `ForceA`, 5: `ForceB`, 6: `V`, 7: `CompConj`, 8: `Kinetic`, 9: `Energy`}

// String returns the string representation of this CabStates value.
func (i CabStates) String() string { return enums.String(i, _CabStatesMap) }

// SetString sets the CabStates value from its string representation,
// and returns an error if the string is invalid.
func (i *CabStates) SetString(s string) error {
	return enums.SetString(i, s, _CabStatesValueMap, "CabStates")
}

// Int64 returns the CabStates value as an int64.
func (i CabStates) Int64() int64 { return int64(i) }

// SetInt64 sets the CabStates value from an int64.
func (i *CabStates) SetInt64(in int64) { *i = CabStates(in) }

// Desc returns the description of the CabStates value.
func (i CabStates) Desc() string { return enums.Desc(i, _CabStatesDescMap) }

// CabStatesValues returns all possible values for the type CabStates.
func CabStatesValues() []CabStates { return _CabStatesValues }

// Values returns all possible values for the type CabStates.
func (i CabStates) Values() []enums.Enum { return enums.Values(_CabStatesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i CabStates) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *CabStates) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "CabStates")
}

var _ViewModesValues = []ViewModes{0, 1}

// ViewModesN is the highest valid value for type ViewModes, plus one.
//
//gosl:start
const ViewModesN ViewModes = 2

//gosl:end

var _ViewModesValueMap = map[string]ViewModes{`Plane`: 0, `Bars`: 1}

var _ViewModesDescMap = map[ViewModes]string{0: `Plane displays a contiguous plane of values -- best for smooth states.`, 1: `Bars displays discrete bars at each point -- best for more discontinuous states.`}

var _ViewModesMap = map[ViewModes]string{0: `Plane`, 1: `Bars`}

// String returns the string representation of this ViewModes value.
func (i ViewModes) String() string { return enums.String(i, _ViewModesMap) }

// SetString sets the ViewModes value from its string representation,
// and returns an error if the string is invalid.
func (i *ViewModes) SetString(s string) error {
	return enums.SetString(i, s, _ViewModesValueMap, "ViewModes")
}

// Int64 returns the ViewModes value as an int64.
func (i ViewModes) Int64() int64 { return int64(i) }

// SetInt64 sets the ViewModes value from an int64.
func (i *ViewModes) SetInt64(in int64) { *i = ViewModes(in) }

// Desc returns the description of the ViewModes value.
func (i ViewModes) Desc() string { return enums.Desc(i, _ViewModesDescMap) }

// ViewModesValues returns all possible values for the type ViewModes.
func ViewModesValues() []ViewModes { return _ViewModesValues }

// Values returns all possible values for the type ViewModes.
func (i ViewModes) Values() []enums.Enum { return enums.Values(_ViewModesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i ViewModes) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *ViewModes) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "ViewModes")
}

var _CurPrevValues = []CurPrev{0, 1}

// CurPrevN is the highest valid value for type CurPrev, plus one.
//
//gosl:start
const CurPrevN CurPrev = 2

//gosl:end

var _CurPrevValueMap = map[string]CurPrev{`Current`: 0, `Previous`: 1}

var _CurPrevDescMap = map[CurPrev]string{0: `Current selects the current state value (most recently updated).`, 1: `Previous selects the previous state value.`}

var _CurPrevMap = map[CurPrev]string{0: `Current`, 1: `Previous`}

// String returns the string representation of this CurPrev value.
func (i CurPrev) String() string { return enums.String(i, _CurPrevMap) }

// SetString sets the CurPrev value from its string representation,
// and returns an error if the string is invalid.
func (i *CurPrev) SetString(s string) error {
	return enums.SetString(i, s, _CurPrevValueMap, "CurPrev")
}

// Int64 returns the CurPrev value as an int64.
func (i CurPrev) Int64() int64 { return int64(i) }

// SetInt64 sets the CurPrev value from an int64.
func (i *CurPrev) SetInt64(in int64) { *i = CurPrev(in) }

// Desc returns the description of the CurPrev value.
func (i CurPrev) Desc() string { return enums.Desc(i, _CurPrevDescMap) }

// CurPrevValues returns all possible values for the type CurPrev.
func CurPrevValues() []CurPrev { return _CurPrevValues }

// Values returns all possible values for the type CurPrev.
func (i CurPrev) Values() []enums.Enum { return enums.Values(_CurPrevValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i CurPrev) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *CurPrev) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "CurPrev") }

var _NPanelsValues = []NPanels{0, 1, 2}

// NPanelsN is the highest valid value for type NPanels, plus one.
//
//gosl:start
const NPanelsN NPanels = 3

//gosl:end

var _NPanelsValueMap = map[string]NPanels{`One`: 0, `Two`: 1, `Four`: 2}

var _NPanelsDescMap = map[NPanels]string{0: `One panel`, 1: `Two side-by-side panels`, 2: `Four bottom-top and side-by-side panels`}

var _NPanelsMap = map[NPanels]string{0: `One`, 1: `Two`, 2: `Four`}

// String returns the string representation of this NPanels value.
func (i NPanels) String() string { return enums.String(i, _NPanelsMap) }

// SetString sets the NPanels value from its string representation,
// and returns an error if the string is invalid.
func (i *NPanels) SetString(s string) error {
	return enums.SetString(i, s, _NPanelsValueMap, "NPanels")
}

// Int64 returns the NPanels value as an int64.
func (i NPanels) Int64() int64 { return int64(i) }

// SetInt64 sets the NPanels value from an int64.
func (i *NPanels) SetInt64(in int64) { *i = NPanels(in) }

// Desc returns the description of the NPanels value.
func (i NPanels) Desc() string { return enums.Desc(i, _NPanelsDescMap) }

// NPanelsValues returns all possible values for the type NPanels.
func NPanelsValues() []NPanels { return _NPanelsValues }

// Values returns all possible values for the type NPanels.
func (i NPanels) Values() []enums.Enum { return enums.Values(_NPanelsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i NPanels) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *NPanels) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "NPanels") }

var _WaveStatesValues = []WaveStates{0, 1, 2, 3, 4, 5}

// WaveStatesN is the highest valid value for type WaveStates, plus one.
//
//gosl:start
const WaveStatesN WaveStates = 6

//gosl:end

var _WaveStatesValueMap = map[string]WaveStates{`Pos`: 0, `Vel`: 1, `Force`: 2, `Kinetic`: 3, `Potential`: 4, `Energy`: 5}

var _WaveStatesDescMap = map[WaveStates]string{0: `WavePos is the position (height) wave state variable.`, 1: `WaveVel is the velocity of wave state variable.`, 2: `WaveForce is the net force computed from neighbors.`, 3: `WaveKinetic is the kinetic energy.`, 4: `WavePotential is the potential energy.`, 5: `WaveEnergy is the total kinetic + potential energy.`}

var _WaveStatesMap = map[WaveStates]string{0: `Pos`, 1: `Vel`, 2: `Force`, 3: `Kinetic`, 4: `Potential`, 5: `Energy`}

// String returns the string representation of this WaveStates value.
func (i WaveStates) String() string { return enums.String(i, _WaveStatesMap) }

// SetString sets the WaveStates value from its string representation,
// and returns an error if the string is invalid.
func (i *WaveStates) SetString(s string) error {
	return enums.SetString(i, s, _WaveStatesValueMap, "WaveStates")
}

// Int64 returns the WaveStates value as an int64.
func (i WaveStates) Int64() int64 { return int64(i) }

// SetInt64 sets the WaveStates value from an int64.
func (i *WaveStates) SetInt64(in int64) { *i = WaveStates(in) }

// Desc returns the description of the WaveStates value.
func (i WaveStates) Desc() string { return enums.Desc(i, _WaveStatesDescMap) }

// WaveStatesValues returns all possible values for the type WaveStates.
func WaveStatesValues() []WaveStates { return _WaveStatesValues }

// Values returns all possible values for the type WaveStates.
func (i WaveStates) Values() []enums.Enum { return enums.Values(_WaveStatesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i WaveStates) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *WaveStates) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "WaveStates")
}
