// Code generated by "core generate -add-types -add-funcs -gosl"; DO NOT EDIT.

package wavesim

import (
	"cogentcore.org/core/enums"
)

var _DiracStatesValues = []DiracStates{18, 19, 20, 21, 22, 23, 24, 25, 26}

// DiracStatesN is the highest valid value for type DiracStates, plus one.
//
//gosl:start
const DiracStatesN DiracStates = 27

//gosl:end

var _DiracStatesValueMap = map[string]DiracStates{`Pos1A`: 18, `Pos1B`: 19, `Pos2A`: 20, `Pos2B`: 21, `Vel1A`: 22, `Vel1B`: 23, `Vel2A`: 24, `Vel2B`: 25, `CC`: 26}

var _DiracStatesDescMap = map[DiracStates]string{18: `DiracPos1A is the position (height) wave state variable 1 for the real complex component A.`, 19: `DiracPos1B is the position (height) wave state variable 1 for the imaginary complex component B.`, 20: `DiracPos2A is the position (height) wave state variable 2 for the real complex component A.`, 21: `DiracPos2B is the position (height) wave state variable 2 for the imaginary complex component B.`, 22: `DiracVel1A is the velocity of wave state variable 1 for the real complex component A.`, 23: `DiracVel1B is the velocity of wave state variable 1 for the imaginary complex component B.`, 24: `DiracVel2A is the velocity of wave state variable 2 for the real complex component A.`, 25: `DiracVel2B is the velocity of wave state variable 2 for the imaginary complex component B.`, 26: `DiracCC is the complex conjugate (&#34;squared&#34;) wave value, which represents the total probability or a conserved charge value.`}

var _DiracStatesMap = map[DiracStates]string{18: `Pos1A`, 19: `Pos1B`, 20: `Pos2A`, 21: `Pos2B`, 22: `Vel1A`, 23: `Vel1B`, 24: `Vel2A`, 25: `Vel2B`, 26: `CC`}

// String returns the string representation of this DiracStates value.
func (i DiracStates) String() string {
	return enums.StringExtended[DiracStates, EMStates](i, _DiracStatesMap)
}

// SetString sets the DiracStates value from its string representation,
// and returns an error if the string is invalid.
func (i *DiracStates) SetString(s string) error {
	return enums.SetStringExtended(i, (*EMStates)(i), s, _DiracStatesValueMap)
}

// Int64 returns the DiracStates value as an int64.
func (i DiracStates) Int64() int64 { return int64(i) }

// SetInt64 sets the DiracStates value from an int64.
func (i *DiracStates) SetInt64(in int64) { *i = DiracStates(in) }

// Desc returns the description of the DiracStates value.
func (i DiracStates) Desc() string {
	return enums.DescExtended[DiracStates, EMStates](i, _DiracStatesDescMap)
}

// DiracStatesValues returns all possible values for the type DiracStates.
func DiracStatesValues() []DiracStates {
	return enums.ValuesGlobalExtended(_DiracStatesValues, EMStatesValues())
}

// Values returns all possible values for the type DiracStates.
func (i DiracStates) Values() []enums.Enum {
	return enums.ValuesExtended(_DiracStatesValues, EMStatesValues())
}

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i DiracStates) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *DiracStates) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "DiracStates")
}

var _EdgesValues = []Edges{0, 1, 2}

// EdgesN is the highest valid value for type Edges, plus one.
//
//gosl:start
const EdgesN Edges = 3

//gosl:end

var _EdgesValueMap = map[string]Edges{`Fixed`: 0, `Wrap`: 1, `Damp`: 2}

var _EdgesDescMap = map[Edges]string{0: `EdgesFixed keeps the edge values fixed at initial values`, 1: `EdgesWrap copies edge values from other side, effectively wrapping the space around on itself like a torus.`, 2: `EdgesDamp implements damping of edge values.`}

var _EdgesMap = map[Edges]string{0: `Fixed`, 1: `Wrap`, 2: `Damp`}

// String returns the string representation of this Edges value.
func (i Edges) String() string { return enums.String(i, _EdgesMap) }

// SetString sets the Edges value from its string representation,
// and returns an error if the string is invalid.
func (i *Edges) SetString(s string) error { return enums.SetString(i, s, _EdgesValueMap, "Edges") }

// Int64 returns the Edges value as an int64.
func (i Edges) Int64() int64 { return int64(i) }

// SetInt64 sets the Edges value from an int64.
func (i *Edges) SetInt64(in int64) { *i = Edges(in) }

// Desc returns the description of the Edges value.
func (i Edges) Desc() string { return enums.Desc(i, _EdgesDescMap) }

// EdgesValues returns all possible values for the type Edges.
func EdgesValues() []Edges { return _EdgesValues }

// Values returns all possible values for the type Edges.
func (i Edges) Values() []enums.Enum { return enums.Values(_EdgesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Edges) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Edges) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "Edges") }

var _MinusPlusOneValues = []MinusPlusOne{0, 1}

// MinusPlusOneN is the highest valid value for type MinusPlusOne, plus one.
//
//gosl:start
const MinusPlusOneN MinusPlusOne = 2

//gosl:end

var _MinusPlusOneValueMap = map[string]MinusPlusOne{`Minus1`: 0, `Plus1`: 1}

var _MinusPlusOneDescMap = map[MinusPlusOne]string{0: ``, 1: ``}

var _MinusPlusOneMap = map[MinusPlusOne]string{0: `Minus1`, 1: `Plus1`}

// String returns the string representation of this MinusPlusOne value.
func (i MinusPlusOne) String() string { return enums.String(i, _MinusPlusOneMap) }

// SetString sets the MinusPlusOne value from its string representation,
// and returns an error if the string is invalid.
func (i *MinusPlusOne) SetString(s string) error {
	return enums.SetString(i, s, _MinusPlusOneValueMap, "MinusPlusOne")
}

// Int64 returns the MinusPlusOne value as an int64.
func (i MinusPlusOne) Int64() int64 { return int64(i) }

// SetInt64 sets the MinusPlusOne value from an int64.
func (i *MinusPlusOne) SetInt64(in int64) { *i = MinusPlusOne(in) }

// Desc returns the description of the MinusPlusOne value.
func (i MinusPlusOne) Desc() string { return enums.Desc(i, _MinusPlusOneDescMap) }

// MinusPlusOneValues returns all possible values for the type MinusPlusOne.
func MinusPlusOneValues() []MinusPlusOne { return _MinusPlusOneValues }

// Values returns all possible values for the type MinusPlusOne.
func (i MinusPlusOne) Values() []enums.Enum { return enums.Values(_MinusPlusOneValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i MinusPlusOne) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *MinusPlusOne) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "MinusPlusOne")
}

var _NeighWeightsValues = []NeighWeights{0, 1, 2}

// NeighWeightsN is the highest valid value for type NeighWeights, plus one.
//
//gosl:start
const NeighWeightsN NeighWeights = 3

//gosl:end

var _NeighWeightsValueMap = map[string]NeighWeights{`LaplacianWts`: 0, `AverageWts`: 1, `Grad18Wts`: 2}

var _NeighWeightsDescMap = map[NeighWeights]string{0: `LaplacianWts are weighting factors for 3D Laplacian = 3 / (13 * d^2)`, 1: `AverageWts are 26 + 1 ctr average weights = 1 / d`, 2: `Grad18Wts are 18 neighbor gradaients`}

var _NeighWeightsMap = map[NeighWeights]string{0: `LaplacianWts`, 1: `AverageWts`, 2: `Grad18Wts`}

// String returns the string representation of this NeighWeights value.
func (i NeighWeights) String() string { return enums.String(i, _NeighWeightsMap) }

// SetString sets the NeighWeights value from its string representation,
// and returns an error if the string is invalid.
func (i *NeighWeights) SetString(s string) error {
	return enums.SetString(i, s, _NeighWeightsValueMap, "NeighWeights")
}

// Int64 returns the NeighWeights value as an int64.
func (i NeighWeights) Int64() int64 { return int64(i) }

// SetInt64 sets the NeighWeights value from an int64.
func (i *NeighWeights) SetInt64(in int64) { *i = NeighWeights(in) }

// Desc returns the description of the NeighWeights value.
func (i NeighWeights) Desc() string { return enums.Desc(i, _NeighWeightsDescMap) }

// NeighWeightsValues returns all possible values for the type NeighWeights.
func NeighWeightsValues() []NeighWeights { return _NeighWeightsValues }

// Values returns all possible values for the type NeighWeights.
func (i NeighWeights) Values() []enums.Enum { return enums.Values(_NeighWeightsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i NeighWeights) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *NeighWeights) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "NeighWeights")
}

var _GPUVarsValues = []GPUVars{0, 1, 2, 3, 4, 5}

// GPUVarsN is the highest valid value for type GPUVars, plus one.
//
//gosl:start
const GPUVarsN GPUVars = 6

//gosl:end

var _GPUVarsValueMap = map[string]GPUVars{`ParamsVar`: 0, `NeighOffsVar`: 1, `FaceOffsVar`: 2, `NeighWtsVar`: 3, `CtxVar`: 4, `StateVar`: 5}

var _GPUVarsDescMap = map[GPUVars]string{0: ``, 1: ``, 2: ``, 3: ``, 4: ``, 5: ``}

var _GPUVarsMap = map[GPUVars]string{0: `ParamsVar`, 1: `NeighOffsVar`, 2: `FaceOffsVar`, 3: `NeighWtsVar`, 4: `CtxVar`, 5: `StateVar`}

// String returns the string representation of this GPUVars value.
func (i GPUVars) String() string { return enums.String(i, _GPUVarsMap) }

// SetString sets the GPUVars value from its string representation,
// and returns an error if the string is invalid.
func (i *GPUVars) SetString(s string) error {
	return enums.SetString(i, s, _GPUVarsValueMap, "GPUVars")
}

// Int64 returns the GPUVars value as an int64.
func (i GPUVars) Int64() int64 { return int64(i) }

// SetInt64 sets the GPUVars value from an int64.
func (i *GPUVars) SetInt64(in int64) { *i = GPUVars(in) }

// Desc returns the description of the GPUVars value.
func (i GPUVars) Desc() string { return enums.Desc(i, _GPUVarsDescMap) }

// GPUVarsValues returns all possible values for the type GPUVars.
func GPUVarsValues() []GPUVars { return _GPUVarsValues }

// Values returns all possible values for the type GPUVars.
func (i GPUVars) Values() []enums.Enum { return enums.Values(_GPUVarsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i GPUVars) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *GPUVars) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "GPUVars") }

var _CabStatesValues = []CabStates{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}

// CabStatesN is the highest valid value for type CabStates, plus one.
//
//gosl:start
const CabStatesN CabStates = 15

//gosl:end

var _CabStatesValueMap = map[string]CabStates{`PosA`: 0, `PosB`: 1, `VelA`: 2, `VelB`: 3, `ForceA`: 4, `ForceB`: 5, `V`: 6, `CC`: 7, `Charge`: 8, `CurrentX`: 9, `CurrentY`: 10, `CurrentZ`: 11, `Kinetic`: 12, `Potential`: 13, `Energy`: 14}

var _CabStatesDescMap = map[CabStates]string{0: `CabPosA is the position (height) wave state variable for the real complex component A.`, 1: `CabPosB is the position (height) wave state variable for the imaginary complex component B.`, 2: `CabVelA is the velocity of wave state variable for the real complex component A.`, 3: `CabVelB is the velocity of wave state variable for the imaginary complex component B.`, 4: `CabForceA is the net force computed from neighbors for the real complex component A.`, 5: `CabForceB is the net force computed from neighbors for the imaginary complex component B.`, 6: `CabV is an external potential energy factor, that can be used to push particles around.`, 7: `CabCC is the complex conjugate (&#34;squared&#34;) wave value, which represents the total probability or a conserved charge value.`, 8: `CabCharge is the charge density.`, 9: `CabCurrentX is the current density.`, 10: `CabCurrentY is the current density.`, 11: `CabCurrentZ is the current density.`, 12: `CabKinetic is the total kinetic energy across components.`, 13: `CabPotential is the total potential energy across components (only for KGC).`, 14: `CabEnergy is the total kinetic + potential energy.`}

var _CabStatesMap = map[CabStates]string{0: `PosA`, 1: `PosB`, 2: `VelA`, 3: `VelB`, 4: `ForceA`, 5: `ForceB`, 6: `V`, 7: `CC`, 8: `Charge`, 9: `CurrentX`, 10: `CurrentY`, 11: `CurrentZ`, 12: `Kinetic`, 13: `Potential`, 14: `Energy`}

// String returns the string representation of this CabStates value.
func (i CabStates) String() string { return enums.String(i, _CabStatesMap) }

// SetString sets the CabStates value from its string representation,
// and returns an error if the string is invalid.
func (i *CabStates) SetString(s string) error {
	return enums.SetString(i, s, _CabStatesValueMap, "CabStates")
}

// Int64 returns the CabStates value as an int64.
func (i CabStates) Int64() int64 { return int64(i) }

// SetInt64 sets the CabStates value from an int64.
func (i *CabStates) SetInt64(in int64) { *i = CabStates(in) }

// Desc returns the description of the CabStates value.
func (i CabStates) Desc() string { return enums.Desc(i, _CabStatesDescMap) }

// CabStatesValues returns all possible values for the type CabStates.
func CabStatesValues() []CabStates { return _CabStatesValues }

// Values returns all possible values for the type CabStates.
func (i CabStates) Values() []enums.Enum { return enums.Values(_CabStatesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i CabStates) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *CabStates) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "CabStates")
}

var _EMStatesValues = []EMStates{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}

// EMStatesN is the highest valid value for type EMStates, plus one.
//
//gosl:start
const EMStatesN EMStates = 18

//gosl:end

var _EMStatesValueMap = map[string]EMStates{`A0Pos`: 0, `AXPos`: 1, `AYPos`: 2, `AZPos`: 3, `A0Vel`: 4, `AXVel`: 5, `AYVel`: 6, `AZVel`: 7, `EX`: 8, `EY`: 9, `EZ`: 10, `BX`: 11, `BY`: 12, `BZ`: 13, `Charge`: 14, `CurrentX`: 15, `CurrentY`: 16, `CurrentZ`: 17}

var _EMStatesDescMap = map[EMStates]string{0: `A0Pos is the position (height) wave state variable for the EM A0 electrical (scalar) potential field.`, 1: `AXPos is the position (height) wave state variable for the EM AX magnetic (vector) potential field, X component.`, 2: `AYPos is the position (height) wave state variable for the EM AY magnetic (vector) potential field, Y component.`, 3: `AZPos is the position (height) wave state variable for the EM AZ magnetic (vector) potential field, Z component.`, 4: `A0Vel is the velocity of wave state variable for the EM A0 electrical (scalar) potential field.`, 5: `AXVel is the velocity of wave state variable for the EM AX magnetic (vector) potential field, X component.`, 6: `AYVel is the velocity of wave state variable for the EM AY magnetic (vector) potential field, Y component.`, 7: `AZVel is the velocity of wave state variable for the EM AZ magnetic (vector) potential field, Z component.`, 8: `EX is the electrical vector field, X component: -grad A_0 - d \vec{A}/dt`, 9: `EY is the electrical vector field, Y component: -grad A_0 - d \vec{A}/dt`, 10: `EZ is the electrical vector field, Z component: -grad A_0 - d \vec{A}/dt`, 11: `BX is the magnetic vector field, X component: curl \vec{A}`, 12: `BY is the magnetic vector field, Y component: curl \vec{A}`, 13: `BZ is the magnetic vector field, Z component: curl \vec{A}`, 14: `Charge is the density of charge, drives A0.`, 15: `CurrentX is the density of current, X component, drives AX.`, 16: `CurrentY is the density of current, Y component, drives AY.`, 17: `CurrentZ is the density of current, Z component, drives AZ.`}

var _EMStatesMap = map[EMStates]string{0: `A0Pos`, 1: `AXPos`, 2: `AYPos`, 3: `AZPos`, 4: `A0Vel`, 5: `AXVel`, 6: `AYVel`, 7: `AZVel`, 8: `EX`, 9: `EY`, 10: `EZ`, 11: `BX`, 12: `BY`, 13: `BZ`, 14: `Charge`, 15: `CurrentX`, 16: `CurrentY`, 17: `CurrentZ`}

// String returns the string representation of this EMStates value.
func (i EMStates) String() string { return enums.String(i, _EMStatesMap) }

// SetString sets the EMStates value from its string representation,
// and returns an error if the string is invalid.
func (i *EMStates) SetString(s string) error {
	return enums.SetString(i, s, _EMStatesValueMap, "EMStates")
}

// Int64 returns the EMStates value as an int64.
func (i EMStates) Int64() int64 { return int64(i) }

// SetInt64 sets the EMStates value from an int64.
func (i *EMStates) SetInt64(in int64) { *i = EMStates(in) }

// Desc returns the description of the EMStates value.
func (i EMStates) Desc() string { return enums.Desc(i, _EMStatesDescMap) }

// EMStatesValues returns all possible values for the type EMStates.
func EMStatesValues() []EMStates { return _EMStatesValues }

// Values returns all possible values for the type EMStates.
func (i EMStates) Values() []enums.Enum { return enums.Values(_EMStatesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i EMStates) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *EMStates) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "EMStates") }

var _EquationsValues = []Equations{0, 1, 2, 3, 4, 5, 6}

// EquationsN is the highest valid value for type Equations, plus one.
//
//gosl:start
const EquationsN Equations = 7

//gosl:end

var _EquationsValueMap = map[string]Equations{`Wave`: 0, `KleinGordon`: 1, `KleinGordonC`: 2, `Schrodinger`: 3, `Maxwell`: 4, `Dirac`: 5, `ParticleKGC`: 6}

var _EquationsDescMap = map[Equations]string{0: `Wave is the basic wave equation in one dimension (X).`, 1: `KleinGordon is the Klein-Gordon massive particle wave function, on a scalar wave state.`, 2: `KleinGordonC is the Klein-Gordon massive particle wave function, on a complex wave state.`, 3: `Schrodinger is the Schrodinger wave function on complex state.`, 4: `Maxwell is Maxwell&#39;s equations for electromagnetic (EM) waves.`, 5: `Dirac is Dirac&#39;s wave equation coupled with electromagnetic (EM) waves.`, 6: `ParticleKGC is the Klein-Gordon complex version of stochastic particles.`}

var _EquationsMap = map[Equations]string{0: `Wave`, 1: `KleinGordon`, 2: `KleinGordonC`, 3: `Schrodinger`, 4: `Maxwell`, 5: `Dirac`, 6: `ParticleKGC`}

// String returns the string representation of this Equations value.
func (i Equations) String() string { return enums.String(i, _EquationsMap) }

// SetString sets the Equations value from its string representation,
// and returns an error if the string is invalid.
func (i *Equations) SetString(s string) error {
	return enums.SetString(i, s, _EquationsValueMap, "Equations")
}

// Int64 returns the Equations value as an int64.
func (i Equations) Int64() int64 { return int64(i) }

// SetInt64 sets the Equations value from an int64.
func (i *Equations) SetInt64(in int64) { *i = Equations(in) }

// Desc returns the description of the Equations value.
func (i Equations) Desc() string { return enums.Desc(i, _EquationsDescMap) }

// EquationsValues returns all possible values for the type Equations.
func EquationsValues() []Equations { return _EquationsValues }

// Values returns all possible values for the type Equations.
func (i Equations) Values() []enums.Enum { return enums.Values(_EquationsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Equations) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Equations) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "Equations")
}

var _ParticleKGCStatesValues = []ParticleKGCStates{15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29}

// ParticleKGCStatesN is the highest valid value for type ParticleKGCStates, plus one.
//
//gosl:start
const ParticleKGCStatesN ParticleKGCStates = 30

//gosl:end

var _ParticleKGCStatesValueMap = map[string]ParticleKGCStates{`MomX`: 15, `MomY`: 16, `MomZ`: 17, `MomXP`: 18, `MomXPv`: 19, `MomXN`: 20, `MomXNv`: 21, `MomYP`: 22, `MomYPv`: 23, `MomYN`: 24, `MomYNv`: 25, `MomZP`: 26, `MomZPv`: 27, `MomZN`: 28, `MomZNv`: 29}

var _ParticleKGCStatesDescMap = map[ParticleKGCStates]string{15: `PKGCMomX is the particle momentum along X axis`, 16: `PKGCMomY is the particle momentum along Y axis`, 17: `PKGCMomZ is the particle momentum along Z axis`, 18: `PKGCMomXP is the SHO position for momentum along positive X axis.`, 19: `PKGCMomXPv is the velocity for SHO position for momentum along positive X axis.`, 20: `PKGCMomXN is the SHO position for momentum along negative X axis.`, 21: `PKGCMomXNv is the velocity for SHO position for momentum along negative X axis.`, 22: `PKGCMomYP is the SHO position for momentum along positive Y axis.`, 23: `PKGCMomYPv is the velocity for SHO position for momentum along positive Y axis.`, 24: `PKGCMomYN is the SHO position for momentum along negative Y axis.`, 25: `PKGCMomYNv is the velocity for SHO position for momentum along negative Y axis.`, 26: `PKGCMomZP is the SHO position for momentum along positive Z axis.`, 27: `PKGCMomZPv is the velocity for SHO position for momentum along positive Z axis.`, 28: `PKGCMomZN is the SHO position for momentum along negative Z axis.`, 29: `PKGCMomZNv is the velocity for SHO position for momentum along negative Z axis.`}

var _ParticleKGCStatesMap = map[ParticleKGCStates]string{15: `MomX`, 16: `MomY`, 17: `MomZ`, 18: `MomXP`, 19: `MomXPv`, 20: `MomXN`, 21: `MomXNv`, 22: `MomYP`, 23: `MomYPv`, 24: `MomYN`, 25: `MomYNv`, 26: `MomZP`, 27: `MomZPv`, 28: `MomZN`, 29: `MomZNv`}

// String returns the string representation of this ParticleKGCStates value.
func (i ParticleKGCStates) String() string {
	return enums.StringExtended[ParticleKGCStates, CabStates](i, _ParticleKGCStatesMap)
}

// SetString sets the ParticleKGCStates value from its string representation,
// and returns an error if the string is invalid.
func (i *ParticleKGCStates) SetString(s string) error {
	return enums.SetStringExtended(i, (*CabStates)(i), s, _ParticleKGCStatesValueMap)
}

// Int64 returns the ParticleKGCStates value as an int64.
func (i ParticleKGCStates) Int64() int64 { return int64(i) }

// SetInt64 sets the ParticleKGCStates value from an int64.
func (i *ParticleKGCStates) SetInt64(in int64) { *i = ParticleKGCStates(in) }

// Desc returns the description of the ParticleKGCStates value.
func (i ParticleKGCStates) Desc() string {
	return enums.DescExtended[ParticleKGCStates, CabStates](i, _ParticleKGCStatesDescMap)
}

// ParticleKGCStatesValues returns all possible values for the type ParticleKGCStates.
func ParticleKGCStatesValues() []ParticleKGCStates {
	return enums.ValuesGlobalExtended(_ParticleKGCStatesValues, CabStatesValues())
}

// Values returns all possible values for the type ParticleKGCStates.
func (i ParticleKGCStates) Values() []enums.Enum {
	return enums.ValuesExtended(_ParticleKGCStatesValues, CabStatesValues())
}

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i ParticleKGCStates) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *ParticleKGCStates) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "ParticleKGCStates")
}

var _ViewModesValues = []ViewModes{0, 1}

// ViewModesN is the highest valid value for type ViewModes, plus one.
//
//gosl:start
const ViewModesN ViewModes = 2

//gosl:end

var _ViewModesValueMap = map[string]ViewModes{`Plane`: 0, `Bars`: 1}

var _ViewModesDescMap = map[ViewModes]string{0: `Plane displays a contiguous plane of values -- best for smooth states.`, 1: `Bars displays discrete bars at each point -- best for more discontinuous states.`}

var _ViewModesMap = map[ViewModes]string{0: `Plane`, 1: `Bars`}

// String returns the string representation of this ViewModes value.
func (i ViewModes) String() string { return enums.String(i, _ViewModesMap) }

// SetString sets the ViewModes value from its string representation,
// and returns an error if the string is invalid.
func (i *ViewModes) SetString(s string) error {
	return enums.SetString(i, s, _ViewModesValueMap, "ViewModes")
}

// Int64 returns the ViewModes value as an int64.
func (i ViewModes) Int64() int64 { return int64(i) }

// SetInt64 sets the ViewModes value from an int64.
func (i *ViewModes) SetInt64(in int64) { *i = ViewModes(in) }

// Desc returns the description of the ViewModes value.
func (i ViewModes) Desc() string { return enums.Desc(i, _ViewModesDescMap) }

// ViewModesValues returns all possible values for the type ViewModes.
func ViewModesValues() []ViewModes { return _ViewModesValues }

// Values returns all possible values for the type ViewModes.
func (i ViewModes) Values() []enums.Enum { return enums.Values(_ViewModesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i ViewModes) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *ViewModes) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "ViewModes")
}

var _CurPrevValues = []CurPrev{0, 1}

// CurPrevN is the highest valid value for type CurPrev, plus one.
//
//gosl:start
const CurPrevN CurPrev = 2

//gosl:end

var _CurPrevValueMap = map[string]CurPrev{`Current`: 0, `Previous`: 1}

var _CurPrevDescMap = map[CurPrev]string{0: `Current selects the current state value (most recently updated).`, 1: `Previous selects the previous state value.`}

var _CurPrevMap = map[CurPrev]string{0: `Current`, 1: `Previous`}

// String returns the string representation of this CurPrev value.
func (i CurPrev) String() string { return enums.String(i, _CurPrevMap) }

// SetString sets the CurPrev value from its string representation,
// and returns an error if the string is invalid.
func (i *CurPrev) SetString(s string) error {
	return enums.SetString(i, s, _CurPrevValueMap, "CurPrev")
}

// Int64 returns the CurPrev value as an int64.
func (i CurPrev) Int64() int64 { return int64(i) }

// SetInt64 sets the CurPrev value from an int64.
func (i *CurPrev) SetInt64(in int64) { *i = CurPrev(in) }

// Desc returns the description of the CurPrev value.
func (i CurPrev) Desc() string { return enums.Desc(i, _CurPrevDescMap) }

// CurPrevValues returns all possible values for the type CurPrev.
func CurPrevValues() []CurPrev { return _CurPrevValues }

// Values returns all possible values for the type CurPrev.
func (i CurPrev) Values() []enums.Enum { return enums.Values(_CurPrevValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i CurPrev) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *CurPrev) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "CurPrev") }

var _CurPrevBothValues = []CurPrevBoth{0, 1, 2}

// CurPrevBothN is the highest valid value for type CurPrevBoth, plus one.
//
//gosl:start
const CurPrevBothN CurPrevBoth = 3

//gosl:end

var _CurPrevBothValueMap = map[string]CurPrevBoth{`CurOnly`: 0, `PrevOnly`: 1, `Both`: 2}

var _CurPrevBothDescMap = map[CurPrevBoth]string{0: `CurOnly sets only current states.`, 1: `PrevOnly sets only previous states.`, 2: `Both sets both current and previous states.`}

var _CurPrevBothMap = map[CurPrevBoth]string{0: `CurOnly`, 1: `PrevOnly`, 2: `Both`}

// String returns the string representation of this CurPrevBoth value.
func (i CurPrevBoth) String() string { return enums.String(i, _CurPrevBothMap) }

// SetString sets the CurPrevBoth value from its string representation,
// and returns an error if the string is invalid.
func (i *CurPrevBoth) SetString(s string) error {
	return enums.SetString(i, s, _CurPrevBothValueMap, "CurPrevBoth")
}

// Int64 returns the CurPrevBoth value as an int64.
func (i CurPrevBoth) Int64() int64 { return int64(i) }

// SetInt64 sets the CurPrevBoth value from an int64.
func (i *CurPrevBoth) SetInt64(in int64) { *i = CurPrevBoth(in) }

// Desc returns the description of the CurPrevBoth value.
func (i CurPrevBoth) Desc() string { return enums.Desc(i, _CurPrevBothDescMap) }

// CurPrevBothValues returns all possible values for the type CurPrevBoth.
func CurPrevBothValues() []CurPrevBoth { return _CurPrevBothValues }

// Values returns all possible values for the type CurPrevBoth.
func (i CurPrevBoth) Values() []enums.Enum { return enums.Values(_CurPrevBothValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i CurPrevBoth) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *CurPrevBoth) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "CurPrevBoth")
}

var _NPanelsValues = []NPanels{0, 1, 2}

// NPanelsN is the highest valid value for type NPanels, plus one.
//
//gosl:start
const NPanelsN NPanels = 3

//gosl:end

var _NPanelsValueMap = map[string]NPanels{`One`: 0, `Two`: 1, `Four`: 2}

var _NPanelsDescMap = map[NPanels]string{0: `One panel`, 1: `Two side-by-side panels`, 2: `Four bottom-top and side-by-side panels`}

var _NPanelsMap = map[NPanels]string{0: `One`, 1: `Two`, 2: `Four`}

// String returns the string representation of this NPanels value.
func (i NPanels) String() string { return enums.String(i, _NPanelsMap) }

// SetString sets the NPanels value from its string representation,
// and returns an error if the string is invalid.
func (i *NPanels) SetString(s string) error {
	return enums.SetString(i, s, _NPanelsValueMap, "NPanels")
}

// Int64 returns the NPanels value as an int64.
func (i NPanels) Int64() int64 { return int64(i) }

// SetInt64 sets the NPanels value from an int64.
func (i *NPanels) SetInt64(in int64) { *i = NPanels(in) }

// Desc returns the description of the NPanels value.
func (i NPanels) Desc() string { return enums.Desc(i, _NPanelsDescMap) }

// NPanelsValues returns all possible values for the type NPanels.
func NPanelsValues() []NPanels { return _NPanelsValues }

// Values returns all possible values for the type NPanels.
func (i NPanels) Values() []enums.Enum { return enums.Values(_NPanelsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i NPanels) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *NPanels) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "NPanels") }

var _WaveStatesValues = []WaveStates{0, 1, 2, 3, 4, 5}

// WaveStatesN is the highest valid value for type WaveStates, plus one.
//
//gosl:start
const WaveStatesN WaveStates = 6

//gosl:end

var _WaveStatesValueMap = map[string]WaveStates{`Pos`: 0, `Vel`: 1, `Force`: 2, `Kinetic`: 3, `Potential`: 4, `Energy`: 5}

var _WaveStatesDescMap = map[WaveStates]string{0: `WavePos is the position (height) wave state variable.`, 1: `WaveVel is the velocity of wave state variable.`, 2: `WaveForce is the net force computed from neighbors.`, 3: `WaveKinetic is the kinetic energy.`, 4: `WavePotential is the potential energy.`, 5: `WaveEnergy is the total kinetic + potential energy.`}

var _WaveStatesMap = map[WaveStates]string{0: `Pos`, 1: `Vel`, 2: `Force`, 3: `Kinetic`, 4: `Potential`, 5: `Energy`}

// String returns the string representation of this WaveStates value.
func (i WaveStates) String() string { return enums.String(i, _WaveStatesMap) }

// SetString sets the WaveStates value from its string representation,
// and returns an error if the string is invalid.
func (i *WaveStates) SetString(s string) error {
	return enums.SetString(i, s, _WaveStatesValueMap, "WaveStates")
}

// Int64 returns the WaveStates value as an int64.
func (i WaveStates) Int64() int64 { return int64(i) }

// SetInt64 sets the WaveStates value from an int64.
func (i *WaveStates) SetInt64(in int64) { *i = WaveStates(in) }

// Desc returns the description of the WaveStates value.
func (i WaveStates) Desc() string { return enums.Desc(i, _WaveStatesDescMap) }

// WaveStatesValues returns all possible values for the type WaveStates.
func WaveStatesValues() []WaveStates { return _WaveStatesValues }

// Values returns all possible values for the type WaveStates.
func (i WaveStates) Values() []enums.Enum { return enums.Values(_WaveStatesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i WaveStates) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *WaveStates) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "WaveStates")
}
