// Code generated by "goal build"; DO NOT EDIT.
//line funcs.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import (
	// "fmt"

	"cogentcore.org/core/math32"
	"cogentcore.org/lab/tensor"
)

func (ss *Sim) ConfigVars() {
	if Params != nil {
		return
	}
	Params = make([]Parameters, 1)
	Params[0].Defaults()
	ss.Params = &Params[0]
	ss.Units.Defaults()
	Ctx = make([]Context, 1)
	Ctx[0].Init()
	NeighOffs = tensor.NewInt32(26, 3)
	LaplacianWts = tensor.NewFloat32(26)
	lnorm := float32(3.0 / 13.0)
	idx := 0
	for z := -1; z <= 1; z++ {
		for y := -1; y <= 1; y++ {
			for x := -1; x <= 1; x++ {
				if x == 0 && y == 0 && z == 0 {
					continue
				}
				NeighOffs.Set(int32(x), int(idx), int(math32.X))
				NeighOffs.Set(int32(y), int(idx), int(math32.Y))
				NeighOffs.Set(int32(z), int(idx), int(math32.Z))

				v := math32.Vec3(float32(x), float32(y), float32(z))
				d2 := v.LengthSquared()
				// d := v.Length()
				invD2 := 1.0 / d2
				// invD := 1.0 / d
				LaplacianWts.Set(lnorm*invD2, idx)
				idx++
			}
		}
	}
}

//gosl:start

// Laplacian1D computes the 1D Laplacian across 2 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
func Laplacian1D(x, y, z, vidx, tidx int32, ctr float32) float32 {
	m1 := State.Value(int(z), int(y), int(x-1), int(vidx), int(tidx))
	p1 := State.Value(int(z), int(y), int(x+1), int(vidx), int(tidx))
	return (m1 + p1) - 2*ctr
}

// Laplacian26 computes the 3D Laplacian across 26 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
func Laplacian26(x, y, z, vidx, tidx int32, ctr float32) float32 {
	avg := float32(0)
	for j := range 26 {
		xo := NeighOffs.Value(int(j), int(math32.X))
		yo := NeighOffs.Value(int(j), int(math32.Y))
		zo := NeighOffs.Value(int(j), int(math32.Z))
		nv := State.Value(int(z+zo), int(y+yo), int(x+xo), int(vidx), int(tidx))
		avg += LaplacianWts.Value(j) * (nv - ctr)
	}
	return avg
}

// PotentialEnergy1D computes the 1D potential energy across 2 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
func PotentialEnergy1D(x, y, z, vidx, tidx int32, ctr float32) float32 {
	m1 := State.Value(int(z), int(y), int(x-1), int(vidx), int(tidx))
	p1 := State.Value(int(z), int(y), int(x+1), int(vidx), int(tidx))
	pm1d := m1 - ctr
	pp1d := p1 - ctr
	return 0.5 * (pm1d*pm1d + pp1d*pp1d)
}

// PotentialEnergy26 computes the 3D potential energy across 26 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
func PotentialEnergy26(x, y, z, vidx, tidx int32, ctr float32) float32 {
	avg := float32(0)
	for j := range 26 {
		xo := NeighOffs.Value(int(j), int(math32.X))
		yo := NeighOffs.Value(int(j), int(math32.Y))
		zo := NeighOffs.Value(int(j), int(math32.Z))
		nv := State.Value(int(z+zo), int(y+yo), int(x+xo), int(vidx), int(tidx))
		dv := (nv - ctr)
		avg += LaplacianWts.Value(j) * dv * dv
	}
	return avg
}

//gosl:end
