// Code generated by "goal build"; DO NOT EDIT.
//line funcs.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import (
	// "fmt"

	"cogentcore.org/core/math32"
	"cogentcore.org/lab/tensor"
)

func (ss *Sim) ConfigVars() {
	if Params != nil {
		return
	}
	Params = make([]Parameters, 1)
	Params[0].Defaults()
	ss.Params = &Params[0]
	ss.Units.Defaults()
	Ctx = make([]Context, 1)
	Ctx[0].Init()
	NeighWts = tensor.NewFloat32(int(NeighWeightsN), 27)
	NeighOffs = tensor.NewInt32(26, 3)
	lnorm := float32(3.0 / 13.0)
	// sum := float32(0)
	idx := 0
	for z := -1; z <= 1; z++ {
		for y := -1; y <= 1; y++ {
			for x := -1; x <= 1; x++ {
				if x == 0 && y == 0 && z == 0 {
					continue
				}
				NeighOffs.Set(int32(x), int(idx), int(math32.X))
				NeighOffs.Set(int32(y), int(idx), int(math32.Y))
				NeighOffs.Set(int32(z), int(idx), int(math32.Z))

				v := math32.Vec3(float32(x), float32(y), float32(z))
				d2 := v.LengthSquared()
				invD2 := 1.0 / d2
				wt := lnorm * invD2
				NeighWts.Set(wt, int(LaplacianWts), int(idx))

				d := v.Length()
				invD := 1.0 / d
				// sum += invD
				NeighWts.Set(invD, int(AverageWts), int(idx))

				idx++
			}
		}
	}
	NeighWts.Set(1.0, int(AverageWts), int(idx))
	// sum += 1.0
	// fmt.Println("sum:", sum, "oneo:", 1.0 / sum)

	FaceOffs = tensor.NewInt32(3, 2, 9, 3)
	n := math32.Vec3i(-1, 0, 0)
	idx = 0
	sum := float32(0)
	for n.Z = -1; n.Z <= 1; n.Z++ {
		for n.Y = -1; n.Y <= 1; n.Y++ {
			FaceOffs.Set(n.X, int(math32.X), int(Minus1), int(idx), int(math32.X))
			FaceOffs.Set(n.Y, int(math32.X), int(Minus1), int(idx), int(math32.Y))
			FaceOffs.Set(n.Z, int(math32.X), int(Minus1), int(idx), int(math32.Z))
			o := n.MulScalar(-1)
			FaceOffs.Set(o.X, int(math32.X), int(Plus1), int(idx), int(math32.X))
			FaceOffs.Set(o.Y, int(math32.X), int(Plus1), int(idx), int(math32.Y))
			FaceOffs.Set(o.Z, int(math32.X), int(Plus1), int(idx), int(math32.Z))

			var v math32.Vector3
			v.SetFromVector3i(n)
			wt := 1.0 / v.Length()
			NeighWts.Set(wt, int(Grad18Wts), int(idx))
			sum += wt
			idx++
		}
	}
	n.Y = -1
	idx = 0
	for n.Z = -1; n.Z <= 1; n.Z++ {
		for n.X = -1; n.X <= 1; n.X++ {
			FaceOffs.Set(n.X, int(math32.Y), int(Minus1), int(idx), int(math32.X))
			FaceOffs.Set(n.Y, int(math32.Y), int(Minus1), int(idx), int(math32.Y))
			FaceOffs.Set(n.Z, int(math32.Y), int(Minus1), int(idx), int(math32.Z))
			o := n.MulScalar(-1)
			FaceOffs.Set(o.X, int(math32.Y), int(Plus1), int(idx), int(math32.X))
			FaceOffs.Set(o.Y, int(math32.Y), int(Plus1), int(idx), int(math32.Y))
			FaceOffs.Set(o.Z, int(math32.Y), int(Plus1), int(idx), int(math32.Z))
			idx++
		}
	}
	n.Z = -1
	idx = 0
	for n.Y = -1; n.Y <= 1; n.Y++ {
		for n.X = -1; n.X <= 1; n.X++ {
			FaceOffs.Set(n.X, int(math32.Z), int(Minus1), int(idx), int(math32.X))
			FaceOffs.Set(n.Y, int(math32.Z), int(Minus1), int(idx), int(math32.Y))
			FaceOffs.Set(n.Z, int(math32.Z), int(Minus1), int(idx), int(math32.Z))
			o := n.MulScalar(-1)
			FaceOffs.Set(o.X, int(math32.Z), int(Plus1), int(idx), int(math32.X))
			FaceOffs.Set(o.Y, int(math32.Z), int(Plus1), int(idx), int(math32.Y))
			FaceOffs.Set(o.Z, int(math32.Z), int(Plus1), int(idx), int(math32.Z))
			idx++
		}
	}
	sum *= 2
	for j := range 9 {
		NeighWts.SetDiv(sum, int(Grad18Wts), int(j))
	}
}

//gosl:start

// MinusPlusOne is minus1 and plus1
type MinusPlusOne int32 //enums:enum

const (
	Minus1 MinusPlusOne = iota
	Plus1
)

// NeighWeights
type NeighWeights int32 //enums:enum

const (
	// LaplacianWts are weighting factors for 3D Laplacian = 3 / (13 * d^2)
	LaplacianWts NeighWeights = iota

	// AverageWts are 26 + 1 ctr average weights = 1 / d
	AverageWts

	// Grad18Wts are 18 neighbor gradaients
	Grad18Wts
)

const (
	// Average27Sum is the sum of the AverageWts
	Average27Sum = float32(20.104084)

	// OneoAverage27Sum is 1.0/ sum of the AverageWts, for actual averaging
	OneoAverage27Sum = 0.049741138
)

// Laplacian1D computes the 1D Laplacian across 2 X dim neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
func Laplacian1D(x, y, z, vidx, tidx int32, ctr float32) float32 {
	m1 := State.Value(int(z), int(y), int(x-1), int(vidx), int(tidx))
	p1 := State.Value(int(z), int(y), int(x+1), int(vidx), int(tidx))
	return (m1 + p1) - 2*ctr
}

// Laplacian26 computes the 3D Laplacian across 26 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
func Laplacian26(x, y, z, vidx, tidx int32, ctr float32) float32 {
	avg := float32(0)
	for j := range 26 {
		xo := NeighOffs.Value(int(j), int(math32.X))
		yo := NeighOffs.Value(int(j), int(math32.Y))
		zo := NeighOffs.Value(int(j), int(math32.Z))
		nv := State.Value(int(z+zo), int(y+yo), int(x+xo), int(vidx), int(tidx))
		avg += NeighWts.Value(int(LaplacianWts), int(j)) * (nv - ctr)
	}
	return avg
}

// NeighAverage27 computes the 3D average across 27 neighbors,
// including the center, for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
func NeighAverage27(x, y, z, vidx, tidx int32) float32 {
	avg := float32(0)
	for j := range 26 {
		xo := NeighOffs.Value(int(j), int(math32.X))
		yo := NeighOffs.Value(int(j), int(math32.Y))
		zo := NeighOffs.Value(int(j), int(math32.Z))
		nv := State.Value(int(z+zo), int(y+yo), int(x+xo), int(vidx), int(tidx))
		avg += NeighWts.Value(int(AverageWts), int(j)) * nv
	}
	avg += NeighWts.Value(int(AverageWts), int(26)) * State.Value(int(z), int(y), int(x), int(vidx), int(tidx))
	return avg
}

// NeighMaxPosNeg computes the 3D max across 27 neighbors,
// including the center which gets abs mag, for given x,y,z center coordinates,
// variable index xPidx = posX, xNidx = negX, etc.
// and cur / prev time index tidx. ctr is the center value.
func NeighMaxPosNeg(x, y, z, pXidx, nXidx, pYidx, nYidx, pZidx, nZidx, tidx int32) float32 {
	mx := float32(0)
	mxabs := float32(0)
	for j := range 26 {
		xo := NeighOffs.Value(int(j), int(math32.X))
		yo := NeighOffs.Value(int(j), int(math32.Y))
		zo := NeighOffs.Value(int(j), int(math32.Z))
		wt := NeighWts.Value(int(AverageWts), int(j))
		var cx, cy, cz float32
		if xo < 0 {
			cx = wt * State.Value(int(z+zo), int(y+yo), int(x+xo), int(pXidx), int(tidx)) // to my left, get P
		} else if xo > 0 {
			cx = wt * State.Value(int(z+zo), int(y+yo), int(x+xo), int(nXidx), int(tidx)) // to my right, get N
		}
		if yo < 0 {
			cy = wt * State.Value(int(z+zo), int(y+yo), int(x+xo), int(pYidx), int(tidx))
		} else if yo > 0 {
			cy = wt * State.Value(int(z+zo), int(y+yo), int(x+xo), int(nYidx), int(tidx))
		}
		if zo < 0 {
			cz = wt * State.Value(int(z+zo), int(y+yo), int(x+xo), int(pZidx), int(tidx))
		} else if zo > 0 {
			cz = wt * State.Value(int(z+zo), int(y+yo), int(x+xo), int(nZidx), int(tidx))
		}
		acx := math32.Abs(cx)
		acy := math32.Abs(cy)
		acz := math32.Abs(cz)
		av := max(max(acx, acy), acz)
		if av > mxabs {
			mxabs = av
			if acx > acy && acx > acz {
				mx = cx
			} else if acy > acx && acy > acz {
				mx = cy
			} else {
				mx = cz
			}
		}
	}
	wt := NeighWts.Value(int(AverageWts), int(26))
	cxp := wt * State.Value(int(z), int(y), int(x), int(pXidx), int(tidx))
	cxn := wt * State.Value(int(z), int(y), int(x), int(nXidx), int(tidx))
	cyp := wt * State.Value(int(z), int(y), int(x), int(pYidx), int(tidx))
	cyn := wt * State.Value(int(z), int(y), int(x), int(nYidx), int(tidx))
	czp := wt * State.Value(int(z), int(y), int(x), int(pZidx), int(tidx))
	czn := wt * State.Value(int(z), int(y), int(x), int(nZidx), int(tidx))
	acxp := math32.Abs(cxp)
	acxn := math32.Abs(cxn)
	acyp := math32.Abs(cyp)
	acyn := math32.Abs(cyn)
	aczp := math32.Abs(czp)
	aczn := math32.Abs(czn)

	mxx := max(acxp, acxn)
	mxy := max(acyp, acyn)
	mxz := max(aczp, aczn)

	if mxx > mxabs && mxx > mxy && mxx > mxz {
		if acxp > acxn {
			mx = cxp
		} else {
			mx = cxn
		}
	}
	if mxy > mxabs && mxy > mxx && mxy > mxz {
		if acyp > acyn {
			mx = cyp
		} else {
			mx = cyn
		}
	}
	if mxz > mxabs && mxz > mxx && mxz > mxy {
		if aczp > aczn {
			mx = czp
		} else {
			mx = czn
		}
	}
	return mx
}

// Gradient18 computes the 3D gradient across 18 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx.
func Gradient18(x, y, z, vidx, tidx int32, dx, dy, dz *float32) {
	for xyz := range 3 {
		sum := float32(0)
		for j := range 9 {
			xp := FaceOffs.Value(int(xyz), int(Plus1), int(j), int(math32.X))
			xm := FaceOffs.Value(int(xyz), int(Minus1), int(j), int(math32.X))
			yp := FaceOffs.Value(int(xyz), int(Plus1), int(j), int(math32.Y))
			ym := FaceOffs.Value(int(xyz), int(Minus1), int(j), int(math32.Y))
			zp := FaceOffs.Value(int(xyz), int(Plus1), int(j), int(math32.Z))
			zm := FaceOffs.Value(int(xyz), int(Minus1), int(j), int(math32.Z))
			grad := NeighWts.Value(int(Grad18Wts), int(j)) * (State.Value(int(z+zp), int(y+yp), int(x+xp), int(vidx), int(tidx)) - State.Value(int(z+zm), int(y+ym), int(x+xm), int(vidx), int(tidx)))
			sum += grad
		}
		switch xyz {
		case 0:
			*dx = sum
		case 1:
			*dy = sum
		case 2:
			*dz = sum
		default:
		}
	}
}

// Divergence18 computes the 3D divergence across 18 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. Div = sum of gradients.
func Divergence18(x, y, z, vidx, tidx int32, dx, dy, dz *float32) float32 {
	sum := float32(0)
	for xyz := range 3 {
		for j := range 9 {
			xp := FaceOffs.Value(int(xyz), int(Plus1), int(j), int(math32.X))
			xm := FaceOffs.Value(int(xyz), int(Minus1), int(j), int(math32.X))
			yp := FaceOffs.Value(int(xyz), int(Plus1), int(j), int(math32.Y))
			ym := FaceOffs.Value(int(xyz), int(Minus1), int(j), int(math32.Y))
			zp := FaceOffs.Value(int(xyz), int(Plus1), int(j), int(math32.Z))
			zm := FaceOffs.Value(int(xyz), int(Minus1), int(j), int(math32.Z))
			grad := NeighWts.Value(int(Grad18Wts), int(j)) * (State.Value(int(z+zp), int(y+yp), int(x+xp), int(vidx), int(tidx)) - State.Value(int(z+zm), int(y+ym), int(x+xm), int(vidx), int(tidx)))
			sum += grad
		}
	}
	return sum
}

// Curl18 computes the 3D curl across 18 neighbors on a field vector,
// for given x,y,z center coordinates, variable index vidx (to X component),
// and cur / prev time index tidx.
func Curl18(x, y, z, vidx, tidx int32, cx, cy, cz *float32) {
	var dzdy, dydz, dxdz, dzdx, dydx, dxdy float32
	dimX := vidx + int32(math32.X)
	dimY := vidx + int32(math32.Y)
	dimZ := vidx + int32(math32.Z)
	for j := range 9 {
		xpX := FaceOffs.Value(int(math32.X), int(Plus1), int(j), int(math32.X))
		xmX := FaceOffs.Value(int(math32.X), int(Minus1), int(j), int(math32.X))
		ypX := FaceOffs.Value(int(math32.X), int(Plus1), int(j), int(math32.Y))
		ymX := FaceOffs.Value(int(math32.X), int(Minus1), int(j), int(math32.Y))
		zpX := FaceOffs.Value(int(math32.X), int(Plus1), int(j), int(math32.Z))
		zmX := FaceOffs.Value(int(math32.X), int(Minus1), int(j), int(math32.Z))

		xpY := FaceOffs.Value(int(math32.Y), int(Plus1), int(j), int(math32.X))
		xmY := FaceOffs.Value(int(math32.Y), int(Minus1), int(j), int(math32.X))
		ypY := FaceOffs.Value(int(math32.Y), int(Plus1), int(j), int(math32.Y))
		ymY := FaceOffs.Value(int(math32.Y), int(Minus1), int(j), int(math32.Y))
		zpY := FaceOffs.Value(int(math32.Y), int(Plus1), int(j), int(math32.Z))
		zmY := FaceOffs.Value(int(math32.Y), int(Minus1), int(j), int(math32.Z))

		xpZ := FaceOffs.Value(int(math32.Z), int(Plus1), int(j), int(math32.X))
		xmZ := FaceOffs.Value(int(math32.Z), int(Minus1), int(j), int(math32.X))
		ypZ := FaceOffs.Value(int(math32.Z), int(Plus1), int(j), int(math32.Y))
		ymZ := FaceOffs.Value(int(math32.Z), int(Minus1), int(j), int(math32.Y))
		zpZ := FaceOffs.Value(int(math32.Z), int(Plus1), int(j), int(math32.Z))
		zmZ := FaceOffs.Value(int(math32.Z), int(Minus1), int(j), int(math32.Z))

		dzdy += NeighWts.Value(int(Grad18Wts), int(j)) * (State.Value(int(z+zpY), int(y+ypY), int(x+xpY), int(dimZ), int(tidx)) - State.Value(int(z+zmY), int(y+ymY), int(x+xmY), int(dimZ), int(tidx)))
		dydz += NeighWts.Value(int(Grad18Wts), int(j)) * (State.Value(int(z+zpZ), int(y+ypZ), int(x+xpZ), int(dimY), int(tidx)) - State.Value(int(z+zmZ), int(y+ymZ), int(x+xmZ), int(dimY), int(tidx)))

		dxdz += NeighWts.Value(int(Grad18Wts), int(j)) * (State.Value(int(z+zpZ), int(y+ypZ), int(x+xpZ), int(dimX), int(tidx)) - State.Value(int(z+zmZ), int(y+ymZ), int(x+xmZ), int(dimX), int(tidx)))
		dzdx += NeighWts.Value(int(Grad18Wts), int(j)) * (State.Value(int(z+zpX), int(y+ypX), int(x+xpX), int(dimZ), int(tidx)) - State.Value(int(z+zmX), int(y+ymX), int(x+xmX), int(dimZ), int(tidx)))

		dydx += NeighWts.Value(int(Grad18Wts), int(j)) * (State.Value(int(z+zpX), int(y+ypX), int(x+xpX), int(dimY), int(tidx)) - State.Value(int(z+zmX), int(y+ymX), int(x+xmX), int(dimY), int(tidx)))
		dxdy += NeighWts.Value(int(Grad18Wts), int(j)) * (State.Value(int(z+zpY), int(y+ypY), int(x+xpY), int(dimX), int(tidx)) - State.Value(int(z+zmY), int(y+ymY), int(x+xmY), int(dimX), int(tidx)))
	}
	*cx = dzdy - dydz
	*cy = dxdz - dzdx
	*cz = dydx - dxdy
}

//////// Edges

// EdgeInBounds1 returns true if given coordinate is >= 1 and < s.
func EdgeInBounds1(x, y, z, sx, sy, sz int32) bool {
	return x >= 1 && x < sx && y >= 1 && y < sy && z >= 1 && z < sz
}

// EdgeInBounds0 returns true if given coordinate is >= 0 and <= s.
func EdgeInBounds0(x, y, z, sx, sy, sz int32) bool {
	return x >= 0 && x <= sx && y >= 0 && y <= sy && z >= 0 && z <= sz
}

// LaplacianEdge1D computes the 1D Laplacian across 2 X dim neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
// For computation at the edge, checks against given full size bounds.
func LaplacianEdge1D(x, y, z, sx, sy, sz, vidx, tidx int32, ctr float32) float32 {
	sum := float32(0)
	if EdgeInBounds1(x-1, y, z, sx, sy, sz) {
		sum += State.Value(int(z), int(y), int(x-1), int(vidx), int(tidx)) - ctr
	}
	if EdgeInBounds1(x+1, y, z, sx, sy, sz) {
		sum += State.Value(int(z), int(y), int(x+1), int(vidx), int(tidx)) - ctr
	}
	return sum
}

// LaplacianEdge26 computes the 3D Laplacian across 26 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
// For computation at the edge, checks against given full size bounds.
func LaplacianEdge26(x, y, z, sx, sy, sz, vidx, tidx int32, ctr float32) float32 {
	avg := float32(0)
	for j := range 26 {
		xo := NeighOffs.Value(int(j), int(math32.X))
		yo := NeighOffs.Value(int(j), int(math32.Y))
		zo := NeighOffs.Value(int(j), int(math32.Z))
		if EdgeInBounds1(x+xo, y+yo, z+zo, sx, sy, sz) {
			nv := State.Value(int(z+zo), int(y+yo), int(x+xo), int(vidx), int(tidx))
			avg += NeighWts.Value(int(LaplacianWts), int(j)) * (nv - ctr)
		}
	}
	return avg
}

// PotentialEnergy1D computes the 1D potential energy across 2 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
func PotentialEnergy1D(x, y, z, vidx, tidx int32, ctr float32) float32 {
	m1 := State.Value(int(z), int(y), int(x-1), int(vidx), int(tidx))
	p1 := State.Value(int(z), int(y), int(x+1), int(vidx), int(tidx))
	pm1d := m1 - ctr
	pp1d := p1 - ctr
	return 0.5 * (pm1d*pm1d + pp1d*pp1d)
}

// PotentialEnergy26 computes the 3D potential energy across 26 neighbors,
// for given x,y,z center coordinates, variable index vidx,
// and cur / prev time index tidx. ctr is the center value.
func PotentialEnergy26(x, y, z, vidx, tidx int32, ctr float32) float32 {
	avg := float32(0)
	for j := range 26 {
		xo := NeighOffs.Value(int(j), int(math32.X))
		yo := NeighOffs.Value(int(j), int(math32.Y))
		zo := NeighOffs.Value(int(j), int(math32.Z))
		nv := State.Value(int(z+zo), int(y+yo), int(x+xo), int(vidx), int(tidx))
		dv := (nv - ctr)
		avg += NeighWts.Value(int(LaplacianWts), int(j)) * dv * dv
	}
	return avg
}

//gosl:end
