// Code generated by "goal build"; DO NOT EDIT.
//line init.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import (
	"cogentcore.org/core/enums"
	"cogentcore.org/core/math32"
)

// CopyCurToPrev copies the current values to previous values
// for all variables.
func (ss *Sim) CopyCurToPrev() {
	vals := ss.StateVars.Values()
	ctx := GetCtx(0)
	cur := ctx.CurState
	prv := ctx.PrevState()
	sz := ss.Config.Size
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				for vi := range vals {
					State.Set(State.Value(int(f.Z), int(f.Y), int(f.X), int(vi), int(cur)), int(f.Z), int(f.Y), int(f.X), int(vi), int(prv))
				}
			}
		}
	}
}

// Sine adds sine wave values along given dimension, to given variable.
func (ss *Sim) Sine(vr enums.Enum, dim math32.Dims, period, phase, amp, off float32) {
	vri := int(vr.Int64())
	ctx := GetCtx(0)
	cur := ctx.CurState
	sz := ss.Config.Size
	tp := float32(2.0 * math32.Pi)
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				dv := float32(c.Dim(dim))
				v := off + amp*math32.Sin(tp*((dv+phase)/period))
				State.SetAdd(v, int(f.Z), int(f.Y), int(f.X), int(vri), int(cur))
			}
		}
	}
}

// MovingWavePacket adds moving wave packet along given dimension, to given variable.
func (ss *Sim) MovingWavePacket(vr enums.Enum, dim math32.Dims, ctr math32.Vector3i, dir, period, width, phase, amp float32) {
	vri := int(vr.Int64())
	ctx := GetCtx(0)
	cur := ctx.CurState
	prv := ctx.PrevState()
	ctrf := math32.Vec3(float32(ctr.X), float32(ctr.Y), float32(ctr.Z))
	var diroff math32.Vector3
	diroff.SetDim(dim, dir*ss.Params.C)
	sz := ss.Config.Size
	tp := float32(2.0 * math32.Pi)
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				ff := math32.Vec3(float32(f.X), float32(f.Y), float32(f.Z))
				d := ff.Sub(ctrf)
				dv := float32(d.Dim(dim))
				cos := amp * math32.Cos(tp*((dv/period)+phase))
				d.SetDivScalar(width)
				dist := d.Length()
				gauss := math32.FastExp(-dist * dist)
				cv := cos * gauss
				State.SetAdd(cv, int(f.Z), int(f.Y), int(f.X), int(vri), int(cur))

				ff.SetAdd(diroff)
				d = ff.Sub(ctrf)
				dv = float32(d.Dim(dim))
				cos = amp * math32.Cos(tp*((dv/period)+phase))
				d.SetDivScalar(width)
				dist = d.Length()
				gauss = math32.FastExp(-dist * dist)
				pv := cos * gauss
				State.SetAdd(pv, int(f.Z), int(f.Y), int(f.X), int(vri), int(prv))
			}
		}
	}
}
