// Code generated by "goal build"; DO NOT EDIT.
//line init.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import (
	"cogentcore.org/core/enums"
	"cogentcore.org/core/math32"
)

// CopyCurToPrev copies the current values to previous values
// for all variables.
func (ss *Sim) CopyCurToPrev() {
	vals := ss.StateVars.Values()
	ctx := GetCtx(0)
	cur := ctx.CurState
	prv := ctx.PrevState()
	sz := ss.Config.Size
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				for vi := range vals {
					State.Set(State.Value(int(f.Z), int(f.Y), int(f.X), int(vi), int(cur)), int(f.Z), int(f.Y), int(f.X), int(vi), int(prv))
				}
			}
		}
	}
}

// Sine adds sine wave values along given dimension, to given variable.
func (ss *Sim) Sine(vr enums.Enum, dim math32.Dims, period, phase, amp, off float32) {
	vri := int(vr.Int64())
	ctx := GetCtx(0)
	cur := ctx.CurState
	sz := ss.Config.Size
	tp := float32(2.0 * math32.Pi)
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				dv := float32(c.Dim(dim))
				v := off + amp*math32.Sin(tp*((dv+phase)/period))
				State.SetAdd(v, int(f.Z), int(f.Y), int(f.X), int(vri), int(cur))
			}
		}
	}
}
