// Code generated by "goal build"; DO NOT EDIT.
//line klein-gordon.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import "cogentcore.org/core/math32"

//gosl:start

// CabStates are the state variables for wave equations on
// a wave state with a single complex value,
// where A = real and B = complex components.
//
// Based on [EMStates] so the complex KG wave can be coupled to the
// electromagnetic field: the A0 / A potentials it is pushed by, and the
// Charge / Current it drives them with, are the same variables MaxwellKernel
// uses. Params.EM switches the coupling on.
type CabStates EMStates //enums:enum -trim-prefix=Cab

const (
	// CabAs is the wave state variable for component A: real.
	CabAs CabStates = CabStates(EMStatesN) + iota

	// CabBs is the wave state variable for component B: imaginary.
	CabBs

	// CabAv is the velocity of wave state variable A.
	CabAv

	// CabBv is the velocity of wave state variable B.
	CabBv

	// CabV is an external potential energy factor, that
	// can be used to push particles around.
	CabV

	// CabMag is the state magnitude (state * complex conjugate),
	// which represents the total probability or a conserved
	// charge value.
	CabMag
)

// KleinGordonKernel is the kernel for computing the KleinGordon equations,
// on scalar state values (WaveStates).
func KleinGordonKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	ppos := State.Value(int(z), int(y), int(x), int(WavePos), int(prv))
	pvel := State.Value(int(z), int(y), int(x), int(WaveVel), int(prv))
	vpot := State.Value(int(z), int(y), int(x), int(WaveV), int(prv))

	mhsq := Params[0].MOverHSq
	csq := Params[0].CSq

	var force float32
	if Params[0].ThreeD.IsTrue() {
		force = Laplacian19(x, y, z, int32(WavePos), prv, ppos)
	} else {
		force = Laplacian1D(x, y, z, int32(WavePos), prv, ppos)
	}
	force += (vpot - mhsq) * ppos // this is the only diff from standard Wave
	vel := pvel + csq*force
	pos := ppos + vel

	if Params[0].Energy.IsTrue() {
		midVel := 0.5 * (pvel + vel)
		kinetic := Params[0].Inv2CSq * midVel * midVel
		var potential float32
		if Params[0].ThreeD.IsTrue() {
			potential = PotentialEnergy19(x, y, z, int32(WavePos), prv, ppos)
		} else {
			potential = PotentialEnergy1D(x, y, z, int32(WavePos), prv, ppos)
		}

		State.Set(kinetic, int(z), int(y), int(x), int(WaveKinetic), int(cur))
		State.Set(potential, int(z), int(y), int(x), int(WavePotential), int(cur))
		State.Set(kinetic+potential, int(z), int(y), int(x), int(WaveEnergy), int(cur))
	}
	State.Set(force, int(z), int(y), int(x), int(WaveForce), int(cur))
	State.Set(vel, int(z), int(y), int(x), int(WaveVel), int(cur))
	State.Set(pos, int(z), int(y), int(x), int(WavePos), int(cur))
}

// KleinGordonCKernel is the kernel for the complex Klein-Gordon equation, with
// optional minimal coupling to the electromagnetic field (Params.EM).
//
// Uncoupled, the two components evolve as two independent real KG waves: the
// complex structure only shows up in the conserved charge, which needs both.
//
// Coupled, the covariant derivative D = d - i(e/hbar)A adds three terms:
//
//	dd(phi_a) = c^2 (Lap - mhsq) phi_a + (2e/hbar)(A0 d(phi_b) + c A.grad phi_b) + (e^2/hbar^2)(A0^2 - A^2) phi_a
//	dd(phi_b) = c^2 (Lap - mhsq) phi_b - (2e/hbar)(A0 d(phi_a) + c A.grad phi_a) + (e^2/hbar^2)(A0^2 - A^2) phi_b
//
// The A0 term acts on the VELOCITY with opposite signs on the two components,
// which is a rotation of (d phi_a, d phi_b) at rate 2 e A0 / hbar. An explicit
// integrator does not rotate, it spirals, and the charge runs away -- which is
// the instability described in web/content/complex-kg.md. Params.Boris applies
// the rotation exactly instead. See EWBorisPhase for the same problem in the
// electroweak kernel.
//
// It also writes the [Charge] and [Current] that MaxwellKernel reads, so the
// wave and the field drive each other.
func KleinGordonCKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	pposA := State.Value(int(z), int(y), int(x), int(CabAs), int(prv))
	pposB := State.Value(int(z), int(y), int(x), int(CabBs), int(prv))
	pvelA := State.Value(int(z), int(y), int(x), int(CabAv), int(prv))
	pvelB := State.Value(int(z), int(y), int(x), int(CabBv), int(prv))
	vpot := State.Value(int(z), int(y), int(x), int(CabV), int(prv))

	mhsq := Params[0].MOverHSq
	csq := Params[0].CSq
	threeD := Params[0].ThreeD.IsTrue()

	var forceA, forceB float32
	if threeD {
		forceA = Laplacian19(x, y, z, int32(CabAs), prv, pposA)
		forceB = Laplacian19(x, y, z, int32(CabBs), prv, pposB)
	} else {
		forceA = Laplacian1D(x, y, z, int32(CabAs), prv, pposA)
		forceB = Laplacian1D(x, y, z, int32(CabBs), prv, pposB)
	}
	forceA += (vpot - mhsq) * pposA // this is the only diff from standard Wave
	forceB += (vpot - mhsq) * pposB
	accA := csq * forceA
	accB := csq * forceB

	// needed for the current in any case, and for the A.grad term when coupled
	var gA, gB math32.Vector3
	if threeD {
		gA = Gradient10(x, y, z, int32(CabAs), prv)
		gB = Gradient10(x, y, z, int32(CabBs), prv)
	} else {
		gA = Gradient1D(x, y, z, int32(CabAs), prv)
		gB = Gradient1D(x, y, z, int32(CabBs), prv)
	}

	em := Params[0].EM.IsTrue()
	var a0, ax, ay, az, omega float32
	if em {
		a0 = State.Value(int(z), int(y), int(x), int(A0s), int(prv))
		ax = State.Value(int(z), int(y), int(x), int(AXs), int(prv))
		ay = State.Value(int(z), int(y), int(x), int(AYs), int(prv))
		az = State.Value(int(z), int(y), int(x), int(AZs), int(prv))
		e2h := Params[0].E2OverH
		cc := Params[0].C
		asq := a0*a0 - (ax*ax + ay*ay + az*az)
		eh2 := Params[0].EOverHSq * asq
		accA += e2h*cc*(ax*gB.X+ay*gB.Y+az*gB.Z) + eh2*pposA
		accB += -e2h*cc*(ax*gA.X+ay*gA.Y+az*gA.Z) + eh2*pposB
		omega = e2h * a0 // the A0 rotation rate
	}

	var velA, velB float32
	if em && Params[0].Boris.IsTrue() {
		// half kick, exact rotation, half kick. d(v_a + i v_b)/dt =
		// -i omega (v_a + i v_b), so the velocity turns by -omega per step.
		haA := 0.5 * accA
		haB := 0.5 * accB
		mA := pvelA + haA
		mB := pvelB + haB
		cs := math32.Cos(omega)
		sn := math32.Sin(omega)
		velA = cs*mA + sn*mB + haA
		velB = -sn*mA + cs*mB + haB
	} else {
		velA = pvelA + accA + omega*pvelB
		velB = pvelB + accB - omega*pvelA
	}
	posA := pposA + velA
	posB := pposB + velB

	// charge and current, at the same time as the position they use: the
	// midpoint velocity is the one that belongs with the previous position in
	// a leapfrog, and the gradients are of the previous position too.
	midA := 0.5 * (pvelA + velA)
	midB := 0.5 * (pvelB + velB)
	ccm := pposA*pposA + pposB*pposB
	hem := Params[0].HEOverMCSq // hbar e / (m c^2)
	rho := hem * (pposB*midA - pposA*midB)
	if em {
		rho -= Params[0].EsqOverMCSq * a0 * ccm
	}
	jf := hem * csq // hbar e / m
	jx := jf * (pposA*gB.X - pposB*gA.X)
	jy := jf * (pposA*gB.Y - pposB*gA.Y)
	jz := jf * (pposA*gB.Z - pposB*gA.Z)
	if em {
		ja := Params[0].EsqOverMCSq * Params[0].C * ccm
		jx -= ja * ax
		jy -= ja * ay
		jz -= ja * az
	}
	State.Set(rho, int(z), int(y), int(x), int(Charge), int(cur))
	State.Set(jx, int(z), int(y), int(x), int(CurrentX), int(cur))
	State.Set(jy, int(z), int(y), int(x), int(CurrentY), int(cur))
	State.Set(jz, int(z), int(y), int(x), int(CurrentZ), int(cur))

	// ccm, not the new position: Charge, Current and Mag are all diagnostics
	// of the same instant, the one the midpoint velocity belongs to. Reading
	// Mag a step later than Charge breaks rho = -e |chi|^2 by the amount the
	// Laplacian moves |chi|^2 in one step.
	State.Set(ccm, int(z), int(y), int(x), int(CabMag), int(cur))
	State.Set(velA, int(z), int(y), int(x), int(CabAv), int(cur))
	State.Set(posA, int(z), int(y), int(x), int(CabAs), int(cur))

	State.Set(velB, int(z), int(y), int(x), int(CabBv), int(cur))
	State.Set(posB, int(z), int(y), int(x), int(CabBs), int(cur))
}

// KleinGordonDampKernel is the kernel for computing the KleinGordon equations,
// on scalar state values (WaveStates),
// at damped edges. Does Sommerfield damping where velocity = force.
func KleinGordonDampKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	face := ctx.EdgeCoords(i, &x, &y, &z)
	if face < 0 {
		return
	}
	sz := ctx.SizePlus1() // exclude updating on edges
	cur := ctx.CurState
	prv := ctx.PrevState()
	ppos := State.Value(int(z), int(y), int(x), int(WavePos), int(prv))

	mhsq := Params[0].MOverHSq
	csq := Params[0].CSq

	var force float32
	if Params[0].ThreeD.IsTrue() {
		force = LaplacianEdge19(x, y, z, sz.X, sz.Y, sz.Z, int32(WavePos), prv, ppos)
	} else {
		force = LaplacianEdge1D(x, y, z, sz.X, sz.Y, sz.Z, int32(WavePos), prv, ppos)
	}
	force -= mhsq * ppos // this is the only diff from standard Wave
	vel := csq * force   // key damp: no +=
	pos := ppos + vel

	State.Set(force, int(z), int(y), int(x), int(WaveForce), int(cur))
	State.Set(vel, int(z), int(y), int(x), int(WaveVel), int(cur))
	State.Set(pos, int(z), int(y), int(x), int(WavePos), int(cur))
}

// KleinGordonCDampKernel is the kernel for computing the KleinGordonC equations,
// on complex wave state,
// at damped edges. Does Sommerfield damping where velocity = force.
func KleinGordonCDampKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	face := ctx.EdgeCoords(i, &x, &y, &z)
	if face < 0 {
		return
	}
	sz := ctx.SizePlus1() // exclude updating on edges
	cur := ctx.CurState
	prv := ctx.PrevState()
	pposA := State.Value(int(z), int(y), int(x), int(CabAs), int(prv))
	pposB := State.Value(int(z), int(y), int(x), int(CabBs), int(prv))

	// mhsq := Params[0].MOverHSq
	csq := Params[0].CSq

	var forceA, forceB float32
	if Params[0].ThreeD.IsTrue() {
		forceA = LaplacianEdge19(x, y, z, sz.X, sz.Y, sz.Z, int32(CabAs), prv, pposA)
		forceB = LaplacianEdge19(x, y, z, sz.X, sz.Y, sz.Z, int32(CabBs), prv, pposB)
	} else {
		forceA = LaplacianEdge1D(x, y, z, sz.X, sz.Y, sz.Z, int32(CabAs), prv, pposA)
		forceB = LaplacianEdge1D(x, y, z, sz.X, sz.Y, sz.Z, int32(CabBs), prv, pposB)
	}
	// forceA -= mhsq * pposA // this is the only diff from standard Wave
	velA := csq * forceA
	posA := pposA + velA

	// forceB -= mhsq * pposB // this is the only diff from standard Wave
	velB := csq * forceB
	posB := pposB + velB

	State.Set(velA, int(z), int(y), int(x), int(CabAv), int(cur))
	State.Set(posA, int(z), int(y), int(x), int(CabAs), int(cur))

	State.Set(velB, int(z), int(y), int(x), int(CabBv), int(cur))
	State.Set(posB, int(z), int(y), int(x), int(CabBs), int(cur))
}

//gosl:end

func (ss *Sim) KleinGordonConfig() {
	ParamsShouldDisplay = KGShouldDisplay
	ss.StateVars = WaveStatesN
	ss.WaveStats()
	ss.ViewInit(func(view *View) {
		view.SetVar(WavePos, -1)
	})
}

func (ss *Sim) KleinGordonCConfig() {
	ParamsShouldDisplay = KGCShouldDisplay
	ss.Params.Edges = EdgesWrap
	ss.StateVars = CabStatesN
	ss.initFuncs = KGCConfigs
	ss.InitFunc = ChargeAtRest
	ss.KleinGordonCStats()
	ss.ViewInit(func(view *View) {
		view.SetVar(CabAs, -1)
	})
}

//////// configurations

// ChargeAtRest is a gaussian lump of charge sitting still: a particle, as far
// as this equation has one.
//
// The two components a quarter cycle apart are a complex number turning at the
// rest mass frequency Omega0 = m c^2 / hbar, and that turning IS the charge:
//
//	rho = (hbar e / m c^2) (phi_b d phi_a - phi_a d phi_b) = -e |chi|^2
//
// exactly, at every cell. Watch the total charge stat while the blob spreads:
// a lump at rest is a spread of momenta, so it disperses as any massive wave
// packet must, and the charge is conserved through all of it while |chi|^2
// moves around. No single real field has a quantity like that, which is the
// reason for going complex in the first place.
//
// Reverse the sense of rotation and the charge changes sign, with nothing else
// about the wave any different. That is antimatter, in the only sense this
// equation knows about it.
func ChargeAtRest(ss *Sim) {
	ss.ChargedBlob(math32.Vec3(-1, -1, -1), ss.Config.PacketWidth, ss.Config.Amplitude, 1)
}

// ChargeAtRestAnti is [ChargeAtRest] turning the other way: the same wave with
// the opposite charge.
func ChargeAtRestAnti(ss *Sim) {
	ss.ChargedBlob(math32.Vec3(-1, -1, -1), ss.Config.PacketWidth, ss.Config.Amplitude, -1)
}

// ChargeUniform fills all of space with charge at rest: flat and dull to look
// at, but rho is then exactly constant in space and time, which makes it the
// clean case for checking the charge against its analytic value.
func ChargeUniform(ss *Sim) {
	ss.ChargedUniform(ss.Config.Amplitude, 1)
}

// kgSelfScale sets Mu0 so the potential a charge blob makes for itself is the
// given fraction of its own rest energy.
//
// A gaussian charge density of peak rho0 = e amp^2 and width w sits at the
// centre of its own potential
//
//	A0(0) = Mu0 rho0 w^2 / 2
//
// and the coupling only means anything while e A0 is well under m c^2. Past
// that the potential exceeds the rest energy, which is the Klein regime: the
// single-particle equation stops describing one particle and the numbers stop
// making sense soon after.
//
// At the defaults that bound is tight. m c^2 = 0.031 while Mu0 = e = 1 and a
// blob of amp 0.05 and width 12 reaches e A0 = m c^2 within five steps. There
// is no amplitude that is both visible and stable, because rho goes as amp^2
// while the display range does not -- Mu0 is the knob, not the amplitude.
// Reducing it is not a fudge: the real coupling is weak too, which is what the
// fine structure constant being 1/137 says.
func kgSelfScale(ss *Sim, frac float32) {
	p := ss.Params
	a := ss.Config.Amplitude
	w := ss.Config.PacketWidth
	p.Mu0 = 2 * frac * (p.Omega0 * p.Hbar) / (p.E * p.E * a * a * w * w)
	p.Update()
}

// ChargeSelfField is [ChargeAtRest] with the back-reaction on: the charge
// makes its own electromagnetic potential, and is pushed by it.
//
// Mu0 is set from [kgSelfScale] so the self-potential is a twentieth of the
// rest energy, which is the regime where this is a charge with a field rather
// than a numerical accident. Raise the fraction and it goes sooner.
//
// Edges are damped, not wrapped. A net charge in a periodic box has no
// solution to Poisson's equation at all -- every copy of the box adds another
// charge -- so A0 climbs without bound and takes the run with it eventually,
// however small the amplitude.
//
// The blob is not bound and is not supposed to be: like charge repels itself,
// so it spreads faster than free dispersion alone and eventually leaves
// through the walls, taking its charge with it. There is nothing in this
// equation that could hold a charge together, which is a real feature of it
// rather than a limitation of the simulation.
func ChargeSelfField(ss *Sim) {
	ss.Params.EM.SetBool(true)
	ss.Params.Edges = EdgesDamp
	kgSelfScale(ss, 0.05)
	ChargeAtRest(ss)
}

// ChargedPacket is a moving charge: a wave packet in the two components a
// quarter wavelength apart, travelling along X.
func ChargedPacket(ss *Sim) {
	ss.ChargedPacketConfig(math32.X, ss.Config.Amplitude, 1)
}

// KGCConfigs are the initialization options offered in the GUI.
var KGCConfigs = []InitFunc{
	InitFunc{Name: "Charge At Rest", Doc: "A gaussian lump of charge at rest: rho = -e |chi|^2 exactly, conserved as the lump disperses", Func: ChargeAtRest, Current: true},
	InitFunc{Name: "Charge At Rest Anti", Doc: "The same lump turning the other way, which is the same thing with the opposite charge", Func: ChargeAtRestAnti},
	InitFunc{Name: "Charge Uniform", Doc: "Charge at rest filling all of space: flat, but rho is then exactly constant and equal to -e |chi|^2", Func: ChargeUniform},
	InitFunc{Name: "Charge Self Field", Doc: "The charge makes its own potential and is pushed back by it: Mu0 is scaled so the self-field is a twentieth of the rest energy, which is the only regime where this is stable", Func: ChargeSelfField},
	InitFunc{Name: "Charged Packet", Doc: "A moving charge: a complex wave packet travelling along X, carrying charge and current", Func: ChargedPacket},
}

// KGCConfigs stats plotted over time in the GUI.
func (ss *Sim) KleinGordonCStats() {
	ss.AddStat(ss.StatStep())
	ss.AddStat(ss.StatSum(Charge))
	ss.AddStat(ss.StatSum(CabMag))
	ss.AddStat(ss.StatGroupVel(math32.X, CabAs))
}

// KGShouldDisplay determines which Parameters fields to display.
var KGShouldDisplay = []string{"Edges", "Energy", "C", "Hbar", "Mass", "Wavelength", "PacketWidth"}

// KGCShouldDisplay determines which Parameters fields to display for the
// complex, optionally EM-coupled version.
var KGCShouldDisplay = []string{"Edges", "Energy", "C", "Hbar", "Mass", "E", "Mu0", "EM", "Boris", "A0NoWave", "Wavelength", "PacketWidth", "Amplitude"}
