// Code generated by "goal build"; DO NOT EDIT.
//line klein-gordon.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

//gosl:start

// CabStates are the state variables for wave equations on
// a wave state with a single complex value,
// where A = real and B = complex components.
type CabStates int32 //enums:enum -trim-prefix=Cab

const (
	// CabPosA is the position (height) wave state variable
	// for the real complex component A.
	CabPosA CabStates = iota

	// CabPosB is the position (height) wave state variable
	// for the imaginary complex component B.
	CabPosB

	// CabVelA is the velocity of wave state variable
	// for the real complex component A.
	CabVelA

	// CabVelB is the velocity of wave state variable
	// for the imaginary complex component B.
	CabVelB

	// CabForceA is the net force computed from neighbors
	// for the real complex component A.
	CabForceA

	// CabForceB is the net force computed from neighbors
	// for the imaginary complex component B.
	CabForceB

	// CabV is an external potential energy factor, that
	// can be used to push particles around.
	CabV

	// CabCC is the complex conjugate ("squared") wave
	// value, which represents the total probability or a conserved
	// charge value.
	CabCC

	// CabCharge is the charge density.
	CabCharge

	// CabCurrentX is the current density.
	CabCurrentX

	// CabCurrentY is the current density.
	CabCurrentY

	// CabCurrentZ is the current density.
	CabCurrentZ

	// CabKinetic is the total kinetic energy across components.
	CabKinetic

	// CabPotential is the total potential energy across components (only for KGC).
	CabPotential

	// CabEnergy is the total kinetic + potential energy.
	CabEnergy
)

// KleinGordonKernel is the kernel for computing the KleinGordon equations,
// on scalar state values (WaveStates).
func KleinGordonKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	ppos := State.Value(int(z), int(y), int(x), int(WavePos), int(prv))
	pvel := State.Value(int(z), int(y), int(x), int(WaveVel), int(prv))

	mhsq := Params[0].MOverHSq
	csq := Params[0].CSq

	var force float32
	if Params[0].ThreeD.IsTrue() {
		force = Laplacian26(x, y, z, int32(WavePos), prv, ppos)
	} else {
		force = Laplacian1D(x, y, z, int32(WavePos), prv, ppos)
	}
	force -= mhsq * ppos // this is the only diff from standard Wave
	vel := pvel + csq*force
	pos := ppos + vel

	if Params[0].Energy.IsTrue() {
		midVel := 0.5 * (pvel + vel)
		kinetic := Params[0].Inv2CSq * midVel * midVel
		var potential float32
		if Params[0].ThreeD.IsTrue() {
			potential = PotentialEnergy26(x, y, z, int32(WavePos), prv, ppos)
		} else {
			potential = PotentialEnergy1D(x, y, z, int32(WavePos), prv, ppos)
		}

		State.Set(kinetic, int(z), int(y), int(x), int(WaveKinetic), int(cur))
		State.Set(potential, int(z), int(y), int(x), int(WavePotential), int(cur))
		State.Set(kinetic+potential, int(z), int(y), int(x), int(WaveEnergy), int(cur))
	}
	State.Set(force, int(z), int(y), int(x), int(WaveForce), int(cur))
	State.Set(vel, int(z), int(y), int(x), int(WaveVel), int(cur))
	State.Set(pos, int(z), int(y), int(x), int(WavePos), int(cur))
}

// KleinGordonCKernel is the kernel for computing the KleinGordonC equations,
// on complex wave state.
func KleinGordonCKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	pposA := State.Value(int(z), int(y), int(x), int(CabPosA), int(prv))
	pposB := State.Value(int(z), int(y), int(x), int(CabPosB), int(prv))
	pvelA := State.Value(int(z), int(y), int(x), int(CabVelA), int(prv))
	pvelB := State.Value(int(z), int(y), int(x), int(CabVelB), int(prv))

	mhsq := Params[0].MOverHSq
	csq := Params[0].CSq

	var forceA, forceB float32
	if Params[0].ThreeD.IsTrue() {
		forceA = Laplacian26(x, y, z, int32(CabPosA), prv, pposA)
		forceB = Laplacian26(x, y, z, int32(CabPosB), prv, pposB)
	} else {
		forceA = Laplacian1D(x, y, z, int32(CabPosA), prv, pposA)
		forceB = Laplacian1D(x, y, z, int32(CabPosB), prv, pposB)
	}
	forceA -= mhsq * pposA // this is the only diff from standard Wave
	velA := pvelA + csq*forceA
	posA := pposA + velA

	forceB -= mhsq * pposB // this is the only diff from standard Wave
	velB := pvelB + csq*forceB
	posB := pposB + velB

	if Params[0].Energy.IsTrue() {
		cc := posA*posA + posB*posB
		midVel := 0.25 * (pvelA + velA + pvelB + velB)
		kinetic := Params[0].Inv2CSq * midVel * midVel
		var potential float32
		if Params[0].ThreeD.IsTrue() {
			potential = PotentialEnergy26(x, y, z, int32(CabPosA), prv, pposA) + PotentialEnergy26(x, y, z, int32(CabPosB), prv, pposB)
		} else {
			potential = PotentialEnergy1D(x, y, z, int32(CabPosA), prv, pposA) + PotentialEnergy1D(x, y, z, int32(CabPosB), prv, pposB)
		}

		State.Set(cc, int(z), int(y), int(x), int(CabCC), int(cur))
		State.Set(kinetic, int(z), int(y), int(x), int(CabKinetic), int(cur))
		State.Set(potential, int(z), int(y), int(x), int(CabPotential), int(cur))
		State.Set(kinetic+potential, int(z), int(y), int(x), int(CabEnergy), int(cur))
	}
	State.Set(forceA, int(z), int(y), int(x), int(CabForceA), int(cur))
	State.Set(velA, int(z), int(y), int(x), int(CabVelA), int(cur))
	State.Set(posA, int(z), int(y), int(x), int(CabPosA), int(cur))

	State.Set(forceB, int(z), int(y), int(x), int(CabForceB), int(cur))
	State.Set(velB, int(z), int(y), int(x), int(CabVelB), int(cur))
	State.Set(posB, int(z), int(y), int(x), int(CabPosB), int(cur))
}

// KleinGordonDampKernel is the kernel for computing the KleinGordon equations,
// on scalar state values (WaveStates),
// at damped edges. Does Sommerfield damping where velocity = force.
func KleinGordonDampKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	face := ctx.EdgeCoords(i, &x, &y, &z)
	if face < 0 {
		return
	}
	sz := ctx.SizePlus1() // exclude updating on edges
	cur := ctx.CurState
	prv := ctx.PrevState()
	ppos := State.Value(int(z), int(y), int(x), int(WavePos), int(prv))

	mhsq := Params[0].MOverHSq
	csq := Params[0].CSq

	var force float32
	if Params[0].ThreeD.IsTrue() {
		force = LaplacianEdge26(x, y, z, sz.X, sz.Y, sz.Z, int32(WavePos), prv, ppos)
	} else {
		force = LaplacianEdge1D(x, y, z, sz.X, sz.Y, sz.Z, int32(WavePos), prv, ppos)
	}
	force -= mhsq * ppos // this is the only diff from standard Wave
	vel := csq * force   // key damp: no +=
	pos := ppos + vel

	State.Set(force, int(z), int(y), int(x), int(WaveForce), int(cur))
	State.Set(vel, int(z), int(y), int(x), int(WaveVel), int(cur))
	State.Set(pos, int(z), int(y), int(x), int(WavePos), int(cur))
}

// KleinGordonCDampKernel is the kernel for computing the KleinGordonC equations,
// on complex wave state,
// at damped edges. Does Sommerfield damping where velocity = force.
func KleinGordonCDampKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	face := ctx.EdgeCoords(i, &x, &y, &z)
	if face < 0 {
		return
	}
	sz := ctx.SizePlus1() // exclude updating on edges
	cur := ctx.CurState
	prv := ctx.PrevState()
	pposA := State.Value(int(z), int(y), int(x), int(CabPosA), int(prv))
	pposB := State.Value(int(z), int(y), int(x), int(CabPosB), int(prv))

	mhsq := Params[0].MOverHSq
	csq := Params[0].CSq

	var forceA, forceB float32
	if Params[0].ThreeD.IsTrue() {
		forceA = LaplacianEdge26(x, y, z, sz.X, sz.Y, sz.Z, int32(CabPosA), prv, pposA)
		forceB = LaplacianEdge26(x, y, z, sz.X, sz.Y, sz.Z, int32(CabPosB), prv, pposB)
	} else {
		forceA = LaplacianEdge1D(x, y, z, sz.X, sz.Y, sz.Z, int32(CabPosA), prv, pposA)
		forceB = LaplacianEdge1D(x, y, z, sz.X, sz.Y, sz.Z, int32(CabPosB), prv, pposB)
	}
	forceA -= mhsq * pposA // this is the only diff from standard Wave
	velA := csq * forceA
	posA := pposA + velA

	forceB -= mhsq * pposB // this is the only diff from standard Wave
	velB := csq * forceB
	posB := pposB + velB

	State.Set(forceA, int(z), int(y), int(x), int(CabForceA), int(cur))
	State.Set(velA, int(z), int(y), int(x), int(CabVelA), int(cur))
	State.Set(posA, int(z), int(y), int(x), int(CabPosA), int(cur))

	State.Set(forceB, int(z), int(y), int(x), int(CabForceB), int(cur))
	State.Set(velB, int(z), int(y), int(x), int(CabVelB), int(cur))
	State.Set(posB, int(z), int(y), int(x), int(CabPosB), int(cur))
}

//gosl:end

func (ss *Sim) KleinGordonConfig() {
	ParamsShouldDisplay = KGShouldDisplay
	ss.StateVars = WaveStatesN
	ss.ViewInit(func(view *View) {
		view.SetVar(WavePos, -1)
	})
}

func (ss *Sim) KleinGordonCConfig() {
	ParamsShouldDisplay = KGShouldDisplay
	ss.StateVars = CabStatesN
	ss.ViewInit(func(view *View) {
		view.SetVar(CabPosA, -1)
	})
}

// KGShouldDisplay determines which Parameters fields to display.
var KGShouldDisplay = []string{"Edges", "Energy", "C", "Hbar", "Mass", "Wavelength", "PacketWidth"}
