// Code generated by "goal build"; DO NOT EDIT.
//line particle-kg.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import "cogentcore.org/core/math32"

//gosl:start

// ParticleKGCStates are the state variables for particles in context
// of KGC complex wave equations on a wave state with two complex values (1, 2),
// where A = real and B = complex components.
type ParticleKGCStates CabStates //enums:enum -trim-prefix=PKGC

const (
	// PKGCParticle indicates the type of particle present at this cell.
	// zero indicates no particle.
	PKGCParticle ParticleKGCStates = ParticleKGCStates(CabStatesN) + iota

	// PKGCPvelX is the particle velocity (proportion of c, [-1..1]) along X axis
	PKGCPvelX

	// PKGCPvelY is the particle velocity (proportion of c, [-1..1]) along Y axis
	PKGCPvelY

	// PKGCPvelZ is the particle velocity (proportion of c, [-1..1]) along Z axis
	PKGCPvelZ

	// PKGCPvelSq is the squared total particle velocity across all axes:
	// X^2 + Y^2 + Z^2
	PKGCPvelSq

	// PKGCLorentz is the Lorentz factor for particle: 1 / sqrt(1-v^2) (v = PvelSq)
	PKGCLorentz

	// PKGCPESq is the square of the particle energy.
	PKGCPESq

	// PKGCDriver is the particle driver field propagating by exponential falloff.
	PKGCDriver

	// PKGCHoP0 is the central time-like SHO position for particle velocity,
	// which provides the reference against which the 3 axis phases are computed.
	PKGCHoP0

	// PKGCHoV0 is the central time-like SHO velocity for particle velocity,
	// which provides the reference against which the 3 axis phases are computed.
	PKGCHoV0

	// PKGCHoPX is the SHO position for particle velocity along X axis,
	// with phase relative to central HoV0 driving normalized velocity value.
	PKGCHoPX

	// PKGCHoVX is the SHO velocity for particle velocity along X axis,
	// with phase relative to central HoV0 driving normalized velocity value.
	PKGCHoVX

	// PKGCHoPY is the SHO position for particle velocity along Y axis,
	// with phase relative to central HoV0 driving normalized velocity value.
	PKGCHoPY

	// PKGCHoVY is the SHO velocity for particle velocity along Y axis,
	// with phase relative to central HoV0 driving normalized velocity value.
	PKGCHoVY

	// PKGCHoPZ is the SHO position for particle velocity along Z axis,
	// with phase relative to central HoV0 driving normalized velocity value.
	PKGCHoPZ

	// PKGCHoVZ is the SHO velocity for particle velocity along Z axis,
	// with phase relative to central HoV0 driving normalized velocity value.
	PKGCHoVZ
)

// ParticleKGCKernel is the kernel for computing the stochastic particle
// with simple harmonic oscillator velocity and rest-mass factors along positive
// and negative directions for each axis, based on KG on complex wave state.
func ParticleKGCKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	pposA := State.Value(int(z), int(y), int(x), int(CabPosA), int(prv))
	pposB := State.Value(int(z), int(y), int(x), int(CabPosB), int(prv))
	pvelA := State.Value(int(z), int(y), int(x), int(CabVelA), int(prv))
	pvelB := State.Value(int(z), int(y), int(x), int(CabVelB), int(prv))

	csq := Params[0].CSq
	// mhsq := Params[0].MOverHSq

	var forceA, forceB float32
	if Params[0].ThreeD.IsTrue() {
		forceA = Laplacian26(x, y, z, int32(CabPosA), prv, pposA)
		forceB = Laplacian26(x, y, z, int32(CabPosB), prv, pposB)
	} else {
		forceA = Laplacian1D(x, y, z, int32(CabPosA), prv, pposA)
		forceB = Laplacian1D(x, y, z, int32(CabPosB), prv, pposB)
	}

	// note: with no weights, favors diagonal; with 1/d or 1/d^2 weights favors
	// the axes. need to synthesize values?
	diff := Params[0].Diff
	drv := NeighMax26(x, y, z, int32(PKGCDriver), prv, diff)
	odrv := diff * drv

	// todo: drive A and B out of phase based on particle charge!
	// probably only for neighbor of particle.
	forceA += odrv - pposA
	velA := pvelA + csq*forceA
	posA := pposA + velA

	forceB += odrv - pposB
	velB := pvelB + csq*forceB
	posB := pposB + velB

	// todo: later, based on particle..
	// var grAX, grAY, grAZ, grBX, grBY, grBZ float32
	// Gradient18(x, y, z, int32(CabPosA), prv, &grAX, &grAY, &grAZ)
	// Gradient18(x, y, z, int32(CabPosB), prv, &grBX, &grBY, &grBZ)
	//
	// chg := pposB*pvelA - pposA*pvelB
	//
	// curX := pposA*grBX - pposB*grAX
	// curY := pposA*grBY - pposB*grAY
	// curZ := pposA*grBZ - pposB*grAZ

	State.Set(forceA, int(z), int(y), int(x), int(CabForceA), int(cur))
	State.Set(velA, int(z), int(y), int(x), int(CabVelA), int(cur))
	State.Set(posA, int(z), int(y), int(x), int(CabPosA), int(cur))

	State.Set(forceB, int(z), int(y), int(x), int(CabForceB), int(cur))
	State.Set(velB, int(z), int(y), int(x), int(CabVelB), int(cur))
	State.Set(posB, int(z), int(y), int(x), int(CabPosB), int(cur))

	State.Set(odrv, int(z), int(y), int(x), int(PKGCDriver), int(cur))

	// State[z, y, x, CabCharge, cur] = chg
	// State[z, y, x, CabCurrentX, cur] = curX
	// State[z, y, x, CabCurrentY, cur] = curY
	// State[z, y, x, CabCurrentZ, cur] = curZ

	particle := State.Value(int(z), int(y), int(x), int(PKGCParticle), int(prv))
	if particle == 0 {
		return
	}

	esq := State.Value(int(z), int(y), int(x), int(PKGCPESq), int(prv))

	hoP0 := State.Value(int(z), int(y), int(x), int(PKGCHoP0), int(prv))
	hoV0 := State.Value(int(z), int(y), int(x), int(PKGCHoV0), int(prv))

	hoPX := State.Value(int(z), int(y), int(x), int(PKGCHoPX), int(prv))
	hoVX := State.Value(int(z), int(y), int(x), int(PKGCHoVX), int(prv))

	hoPY := State.Value(int(z), int(y), int(x), int(PKGCHoPY), int(prv))
	hoVY := State.Value(int(z), int(y), int(x), int(PKGCHoVY), int(prv))

	hoPZ := State.Value(int(z), int(y), int(x), int(PKGCHoPZ), int(prv))
	hoVZ := State.Value(int(z), int(y), int(x), int(PKGCHoVZ), int(prv))

	// note: esq will get larger than 1!

	hoV0 += -esq * hoP0
	hoP0 += hoV0

	hoVX += -esq * hoPX
	hoPX += hoVX

	hoVY += -esq * hoPY
	hoPY += hoVY

	hoVZ += -esq * hoPZ
	hoPZ += hoVZ

	// multiply by C to get back to non-normalized units
	// but it is still a bit strange.
	homc := Params[0].C * Params[0].HOverMC

	pvX := homc * (hoP0*hoVX - hoPX*hoV0)
	pvY := homc * (hoP0*hoVY - hoPY*hoV0)
	pvZ := homc * (hoP0*hoVZ - hoPZ*hoV0)

	pvSq := pvX*pvX + pvY*pvY + pvZ*pvZ
	lorenz := 1.0 / math32.Sqrt(1.0-(pvSq/csq))
	esq = Params[0].C6M2 / (csq - pvSq)

	// todo: is this e factor across all dimensions or only within each individual dimension?
	// Sciaretta21 does only within individual, but that doesn't seem correct.
	// Need to empirically measure in separate particle-only test simulation.
	e := 0.5 * (1.0 + pvSq)
	pXp := 0.5 * (e + pvX)
	pXn := 0.5 * (e - pvX)
	pYp := 0.5 * (e + pvY)
	pYn := 0.5 * (e - pvY)
	pZp := 0.5 * (e + pvZ)
	pZn := 0.5 * (e - pvZ)

	rndX := GetRandomNumber(i, ctx.RandCounter.Counter, 0)
	rndY := GetRandomNumber(i, ctx.RandCounter.Counter, 1)
	rndZ := GetRandomNumber(i, ctx.RandCounter.Counter, 2)

	mvX := int32(0)
	if rndX < pXp {
		mvX = 1
	} else if rndX < pXp+pXn {
		mvX = -1
	}
	mvY := int32(0)
	if rndY < pYp {
		mvY = 1
	} else if rndY < pYp+pYn {
		mvY = -1
	}
	mvZ := int32(0)
	if rndZ < pZp {
		mvZ = 1
	} else if rndZ < pZp+pZn {
		mvZ = -1
	}
	if Params[0].ThreeD.IsFalse() || Params[0].Move.IsFalse() {
		mvY = 0
		mvZ = 0
	}
	if Params[0].Move.IsFalse() {
		mvX = 0
	}

	moving := false
	mx := x + mvX
	my := y + mvY
	mz := z + mvZ
	if mvX != 0 || mvY != 0 || mvZ != 0 { // moving..
		moving = true
		// fmt.Println("move:", mvX, pvX, pvXP, pvXN)
	}

	State.Set(hoP0, int(mz), int(my), int(mx), int(PKGCHoP0), int(cur))
	State.Set(hoV0, int(mz), int(my), int(mx), int(PKGCHoV0), int(cur))

	State.Set(hoPX, int(mz), int(my), int(mx), int(PKGCHoPX), int(cur))
	State.Set(hoVX, int(mz), int(my), int(mx), int(PKGCHoVX), int(cur))

	State.Set(hoPY, int(mz), int(my), int(mx), int(PKGCHoPY), int(cur))
	State.Set(hoVY, int(mz), int(my), int(mx), int(PKGCHoVY), int(cur))

	State.Set(hoPZ, int(mz), int(my), int(mx), int(PKGCHoPZ), int(cur))
	State.Set(hoVZ, int(mz), int(my), int(mx), int(PKGCHoVZ), int(cur))

	State.Set(pvX, int(mz), int(my), int(mx), int(PKGCPvelX), int(cur))
	State.Set(pvY, int(mz), int(my), int(mx), int(PKGCPvelY), int(cur))
	State.Set(pvZ, int(mz), int(my), int(mx), int(PKGCPvelZ), int(cur))
	State.Set(pvSq, int(mz), int(my), int(mx), int(PKGCPvelSq), int(cur))
	State.Set(lorenz, int(mz), int(my), int(mx), int(PKGCLorentz), int(cur))
	State.Set(esq, int(mz), int(my), int(mx), int(PKGCPESq), int(cur))

	State.Set(hoP0, int(mz), int(my), int(mx), int(PKGCDriver), int(cur))
	State.Set(particle, int(mz), int(my), int(mx), int(PKGCParticle), int(cur))

	if moving { // clear old data out
		for vi := int32(PKGCParticle); vi < int32(ParticleKGCStatesN); vi++ {
			State.Set(0.0, int(z), int(y), int(x), int(vi), int(cur))
			State.Set(0.0, int(z), int(y), int(x), int(vi), int(prv))
		}
	}
}

//gosl:end

func (ss *Sim) ParticleKGCConfig() {
	ParamsShouldDisplay = ParticleDisplay
	ss.StateVars = ParticleKGCStatesN
	ss.ViewInit(func(view *View) {
		view.SetVar(PKGCParticle, -1)
	})
}

// ParticleKGCViewAll configures the View to display ParticleKGC values
func ParticleKGCViewAll(view *View) {
	view.Settings.NPanels = PanelsFour
	view.Settings.Camera = 2
	view.Settings.Height = 0.8
	view.Panels[0].Var = PKGCHoP0
	view.Panels[1].Var = PKGCHoPX
	// view.SetCurPrev(Previous, 1)
	view.Panels[2].Var = CabPosA
	// view.SetCurPrev(Previous, 3)
	view.Panels[3].Var = CabPosB
}

func (ss *Sim) ParticleKGCStats() {
	ss.AddStat(ss.StatStep())
	ss.AddStat(ss.StatSum(CabCC))
	ss.AddStat(ss.StatSum(CabCharge))
	ss.AddStat(ss.StatSum(PKGCPvelX))
	ss.AddStat(ss.StatSum(PKGCPvelY))
	ss.AddStat(ss.StatSum(PKGCPvelZ))
	ss.AddStat(ss.StatSum(PKGCPvelSq))
	ss.AddStat(ss.StatSum(PKGCPESq))
}

// ParticleDisplay determines which Parameters fields to display.
var ParticleDisplay = []string{"Edges", "Energy", "C", "Diff", "Hbar", "Mass", "Wavelength", "PacketWidth", "Velocity", "Move"}
