// Code generated by "goal build"; DO NOT EDIT.
//line particle-kg.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

//gosl:start

// ParticleKGCStates are the state variables for particles in context
// of KGC complex wave equations on a wave state with two complex values (1, 2),
// where A = real and B = complex components.
type ParticleKGCStates CabStates //enums:enum -trim-prefix=PKGC

const (
	// PKGCParticle indicates the type of particle present at this cell.
	// zero indicates no particle.
	PKGCParticle ParticleKGCStates = ParticleKGCStates(CabStatesN) + iota

	// PKGCMomX is the particle momentum along X axis
	PKGCMomX

	// PKGCMomY is the particle momentum along Y axis
	PKGCMomY

	// PKGCMomZ is the particle momentum along Z axis
	PKGCMomZ

	// PKGCMomSq is the squared total particle momentum across all axes.
	PKGCMomSq

	// PKGCMomXP is the SHO position for momentum along positive X axis.
	PKGCMomXP

	// PKGCMomXPv is the velocity for SHO position for momentum along positive X axis.
	PKGCMomXPv

	// PKGCMomXN is the SHO position for momentum along negative X axis.
	PKGCMomXN

	// PKGCMomXNv is the velocity for SHO position for momentum along negative X axis.
	PKGCMomXNv

	// PKGCMomYP is the SHO position for momentum along positive Y axis.
	PKGCMomYP

	// PKGCMomYPv is the velocity for SHO position for momentum along positive Y axis.
	PKGCMomYPv

	// PKGCMomYN is the SHO position for momentum along negative Y axis.
	PKGCMomYN

	// PKGCMomYNv is the velocity for SHO position for momentum along negative Y axis.
	PKGCMomYNv

	// PKGCMomZP is the SHO position for momentum along positive Z axis.
	PKGCMomZP

	// PKGCMomZPv is the velocity for SHO position for momentum along positive Z axis.
	PKGCMomZPv

	// PKGCMomZN is the SHO position for momentum along negative Z axis.
	PKGCMomZN

	// PKGCMomZNv is the velocity for SHO position for momentum along negative Z axis.
	PKGCMomZNv
)

// ParticleKGCKernel is the kernel for computing the stochastic particle
// with simple harmonic oscillator self-momentum factors along positive
// and negative directions for each axis, based on KG on complex wave state.
func ParticleKGCKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	pposA := State.Value(int(z), int(y), int(x), int(CabPosA), int(prv))
	pposB := State.Value(int(z), int(y), int(x), int(CabPosB), int(prv))
	pvelA := State.Value(int(z), int(y), int(x), int(CabVelA), int(prv))
	pvelB := State.Value(int(z), int(y), int(x), int(CabVelB), int(prv))

	mchsq := Params[0].MCOverHSq

	var forceA, forceB float32
	if Params[0].ThreeD.IsTrue() {
		forceA = Laplacian26(x, y, z, int32(CabPosA), prv, pposA)
		forceB = Laplacian26(x, y, z, int32(CabPosB), prv, pposB)
	} else {
		forceA = Laplacian1D(x, y, z, int32(CabPosA), prv, pposA)
		forceB = Laplacian1D(x, y, z, int32(CabPosB), prv, pposB)
	}

	// everyone to the left of me gets NegX, to right gets PosX, etc
	nmomSq := NeighAverage27(x, y, z, int32(PKGCMomSq), prv)

	forceA += nmomSq * pvelA // drive entrainment instead of damping / self term from mass.
	forceB += nmomSq * pposB

	// todo: drive A and B out of phase based on particle charge!
	// probably only for neighbor of particle.
	velA := pvelA + Params[0].CSq*forceA
	posA := pposA + velA

	velB := pvelB + Params[0].CSq*forceB
	posB := pposB + velB

	// todo: later, based on particle..
	// var grAX, grAY, grAZ, grBX, grBY, grBZ float32
	// Gradient18(x, y, z, int32(CabPosA), prv, &grAX, &grAY, &grAZ)
	// Gradient18(x, y, z, int32(CabPosB), prv, &grBX, &grBY, &grBZ)
	//
	// chg := pposB*pvelA - pposA*pvelB
	//
	// curX := pposA*grBX - pposB*grAX
	// curY := pposA*grBY - pposB*grAY
	// curZ := pposA*grBZ - pposB*grAZ

	State.Set(forceA, int(z), int(y), int(x), int(CabForceA), int(cur))
	State.Set(velA, int(z), int(y), int(x), int(CabVelA), int(cur))
	State.Set(posA, int(z), int(y), int(x), int(CabPosA), int(cur))

	State.Set(forceB, int(z), int(y), int(x), int(CabForceB), int(cur))
	State.Set(velB, int(z), int(y), int(x), int(CabVelB), int(cur))
	State.Set(posB, int(z), int(y), int(x), int(CabPosB), int(cur))

	// State[z, y, x, CabCharge, cur] = chg
	// State[z, y, x, CabCurrentX, cur] = curX
	// State[z, y, x, CabCurrentY, cur] = curY
	// State[z, y, x, CabCurrentZ, cur] = curZ

	particle := State.Value(int(z), int(y), int(x), int(PKGCParticle), int(prv))
	if particle == 0 {
		return
	}

	momXP := State.Value(int(z), int(y), int(x), int(PKGCMomXP), int(prv))
	momXPv := State.Value(int(z), int(y), int(x), int(PKGCMomXPv), int(prv))
	momXN := State.Value(int(z), int(y), int(x), int(PKGCMomXN), int(prv))
	momXNv := State.Value(int(z), int(y), int(x), int(PKGCMomXNv), int(prv))

	momYP := State.Value(int(z), int(y), int(x), int(PKGCMomYP), int(prv))
	momYPv := State.Value(int(z), int(y), int(x), int(PKGCMomYPv), int(prv))
	momYN := State.Value(int(z), int(y), int(x), int(PKGCMomYN), int(prv))
	momYNv := State.Value(int(z), int(y), int(x), int(PKGCMomYNv), int(prv))

	momZP := State.Value(int(z), int(y), int(x), int(PKGCMomZP), int(prv))
	momZPv := State.Value(int(z), int(y), int(x), int(PKGCMomZPv), int(prv))
	momZN := State.Value(int(z), int(y), int(x), int(PKGCMomZN), int(prv))
	momZNv := State.Value(int(z), int(y), int(x), int(PKGCMomZNv), int(prv))

	momXPv += -mchsq * momXP
	momXP += momXPv
	momXNv += -mchsq * momXN
	momXN += momXNv

	momYPv += -mchsq * momYP
	momYP += momYPv
	momYNv += -mchsq * momYN
	momYN += momYNv

	momZPv += -mchsq * momZP
	momZP += momZPv
	momZNv += -mchsq * momZN
	momZN += momZNv

	homc := Params[0].HOverMC

	momX := homc * (momXP*momXNv - momXN*momXPv)
	momY := homc * (momYP*momYNv - momYN*momYPv)
	momZ := homc * (momZP*momZNv - momZN*momZPv)

	momSq := momX*momX + momY*momY + momZ*momZ

	e := 0.5 * (1.0 + momSq)
	pXp := 0.5 * (e + momX)
	pXn := 0.5 * (e - momX)
	pYp := 0.5 * (e + momY)
	pYn := 0.5 * (e - momY)
	pZp := 0.5 * (e + momZ)
	pZn := 0.5 * (e - momZ)

	rndX := GetRandomNumber(i, ctx.RandCounter.Counter, 0)
	rndY := GetRandomNumber(i, ctx.RandCounter.Counter, 1)
	rndZ := GetRandomNumber(i, ctx.RandCounter.Counter, 2)

	mvX := int32(0)
	if rndX < pXp {
		mvX = 1
	} else if rndX < pXp+pXn {
		mvX = -1
	}
	mvY := int32(0)
	if rndY < pYp {
		mvY = 1
	} else if rndY < pYp+pYn {
		mvY = -1
	}
	mvZ := int32(0)
	if rndZ < pZp {
		mvZ = 1
	} else if rndZ < pZp+pZn {
		mvZ = -1
	}
	if Params[0].ThreeD.IsFalse() {
		mvY = 0
		mvZ = 0
	}

	moving := false
	mx := x + mvX
	my := y + mvY
	mz := z + mvZ
	if mvX != 0 || mvY != 0 || mvZ != 0 { // moving..
		moving = true
		// fmt.Println("move:", mvX, momX, momXP, momXN)
	}

	State.Set(momXP, int(mz), int(my), int(mx), int(PKGCMomXP), int(cur))
	State.Set(momXPv, int(mz), int(my), int(mx), int(PKGCMomXPv), int(cur))
	State.Set(momXN, int(mz), int(my), int(mx), int(PKGCMomXN), int(cur))
	State.Set(momXNv, int(mz), int(my), int(mx), int(PKGCMomXNv), int(cur))

	State.Set(momYP, int(mz), int(my), int(mx), int(PKGCMomYP), int(cur))
	State.Set(momYPv, int(mz), int(my), int(mx), int(PKGCMomYPv), int(cur))
	State.Set(momYN, int(mz), int(my), int(mx), int(PKGCMomYN), int(cur))
	State.Set(momYNv, int(mz), int(my), int(mx), int(PKGCMomYNv), int(cur))

	State.Set(momZP, int(mz), int(my), int(mx), int(PKGCMomZP), int(cur))
	State.Set(momZPv, int(mz), int(my), int(mx), int(PKGCMomZPv), int(cur))
	State.Set(momZN, int(mz), int(my), int(mx), int(PKGCMomZN), int(cur))
	State.Set(momZNv, int(mz), int(my), int(mx), int(PKGCMomZNv), int(cur))

	State.Set(momX, int(mz), int(my), int(mx), int(PKGCMomX), int(cur))
	State.Set(momY, int(mz), int(my), int(mx), int(PKGCMomY), int(cur))
	State.Set(momZ, int(mz), int(my), int(mx), int(PKGCMomZ), int(cur))
	State.Set(momSq, int(mz), int(my), int(mx), int(PKGCMomSq), int(cur))

	State.Set(particle, int(mz), int(my), int(mx), int(PKGCParticle), int(cur))

	if moving { // clear old data out
		for vi := int32(PKGCParticle); vi < int32(ParticleKGCStatesN); vi++ {
			State.Set(0.0, int(z), int(y), int(x), int(vi), int(cur))
			State.Set(0.0, int(z), int(y), int(x), int(vi), int(prv))
		}
	}
}

//gosl:end

func (ss *Sim) ParticleKGCConfig() {
	ParamsShouldDisplay = KGShouldDisplay
	ss.StateVars = ParticleKGCStatesN
	ss.ViewInit(func(view *View) {
		view.SetVar(PKGCParticle, -1)
	})
}

// ParticleKGCViewAll configures the View to display ParticleKGC values
func ParticleKGCViewAll(view *View) {
	view.Settings.NPanels = PanelsFour
	view.Settings.Camera = 2
	view.Settings.Height = 0.8
	view.Panels[0].Var = PKGCMomXP
	view.Panels[1].Var = PKGCMomXN
	// view.SetCurPrev(Previous, 1)
	view.Panels[2].Var = CabPosA
	// view.SetCurPrev(Previous, 3)
	view.Panels[3].Var = CabPosB
}

func (ss *Sim) ParticleKGCStats() {
	ss.AddStat(ss.StatStep())
	ss.AddStat(ss.StatSum(CabCC))
	ss.AddStat(ss.StatSum(CabCharge))
	ss.AddStat(ss.StatSum(PKGCMomX))
	ss.AddStat(ss.StatSum(PKGCMomY))
	ss.AddStat(ss.StatSum(PKGCMomZ))
	ss.AddStat(ss.StatSum(PKGCMomSq))
}
