// Code generated by "goal build"; DO NOT EDIT.
//line schrodinger.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import "cogentcore.org/core/math32"

//gosl:start

// SchrodingerKernel is the kernel for computing the Schrodinger equations.
func SchrodingerKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	pposA := State.Value(int(z), int(y), int(x), int(CabAs), int(prv))
	pposB := State.Value(int(z), int(y), int(x), int(CabBs), int(prv))
	pvelA := State.Value(int(z), int(y), int(x), int(CabAv), int(prv))
	pvelB := State.Value(int(z), int(y), int(x), int(CabBv), int(prv))
	vpot := State.Value(int(z), int(y), int(x), int(CabV), int(prv))

	// need to alternate the updating for stability
	// just carry forward other vars.
	var forceA, velA, posA, forceB, velB, posB float32
	if cur == 0 {
		if Params[0].ThreeD.IsTrue() {
			forceA = Laplacian19(x, y, z, int32(CabBs), prv, pposB) // A driven by B
		} else {
			forceA = Laplacian1D(x, y, z, int32(CabBs), prv, pposB) // A driven by B
		}
		forceA *= -Params[0].HSqOver2M + vpot*pposB // note neg here, not in B
		velA = forceA                               // first order, not +=
		posA = pposA + velA

		// carry the other component forward
		velB = pvelB
		posB = pposB
	} else {
		if Params[0].ThreeD.IsTrue() {
			forceB = Laplacian19(x, y, z, int32(CabAs), prv, pposA) // B driven by A
		} else {
			forceB = Laplacian1D(x, y, z, int32(CabAs), prv, pposA) // B driven by A
		}
		forceB *= Params[0].HSqOver2M + vpot*pposA // todo: not sure about this!!
		velB = forceB                              // first order, not +=
		posB = pposB + velB

		// carry the other component forward
		velA = pvelA
		posA = pposA
	}

	State.Set(velA, int(z), int(y), int(x), int(CabAv), int(cur))
	State.Set(posA, int(z), int(y), int(x), int(CabAs), int(cur))

	State.Set(velB, int(z), int(y), int(x), int(CabBv), int(cur))
	State.Set(posB, int(z), int(y), int(x), int(CabBs), int(cur))

	State.Set(posA*posA+posB*posB, int(z), int(y), int(x), int(CabMag), int(cur))
}

//gosl:end

func (ss *Sim) SchrodingerConfig() {
	ParamsShouldDisplay = SchrodShouldDisplay
	ss.StateVars = CabStatesN
	ss.SchrodingerStats()
	ss.ViewInit(func(view *View) {
		view.SetVar(CabAs, -1)
	})
}

// SchrodShouldDisplay determines which Parameters fields to display.
var SchrodShouldDisplay = []string{"Edges", "Energy", "C", "Hbar", "Mass", "Wavelength", "PacketWidth"}

// Cab1DViewAll configures the View to display A and B, Cur and Prev
func Cab1DViewAll(view *View) {
	view.Settings.NPanels = PanelsFour
	view.Settings.Camera = 2
	// view.SetVarMinMax(WavePos, -0.8, 0.8)
	view.Settings.Height = 0.8
	view.SetCurPrev(Previous, 1)
	view.Panels[2].Var = CabBs
	view.SetCurPrev(Previous, 3)
	view.Panels[3].Var = CabBs
}

func (ss *Sim) SchrodingerStats() {
	ss.AddStat(ss.StatStep())
	ss.AddStat(ss.StatSum(CabMag))
	// a matter wave: the group velocity is not the phase velocity
	ss.AddStat(ss.StatGroupVel(math32.X, CabAs))
}
