// Code generated by "goal build"; DO NOT EDIT.
//line stats.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import (
	"math"
	"strconv"

	"cogentcore.org/core/base/metadata"
	"cogentcore.org/core/enums"
	"cogentcore.org/core/math32"
	"cogentcore.org/lab/plot"
	"cogentcore.org/lab/tensorfs"
)

// AddStat adds given stat function.
func (ss *Sim) AddStat(fun func(init bool)) {
	ss.StatFuncs = append(ss.StatFuncs, fun)
}

// RunStats runs all the stats functions, with given init flag.
func (ss *Sim) RunStats(init bool) {
	for _, sf := range ss.StatFuncs {
		sf(init)
	}
	if !init {
		tensorfs.DirTable(ss.Stats, nil).WriteToLog()
		if ss.GUI.Tabs != nil {
			ss.GUI.Tabs.AsLab().GoUpdatePlot("Root Stats Plot")
		}
	} else {
		if ss.GUI.Tabs != nil {
			tbs := ss.GUI.Tabs.AsLab()
			_, idx := tbs.CurrentTab()
			tbs.PlotTensorFS(ss.Stats)
			tbs.SelectTabIndex(idx)
		}
	}
}

// StateSum computes the sum of given variable at given cur vs. prev state
// with given non-edge size.
// StateMax returns the largest value of the vr variable over the interior.
func StateMax(sz math32.Vector3i, vr enums.Enum, curPrv int32) float64 {
	vri := int(vr.Int64())
	mx := float32(-math32.MaxFloat32)
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				v := State.Value(int(f.Z), int(f.Y), int(f.X), int(vri), int(curPrv))
				if v > mx {
					mx = v
				}
			}
		}
	}
	return float64(mx)
}

func StateSum(sz math32.Vector3i, vr enums.Enum, curPrv int32) float64 {
	vri := int(vr.Int64())
	sum := 0.0
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				sum += float64(State.Value(int(f.Z), int(f.Y), int(f.X), int(vri), int(curPrv)))
			}
		}
	}
	return sum
}

// StatStep is a stats function that records current time step
func (ss *Sim) StatStep() func(init bool) {
	return func(init bool) {
		name := "Step"
		tsr := ss.Stats.Int(name)
		if init {
			tsr.SetNumRows(0)
			plot.SetFirstStyler(tsr, func(s *plot.Style) {
				s.Range.SetMin(0)
				s.Role = plot.X
			})
			metadata.SetDoc(tsr, "Current time Step")
			return
		}
		ctx := GetCtx(0)
		tsr.AppendRowInt(int(ctx.Step))
	}
}

// StatSum is a stats function that records sum of given variable
// for current state.
func (ss *Sim) StatSum(vr enums.Enum) func(init bool) {
	return func(init bool) {
		name := vr.String()
		tsr := ss.Stats.Float64(name)
		if init {
			tsr.SetNumRows(0)
			plot.SetFirstStyler(tsr, func(s *plot.Style) {
				s.Range.SetMin(0)
				s.On = true
			})
			metadata.SetDoc(tsr, "Sum of "+name)
			return
		}
		ctx := GetCtx(0)
		tsr.AppendRowFloat(StateSum(ss.Config.Size, vr, ctx.CurState))
	}
}

// StatParticle is a stats function that records particle state
// for given particle index.
func (ss *Sim) StatParticle(idx int) func(init bool) {
	return func(init bool) {
		for pv := range ParticleVarsN {
			name := pv.String()
			tsr := ss.Stats.Float64(name)
			if init {
				tsr.SetNumRows(0)
				plot.SetFirstStyler(tsr, func(s *plot.Style) {
					s.Range.SetMin(0)
					s.On = true
				})
				metadata.SetDoc(tsr, "Particle "+strconv.Itoa(idx)+": "+name)
				continue
			}
			vri := int(pv.Int64())
			stat := float64(Particles.Value(int(idx), int(vri)))
			tsr.AppendRowFloat(stat)
		}
	}
}

// StateMean computes the mean of given variable over the non-edge interior.
func StateMean(sz math32.Vector3i, vr enums.Enum, curPrv int32) float64 {
	n := int(sz.X) * int(sz.Y) * int(sz.Z)
	if n == 0 {
		return 0
	}
	return StateSum(sz, vr, curPrv) / float64(n)
}

// StateCentroids computes the intensity-weighted (value squared) centroid
// along dim for each of the given variables, in cube coordinates, along with
// the total intensity, in ONE pass over the state. Variables that are
// everywhere zero get the box center.
// One pass because a full scan is the expensive part of any stat: at 100^3
// that is a million cells, so do not add more passes than you need.
func StateCentroids(sz math32.Vector3i, dim math32.Dims, curPrv int32, vrs []enums.Enum, ctrs, wts []float64) {
	nv := len(vrs)
	vris := make([]int, nv)
	num := make([]float64, nv)
	den := make([]float64, nv)
	for i, vr := range vrs {
		vris[i] = int(vr.Int64())
	}
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				d := float64(c.Dim(dim))
				for i := range nv {
					v := float64(State.Value(int(f.Z), int(f.Y), int(f.X), int(vris[i]), int(curPrv)))
					w := v * v
					num[i] += w * d
					den[i] += w
				}
			}
		}
	}
	for i := range nv {
		wts[i] = den[i]
		if den[i] == 0 {
			ctrs[i] = float64(sz.Dim(dim)) / 2
		} else {
			ctrs[i] = num[i] / den[i]
		}
	}
}

// StatGroupVelWindow is how many recorded samples [Sim.StatGroupVel] measures
// the centroid shift over. The centroid of a carrier under an envelope wobbles
// at twice the carrier frequency, so a one-sample difference is dominated by
// that wobble; a window long enough to cover a couple of periods averages it
// out without smearing a real change of speed.
var StatGroupVelWindow = 20

// StatCentroidName is the stat name for the centroid of vr along dim.
func StatCentroidName(vr enums.Enum, dim math32.Dims) string {
	return "Ctr" + vr.String() + dim.String()
}

// StatGroupVelName is the stat name for the group velocity of vr along dim.
func StatGroupVelName(vr enums.Enum, dim math32.Dims) string {
	return "Vg" + vr.String() + dim.String()
}

// StatGroupVel records, for each of the given variables, the intensity
// centroid along dim and the speed of that centroid in units of C: the group
// velocity of a wave packet. Both are recorded; only the velocity is plotted
// by default.
//
// The shift is measured over [StatGroupVelWindow] samples, so the first that
// many read zero. A packet crossing a wrapped edge is taken the short way
// round the box, so it does not register as a jump.
//
// A variable carrying a negligible share of the intensity in the group reads
// zero rather than the centroid of its own roundoff, which would otherwise be
// pure noise: in a Z pulse, for instance, the photon field is not excited at
// all. That is why these belong in one call rather than several -- besides
// sharing the one pass over the state, they calibrate each other.
func (ss *Sim) StatGroupVel(dim math32.Dims, vrs ...enums.Enum) func(init bool) {
	nv := len(vrs)
	ctrs := make([]float64, nv)
	wts := make([]float64, nv)
	var hist []float64
	var steps []int
	var n, win int
	return func(init bool) {
		ctx := GetCtx(0)
		if init {
			win = max(StatGroupVelWindow, 1)
			hist = make([]float64, win*nv)
			steps = make([]int, win)
			n = 0
			for _, vr := range vrs {
				ct := ss.Stats.Float64(StatCentroidName(vr, dim))
				vt := ss.Stats.Float64(StatGroupVelName(vr, dim))
				ct.SetNumRows(0)
				vt.SetNumRows(0)
				plot.SetFirstStyler(ct, func(s *plot.Style) {
					s.On = false
				})
				plot.SetFirstStyler(vt, func(s *plot.Style) {
					s.On = true
				})
				metadata.SetDoc(ct, "Intensity centroid of "+vr.String()+" along "+dim.String()+", in cubes")
				metadata.SetDoc(vt, "Group velocity of "+vr.String()+" along "+dim.String()+", in units of C")
			}
			return
		}
		sz := ss.Config.Size
		ln := float64(sz.Dim(dim))
		StateCentroids(sz, dim, ctx.CurState, vrs, ctrs, wts)
		mx := 0.0
		for i := range nv {
			if wts[i] > mx {
				mx = wts[i]
			}
		}
		// the window slot about to be overwritten holds the oldest sample
		old := n % win
		have := n >= win
		ds := float64(int(ctx.Step) - steps[old])
		for i, vr := range vrs {
			vg := 0.0
			if have && ds > 0 && ss.Params.C > 0 && wts[i] > 1.0e-6*mx {
				d := ctrs[i] - hist[old*nv+i]
				if d > ln/2 {
					d -= ln
				} else if d < -ln/2 {
					d += ln
				}
				vg = d / ds / float64(ss.Params.C)
			}
			hist[old*nv+i] = ctrs[i]
			ss.Stats.Float64(StatCentroidName(vr, dim)).AppendRowFloat(ctrs[i])
			ss.Stats.Float64(StatGroupVelName(vr, dim)).AppendRowFloat(vg)
		}
		steps[old] = int(ctx.Step)
		n++
	}
}

// StatMean is a stats function that records the mean of given variable over
// the interior, which for |Phi|^2 is directly comparable to v^2.
func (ss *Sim) StatMean(vr enums.Enum) func(init bool) {
	return func(init bool) {
		name := "Mean" + vr.String()
		tsr := ss.Stats.Float64(name)
		if init {
			tsr.SetNumRows(0)
			plot.SetFirstStyler(tsr, func(s *plot.Style) {
				s.On = true
			})
			metadata.SetDoc(tsr, "Mean of "+vr.String()+" over the interior")
			return
		}
		ctx := GetCtx(0)
		tsr.AppendRowFloat(StateMean(ss.Config.Size, vr, ctx.CurState))
	}
}

// StatSumSq records the summed squares of the given variables under the given
// name: the total power in a multi-component field.
func (ss *Sim) StatSumSq(name string, vrs ...enums.Enum) func(init bool) {
	return func(init bool) {
		tsr := ss.Stats.Float64(name)
		if init {
			tsr.SetNumRows(0)
			plot.SetFirstStyler(tsr, func(s *plot.Style) {
				s.On = false
			})
			metadata.SetDoc(tsr, "Summed squares of "+name)
			return
		}
		ctx := GetCtx(0)
		cur := ctx.CurState
		sz := ss.Config.Size
		vris := make([]int, len(vrs))
		for i, vr := range vrs {
			vris[i] = int(vr.Int64())
		}
		sum := 0.0
		var c math32.Vector3i
		for c.Z = range sz.Z {
			for c.Y = range sz.Y {
				for c.X = range sz.X {
					f := c.AddScalar(1)
					for i := range vris {
						v := float64(State.Value(int(f.Z), int(f.Y), int(f.X), int(vris[i]), int(cur)))
						sum += v * v
					}
				}
			}
		}
		tsr.AppendRowFloat(sum)
	}
}

// StatWeightedMean records the mean of vr weighted by the intensity of wtVr:
// what a wtVr wave packet sees as it passes, rather than the box average.
func (ss *Sim) StatWeightedMean(name string, vr, wtVr enums.Enum) func(init bool) {
	return func(init bool) {
		tsr := ss.Stats.Float64(name)
		if init {
			tsr.SetNumRows(0)
			plot.SetFirstStyler(tsr, func(s *plot.Style) {
				s.On = false
			})
			metadata.SetDoc(tsr, "Mean of "+vr.String()+" weighted by the intensity of "+wtVr.String())
			return
		}
		ctx := GetCtx(0)
		cur := ctx.CurState
		sz := ss.Config.Size
		vri := int(vr.Int64())
		wti := int(wtVr.Int64())
		num, den := 0.0, 0.0
		var c math32.Vector3i
		for c.Z = range sz.Z {
			for c.Y = range sz.Y {
				for c.X = range sz.X {
					f := c.AddScalar(1)
					w := float64(State.Value(int(f.Z), int(f.Y), int(f.X), int(wti), int(cur)))
					w *= w
					num += w * float64(State.Value(int(f.Z), int(f.Y), int(f.X), int(vri), int(cur)))
					den += w
				}
			}
		}
		if den > 0 {
			num /= den
		}
		tsr.AppendRowFloat(num)
	}
}

// StatVals returns the values recorded so far for the named stat,
// nil if there is no such stat.
func (ss *Sim) StatVals(name string) []float64 {
	tsrs, err := ss.Stats.Values(name)
	if err != nil || len(tsrs) != 1 {
		return nil
	}
	tsr := tsrs[0]
	n := tsr.Len()
	vals := make([]float64, n)
	for i := range n {
		vals[i] = tsr.Float1D(i)
	}
	return vals
}

// StateAt returns the value of the given variable at the cell nearest to pos,
// in non-edge coordinates, clamped to the interior.
func StateAt(sz math32.Vector3i, vri int, pos math32.Vector3, curPrv int32) float32 {
	c := CoordToInt(pos)
	c.X = min(max(c.X, 0), sz.X-1)
	c.Y = min(max(c.Y, 0), sz.Y-1)
	c.Z = min(max(c.Z, 0), sz.Z-1)
	f := c.AddScalar(1)
	return State.Value(int(f.Z), int(f.Y), int(f.X), int(vri), int(curPrv))
}

// invSqrt3 is 1/sqrt(3), normalizing the (1,1,1) diagonal.
const invSqrt3 = 0.57735026918962576451

// StateAtInterp returns the trilinearly interpolated value of the given
// variable at pos, in non-edge coordinates, clamped to the interior.
//
// Interpolated rather than nearest-cell because the radial stats compare an
// axis against a diagonal: [CoordToInt] truncates, which along a diagonal
// shortens the radius by up to 13% and reads as an anisotropy that is not
// there.
func StateAtInterp(sz math32.Vector3i, vri int, pos math32.Vector3, curPrv int32) float32 {
	b := math32.Vec3i(int32(math32.Floor(pos.X)), int32(math32.Floor(pos.Y)), int32(math32.Floor(pos.Z)))
	f := pos.Sub(CoordToFloat(b))
	tot := float32(0)
	for k := range 2 {
		wz := f.Z
		if k == 0 {
			wz = 1 - f.Z
		}
		for j := range 2 {
			wy := f.Y
			if j == 0 {
				wy = 1 - f.Y
			}
			for i := range 2 {
				wx := f.X
				if i == 0 {
					wx = 1 - f.X
				}
				c := math32.Vec3i(b.X+int32(i), b.Y+int32(j), b.Z+int32(k))
				c.X = min(max(c.X, 0), sz.X-1)
				c.Y = min(max(c.Y, 0), sz.Y-1)
				c.Z = min(max(c.Z, 0), sz.Z-1)
				g := c.AddScalar(1)
				tot += wx * wy * wz * State.Value(int(g.Z), int(g.Y), int(g.X), int(vri), int(curPrv))
			}
		}
	}
	return tot
}

// Direction labels for [StatRadialName].
const (
	// StatRadialAxis is the +X direction, along a face axis of the stencil.
	StatRadialAxis = "X"

	// StatRadialDiag is the (1,1,1) direction, through a corner of the stencil.
	StatRadialDiag = "D"
)

// StatRadialName is the stat name for a radial sample: name, direction label
// and radius index.
func StatRadialName(name, dir string, i int) string {
	return name + dir + strconv.Itoa(i)
}

// StatRadial records the given variable sampled at radii of
// [Config.Wavelength], twice that and so on out to nrad, from [Config.Source],
// along +X and along the (1,1,1) diagonal.
//
// The two directions at the same radius are the point: a field that should be
// spherical reads the same both ways only if the discretization is isotropic,
// so the pair measures the anisotropy directly.
func (ss *Sim) StatRadial(name string, vr enums.Enum, nrad int) func(init bool) {
	return ss.statRadial(name, vr, nrad, false)
}

// StatRadialVec is [Sim.StatRadial] for the MAGNITUDE of the three-vector
// whose X component is vr, such as E or B.
func (ss *Sim) StatRadialVec(name string, vr enums.Enum, nrad int) func(init bool) {
	return ss.statRadial(name, vr, nrad, true)
}

func (ss *Sim) statRadial(name string, vr enums.Enum, nrad int, vec bool) func(init bool) {
	dirs := []string{StatRadialAxis, StatRadialDiag}
	unit := make([]math32.Vector3, 2)
	unit[0] = math32.Vec3(1, 0, 0)
	unit[1] = math32.Vec3(invSqrt3, invSqrt3, invSqrt3)
	return func(init bool) {
		what := "Value of " + vr.String()
		if vec {
			what = "Magnitude of the vector at " + vr.String()
		}
		for d, dir := range dirs {
			for i := 1; i <= nrad; i++ {
				tsr := ss.Stats.Float64(StatRadialName(name, dir, i))
				if init {
					tsr.SetNumRows(0)
					plot.SetFirstStyler(tsr, func(s *plot.Style) {
						s.On = !vec
					})
					doc := what + " at " + strconv.Itoa(i) + " x Config.Wavelength from Config.Source, along " + dir
					metadata.SetDoc(tsr, doc)
					continue
				}
				ctx := GetCtx(0)
				sz := ss.Config.Size
				ctr := CenterF(ss.Config.Source)
				pos := ctr.Add(unit[d].MulScalar(float32(i) * ss.Config.Wavelength))
				vri := int(vr.Int64())
				v := float64(StateAtInterp(sz, vri, pos, ctx.CurState))
				if vec {
					vy := float64(StateAtInterp(sz, vri+1, pos, ctx.CurState))
					vz := float64(StateAtInterp(sz, vri+2, pos, ctx.CurState))
					v = math.Sqrt(v*v + vy*vy + vz*vz)
				}
				tsr.AppendRowFloat(v)
			}
		}
	}
}
