// Code generated by "core generate -add-types -add-funcs -gosl"; DO NOT EDIT.

package wavesim

import (
	"cogentcore.org/core/enums"
	"cogentcore.org/core/math32"
	"cogentcore.org/core/tree"
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Config", IDName: "config", Doc: "Config contains overall simulation configuration options.", Fields: []types.Field{{Name: "GPU", Doc: "GPU determines whether to use the GPU."}, {Name: "GUI", Doc: "GUI determines whether to show the GUI."}, {Name: "Equation", Doc: "Equation to run"}, {Name: "Size", Doc: "Size of Universe to run. This is only the active portion, excluding\nedges at all sizes (add 2 to each dim)."}, {Name: "ViewInterval", Doc: "ViewInterval is how often to update the view"}, {Name: "MaxSteps", Doc: "MaxSteps is the maximum number of steps to run."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Context", IDName: "context", Doc: "Context contains all simulation counters and other context.\nThis is only other state shared with GPU.", Directives: []types.Directive{{Tool: "gosl", Directive: "start"}}, Fields: []types.Field{{Name: "Size", Doc: "Size is the 3D size of the state, EXCLUSIVE of edges (add 2 to each dim)."}, {Name: "Step", Doc: "Step is the current simulation timestep."}, {Name: "CurState", Doc: "CurState is either 0 or 1, indicating which state variables\nare currently being updated on this compute pass."}, {Name: "pad"}, {Name: "pad1"}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Scene", IDName: "scene", Doc: "Scene is a Widget for managing the 3D Scene of the NetView", Embeds: []types.Field{{Name: "Scene"}}, Fields: []types.Field{{Name: "View"}}})

// NewScene returns a new [Scene] with the given optional parent:
// Scene is a Widget for managing the 3D Scene of the NetView
func NewScene(parent ...tree.Node) *Scene { return tree.New[Scene](parent...) }

// SetView sets the [Scene.View]
func (t *Scene) SetView(v *View) *Scene { t.View = v; return t }

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.GPUVars", IDName: "gpu-vars", Doc: "GPUVars is an enum for GPU variables, for specifying what to sync."})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.GUI", IDName: "gui", Doc: "GUI manages all standard elements of a simulation Graphical User Interface", Embeds: []types.Field{{Name: "Browser"}}, Fields: []types.Field{{Name: "Active", Doc: "Active is true if the GUI is configured and running"}, {Name: "SimForm", Doc: "SimForm displays the Sim object fields in the left panel."}, {Name: "Body", Doc: "Body is the entire content of the sim window."}, {Name: "isRunning", Doc: "isRunning is true if sim is running."}, {Name: "stopNow", Doc: "stopNow can be set via SetStopNow method under mutex protection\nto signal the current sim to stop running.\nIt is not used directly in the looper-based control logic, which has\nits own direct Stop function, but it is set there in case there are\nother processes that are looking at this flag."}, {Name: "View", Doc: "view if created."}, {Name: "sim", Doc: "the sim"}, {Name: "runMu"}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Equations", IDName: "equations", Doc: "Equations are the different implemented equations to simulate."})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Edges", IDName: "edges", Doc: "Edges determines how to handle the edges."})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Parameters", IDName: "parameters", Doc: "Parameters contains the full set of simulation parameters.\nthis is uploaded to the GPU.", Fields: []types.Field{{Name: "Edges", Doc: "Edges determines how to handle the edges."}, {Name: "DoEnergy", Doc: "DoEnergy determines if energy is computed (when not necessary)."}, {Name: "pad"}, {Name: "pad1"}, {Name: "Units", Doc: "Units are the relevant unit factors."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Display", IDName: "display", Doc: "Display contains display parameters.", Fields: []types.Field{{Name: "On", Doc: "On determines if display is updated."}, {Name: "Interval", Doc: "Interval is the number of time steps between display updates."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Units", IDName: "units", Doc: "Units contains all the relevant units", Fields: []types.Field{{Name: "C", Doc: "C is the speed of light factor"}, {Name: "CSq", Doc: "CSq = C^2"}, {Name: "Inv2CSq", Doc: "Inv2CSq = 1 / 2C^2"}, {Name: "pad"}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.PlaneMesh", IDName: "plane-mesh", Doc: "PlaneMesh is a xyz.Mesh that represents an X-Y plane through the state,\nas either a Heightfield or bars.\nIt is dynamically updated using the Set method.\nThe geometry is literal in the size:\n0,0,0 lower-left corner and increasing X,Z in display for the X,Y plane.\nDisplay applies an overall scaling to make it fit within the larger view.", Embeds: []types.Field{{Name: "MeshBase"}}, Fields: []types.Field{{Name: "view"}, {Name: "panelNo", Doc: "our panel number"}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.PlaneObj", IDName: "plane-obj", Doc: "PlaneObj is the Plane 3D object within the View", Embeds: []types.Field{{Name: "Solid"}}, Fields: []types.Field{{Name: "panelNo"}, {Name: "view"}}})

// NewPlaneObj returns a new [PlaneObj] with the given optional parent:
// PlaneObj is the Plane 3D object within the View
func NewPlaneObj(parent ...tree.Node) *PlaneObj { return tree.New[PlaneObj](parent...) }

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.ViewModes", IDName: "view-modes", Doc: "ViewModes are different ways of displaying wave states."})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.CurPrev", IDName: "cur-prev", Doc: "CurPrev for Current vs Previous state access."})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.NPanels", IDName: "n-panels", Doc: "NPanels selects number of panels."})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Settings", IDName: "settings", Doc: "Settings for how the View is rendered.", Directives: []types.Directive{{Tool: "gosl", Directive: "end"}}, Fields: []types.Field{{Name: "NPanels", Doc: "Number of different panels, each capable of displaying a different variable, mode,\nand location in the state."}, {Name: "Mode", Doc: "Mode is how the state values are displayed."}, {Name: "Height", Doc: "Height is how high the values are, in normalized units."}, {Name: "Camera", Doc: "Camera specifies the initial camera view to show the scene\n1 = default = top-down, 2 = side-long"}, {Name: "BarSize", Doc: "size of a single bar element, where 1 = full width and no space.. .9 default"}, {Name: "ColorMap", Doc: "name of color map to use"}, {Name: "LabelSize", Doc: "size of the labels"}, {Name: "ZeroAlpha", Doc: "opacity (0-1) of zero values. greater magnitude values become increasingly\nopaque on either side of this minimum."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.VarSettings", IDName: "var-settings", Doc: "VarSettings holds parameters for display of each variable", Fields: []types.Field{{Name: "Var", Doc: "the variable"}, {Name: "ZeroCtr", Doc: "keep Min - Max centered around 0, and use negative heights for units\nelse use full min-max range for height (no negative heights)"}, {Name: "Range", Doc: "range to display"}, {Name: "MinMax", Doc: "if not using fixed range, this is the actual range of data"}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.VarSettinger", IDName: "var-settinger", Doc: "VarSettinger sets variable parameters", Methods: []types.Method{{Name: "SetVarSettings", Args: []string{"vs"}}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Sim", IDName: "sim", Doc: "Sim contains everything for the simulation.", Directives: []types.Directive{{Tool: "go", Directive: "generate", Args: []string{"core", "generate", "-add-types", "-add-funcs", "-gosl"}}}, Fields: []types.Field{{Name: "Params", Doc: "Params contains the current simulation parameters."}, {Name: "Config", Doc: "Config contains the broader running configuration."}, {Name: "ConfigFunc", Doc: "ConfigFunc is run at initial configuration, after all default configuration,\nand can then change any parameters etc."}, {Name: "InitFunc", Doc: "InitFunc is run at initialization, and should be used to set\nthe initial State, using functions in init."}, {Name: "viewInitFuncs", Doc: "viewInitFuncs are run at initialization of the GUI wave View.\nuse ViewInit method to add."}, {Name: "Root", Doc: "Root is the root tensorfs directory, where all stats and other misc sim data goes."}, {Name: "Stats", Doc: "Stats has the stats directory within Root."}, {Name: "Current", Doc: "Current has the current stats values within Stats."}, {Name: "GUI", Doc: "GUI manages all the GUI elements"}, {Name: "StateVars", Doc: "StateVars points the current state variables in effect."}, {Name: "Rand", Doc: "Rand is the random number generator for the network.\nall random calls must use this.\nSet seed here for weight initialization values."}, {Name: "RandSeed", Doc: "Random seed to be set at the start of configuring\nthe network and initializing the weights.\nSet this to get a different set of weights."}, {Name: "RandSeeds", Doc: "RandSeeds is a list of random seeds to use for each run."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.PanelView", IDName: "panel-view", Doc: "PanelView for what each panel in the View renders.", Fields: []types.Field{{Name: "Var", Doc: "Variable to display."}, {Name: "CurPrev", Doc: "Select which state to view"}, {Name: "Mode", Doc: "Mode is how the state values are displayed for this panel."}, {Name: "Offset", Doc: "Offset is an additional offset from the global Start,\nenforced to be within the displayable size."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.View", IDName: "view", Doc: "View is a Cogent Core Widget that provides a 3D view into state.", Embeds: []types.Field{{Name: "Frame"}, {Name: "Mutex"}}, Fields: []types.Field{{Name: "Var", Doc: "Var determines the set of variables being used.\nactual variable to view is in the PanelView."}, {Name: "Panels", Doc: "Pannels are the view settings per panel (4 max)."}, {Name: "Start", Doc: "Starting front-left corner location within state."}, {Name: "Size", Doc: "Size of planes"}, {Name: "VarSettings", Doc: "parameters for the list of variables to view"}, {Name: "Settings", Doc: "Settings are parameters controlling how the view is rendered"}, {Name: "Counters", Doc: "Counters are displayed at the bottom: time, etc."}, {Name: "colorMap", Doc: "color map for mapping values to colors -- set by name in Settings"}, {Name: "curPanel", Doc: "which panel are we currently updating"}, {Name: "curNPanels", Doc: "current number of panels rendered -- if changes, do full rebuild."}, {Name: "midFrame"}, {Name: "scene"}, {Name: "counters", Doc: "SceneDBG  *Scene"}, {Name: "varsFrame"}, {Name: "toolbar"}, {Name: "viewbar"}}})

// NewView returns a new [View] with the given optional parent:
// View is a Cogent Core Widget that provides a 3D view into state.
func NewView(parent ...tree.Node) *View { return tree.New[View](parent...) }

// SetPanels sets the [View.Panels]:
// Pannels are the view settings per panel (4 max).
func (t *View) SetPanels(v [4]PanelView) *View { t.Panels = v; return t }

// SetStart sets the [View.Start]:
// Starting front-left corner location within state.
func (t *View) SetStart(v math32.Vector3i) *View { t.Start = v; return t }

// SetSize sets the [View.Size]:
// Size of planes
func (t *View) SetSize(v math32.Vector3i) *View { t.Size = v; return t }

// SetVarSettings sets the [View.VarSettings]:
// parameters for the list of variables to view
func (t *View) SetVarSettings(v map[enums.Enum]*VarSettings) *View { t.VarSettings = v; return t }

// SetSettings sets the [View.Settings]:
// Settings are parameters controlling how the view is rendered
func (t *View) SetSettings(v Settings) *View { t.Settings = v; return t }

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.WaveStates", IDName: "wave-states", Doc: "WaveStates are the state variables for Wave equations."})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.FormDialog", Doc: "FormDialog opens a dialog in a new, separate window\nfor viewing / editing the given struct object, in\nthe context of the given ctx widget.", Args: []string{"ctx", "v", "title"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.Laplacian26", Doc: "Laplacian26 computes the 3D Laplacian across 26 neighbors,\nfor given x,y,z center coordinates, variable index vidx,\nand cur / prev time index tidx. ctr is the center value.", Args: []string{"x", "y", "z", "vidx", "tidx", "ctr"}, Returns: []string{"float32"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.PotentialEnergy26", Doc: "PotentialEnergy26 computes the 3D potential energy across 26 neighbors,\nfor given x,y,z center coordinates, variable index vidx,\nand cur / prev time index tidx. ctr is the center value.", Args: []string{"x", "y", "z", "vidx", "tidx", "ctr"}, Returns: []string{"float32"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.GPUInit", Doc: "GPUInit initializes the GPU compute system,\nconfiguring system(s), variables and kernels.\nIt is safe to call multiple times: detects if already run."})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.GPURelease", Doc: "GPURelease releases the GPU compute system resources.\nCall this at program exit."})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunWave1DKernel", Doc: "RunWave1DKernel runs the Wave1DKernel kernel with given number of elements,\non either the CPU or GPU depending on the UseGPU variable.\nCan call multiple Run* kernels in a row, which are then all launched\nin the same command submission on the GPU, which is by far the most efficient.\nMUST call RunDone (with optional vars to sync) after all Run calls.\nAlternatively, a single-shot RunOneWave1DKernel call does Run and Done for a\nsingle run-and-sync case.", Args: []string{"n"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunWave1DKernelGPU", Doc: "RunWave1DKernelGPU runs the Wave1DKernel kernel on the GPU. See [RunWave1DKernel] for more info.", Args: []string{"n"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunWave1DKernelCPU", Doc: "RunWave1DKernelCPU runs the Wave1DKernel kernel on the CPU.", Args: []string{"n"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunOneWave1DKernel", Doc: "RunOneWave1DKernel runs the Wave1DKernel kernel with given number of elements,\non either the CPU or GPU depending on the UseGPU variable.\nThis version then calls RunDone with the given variables to sync\nafter the Run, for a single-shot Run-and-Done call. If multiple kernels\ncan be run in sequence, it is much more efficient to do multiple Run*\ncalls followed by a RunDone call.", Args: []string{"n", "syncVars"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunWave3DKernel", Doc: "RunWave3DKernel runs the Wave3DKernel kernel with given number of elements,\non either the CPU or GPU depending on the UseGPU variable.\nCan call multiple Run* kernels in a row, which are then all launched\nin the same command submission on the GPU, which is by far the most efficient.\nMUST call RunDone (with optional vars to sync) after all Run calls.\nAlternatively, a single-shot RunOneWave3DKernel call does Run and Done for a\nsingle run-and-sync case.", Args: []string{"n"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunWave3DKernelGPU", Doc: "RunWave3DKernelGPU runs the Wave3DKernel kernel on the GPU. See [RunWave3DKernel] for more info.", Args: []string{"n"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunWave3DKernelCPU", Doc: "RunWave3DKernelCPU runs the Wave3DKernel kernel on the CPU.", Args: []string{"n"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunOneWave3DKernel", Doc: "RunOneWave3DKernel runs the Wave3DKernel kernel with given number of elements,\non either the CPU or GPU depending on the UseGPU variable.\nThis version then calls RunDone with the given variables to sync\nafter the Run, for a single-shot Run-and-Done call. If multiple kernels\ncan be run in sequence, it is much more efficient to do multiple Run*\ncalls followed by a RunDone call.", Args: []string{"n", "syncVars"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunDone", Doc: "RunDone must be called after Run* calls to start compute kernels.\nThis actually submits the kernel jobs to the GPU, and adds commands\nto synchronize the given variables back from the GPU to the CPU.\nAfter this function completes, the GPU results will be available in\nthe specified variables.", Args: []string{"syncVars"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.ToGPU", Doc: "ToGPU copies given variables to the GPU for the system.", Args: []string{"vars"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunGPUSync", Doc: "RunGPUSync can be called to synchronize data between CPU and GPU.\nAny prior ToGPU* calls will execute to send data to the GPU,\nand any subsequent RunDone* calls will copy data back from the GPU."})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.ToGPUTensorStrides", Doc: "ToGPUTensorStrides gets tensor strides and starts copying to the GPU."})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.ReadFromGPU", Doc: "ReadFromGPU starts the process of copying vars to the GPU.", Args: []string{"vars"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.SyncFromGPU", Doc: "SyncFromGPU synchronizes vars from the GPU to the actual variable.", Args: []string{"vars"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.GetParams", Doc: "GetParams returns a pointer to the given global variable:\n[Params] []Parameters at given index. This directly processed in the GPU code,\nso this function call is an equivalent for the CPU.", Args: []string{"idx"}, Returns: []string{"Parameters"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.GetCtx", Doc: "GetCtx returns a pointer to the given global variable:\n[Ctx] []Context at given index. This directly processed in the GPU code,\nso this function call is an equivalent for the CPU.", Args: []string{"idx"}, Returns: []string{"Context"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.NewGUIBody", Doc: "NewGUIBody returns a new GUI, with an initialized Body by calling [gui.MakeBody].", Args: []string{"b", "sim", "fsroot", "appname", "title", "about"}, Returns: []string{"GUI"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.NewPlaneMesh", Doc: "NewPlaneMesh adds PlaneMesh mesh to given scene for given layer", Args: []string{"sc", "view", "panel"}, Returns: []string{"PlaneMesh"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.Run", Args: []string{"configFunc", "initFunc"}, Returns: []string{"Sim"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.RunSim", Args: []string{"cfg", "configFunc", "initFunc"}, Returns: []string{"Sim"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.Embed", Directives: []types.Directive{{Tool: "yaegi", Directive: "add"}}, Args: []string{"parent", "configFunc", "initFunc"}, Returns: []string{"Sim"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.Wave3DKernel", Doc: "Wave3DKernel is the kernel for computing the Wave3D equations.", Directives: []types.Directive{{Tool: "gosl", Directive: "kernel"}}, Args: []string{"i"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.Wave1DKernel", Doc: "Wave1DKernel is the kernel for computing the Wave1D equations.", Directives: []types.Directive{{Tool: "gosl", Directive: "kernel"}}, Args: []string{"i"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.Wave1DViewAll", Doc: "Wave1DViewAll configures the", Args: []string{"view"}})
