// Code generated by "core generate -add-types -add-funcs -gosl"; DO NOT EDIT.

package wavesim

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Config", IDName: "config", Doc: "Config contains overall simulation configuration options.", Fields: []types.Field{{Name: "GPU", Doc: "GPU determines whether to use the GPU."}, {Name: "GUI", Doc: "GUI determines whether to show the GUI."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Context", IDName: "context", Doc: "Context contains all simulation counters and other context.\nThis is only other state shared with GPU.", Directives: []types.Directive{{Tool: "gosl", Directive: "start"}}, Fields: []types.Field{{Name: "Size", Doc: "Size is the 3D size of the state, EXCLUSIVE of edges (add 2 to each dim)."}, {Name: "Step", Doc: "Step is the current simulation timestep."}, {Name: "CurState", Doc: "CurState is either 0 or 1, indicating which state variables\nare currently being updated on this compute pass."}, {Name: "pad"}, {Name: "pad1"}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Equations", IDName: "equations", Doc: "Equations are the different implemented equations to simulate."})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Edges", IDName: "edges", Doc: "Edges determines how to handle the edges."})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Parameters", IDName: "parameters", Doc: "Parameters contains the full set of simulation parameters.\nthis is uploaded to the GPU.", Fields: []types.Field{{Name: "Equation", Doc: "Equation determines what equations are computed."}, {Name: "Edges", Doc: "Edges determines how to handle the edges."}, {Name: "DoEnergy", Doc: "DoEnergy determines if energy is computed (when not necessary)."}, {Name: "pad"}, {Name: "Units", Doc: "Units are the relevant unit factors."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Display", IDName: "display", Doc: "Display contains display parameters.", Fields: []types.Field{{Name: "On", Doc: "On determines if display is updated."}, {Name: "Interval", Doc: "Interval is the number of time steps between display updates."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Units", IDName: "units", Doc: "Units contains all the relevant units", Fields: []types.Field{{Name: "C", Doc: "C is the speed of light factor"}, {Name: "CSq", Doc: "CSq = C^2"}, {Name: "Inv2CSq", Doc: "Inv2CSq = 1 / 2C^2"}, {Name: "pad"}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.Sim", IDName: "sim", Doc: "Sim contains everything for the simulation.", Directives: []types.Directive{{Tool: "go", Directive: "generate", Args: []string{"core", "generate", "-add-types", "-add-funcs", "-gosl"}}}, Fields: []types.Field{{Name: "Params", Doc: "Params contains the current simulation parameters."}, {Name: "Config", Doc: "Config contains the broader running configuration."}, {Name: "Root", Doc: "Root is the root tensorfs directory, where all stats and other misc sim data goes."}, {Name: "Stats", Doc: "Stats has the stats directory within Root."}, {Name: "Current", Doc: "Current has the current stats values within Stats."}}})

var _ = types.AddType(&types.Type{Name: "github.com/WaveReality/waves/wavesim.WaveStates", IDName: "wave-states", Doc: "WaveStates are the state variables for Wave equations."})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.Laplacian26", Doc: "Laplacian26 computes the 3D Laplacian across 26 neighbors,\nfor given x,y,z center coordinates, variable index vidx,\nand cur / prev time index tidx. ctr is the center value.", Directives: []types.Directive{{Tool: "gosl", Directive: "start"}}, Args: []string{"x", "y", "z", "vidx", "tidx", "ctr"}, Returns: []string{"float32"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.PotentialEnergy26", Doc: "PotentialEnergy26 computes the 3D potential energy across 26 neighbors,\nfor given x,y,z center coordinates, variable index vidx,\nand cur / prev time index tidx. ctr is the center value.", Args: []string{"x", "y", "z", "vidx", "tidx", "ctr"}, Returns: []string{"float32"}})

var _ = types.AddFunc(&types.Func{Name: "github.com/WaveReality/waves/wavesim.Wave3DKernel", Doc: "Wave3DKernel is the kernel for computing the Wave3D equations.", Directives: []types.Directive{{Tool: "gosl", Directive: "kernel"}}, Args: []string{"i"}})
