// Code generated by "goal build"; DO NOT EDIT.
//line wave.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

//gosl:start

// WaveStates are the state variables for Wave equations.
type WaveStates int32 //enums:enum -trim-prefix=Wave

const (
	// WavePos is the position (height) wave state variable.
	WavePos WaveStates = iota

	// WaveVel is the velocity of wave state variable.
	WaveVel

	// WaveForce is the net force computed from neighbors.
	WaveForce

	// WaveKinetic is the kinetic energy.
	WaveKinetic

	// WavePotential is the potential energy.
	WavePotential

	// WaveEnergy is the total kinetic + potential energy.
	WaveEnergy
)

// Wave3DKernel is the kernel for computing the Wave3D equations.
func Wave3DKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	ppos := State.Value(int(z), int(y), int(x), int(WavePos), int(prv))
	pvel := State.Value(int(z), int(y), int(x), int(WaveVel), int(prv))
	force := Laplacian26(x, y, z, int32(WavePos), prv, ppos)
	vel := pvel + Params[0].CSq*force
	pos := ppos + vel

	if Params[0].Energy.IsTrue() {
		midVel := 0.5 * (pvel + vel)
		kinetic := Params[0].Inv2CSq * midVel * midVel
		potential := PotentialEnergy26(x, y, z, int32(WavePos), prv, ppos)

		State.Set(kinetic, int(z), int(y), int(x), int(WaveKinetic), int(cur))
		State.Set(potential, int(z), int(y), int(x), int(WavePotential), int(cur))
		State.Set(kinetic+potential, int(z), int(y), int(x), int(WaveEnergy), int(cur))
	}
	State.Set(force, int(z), int(y), int(x), int(WaveForce), int(cur))
	State.Set(vel, int(z), int(y), int(x), int(WaveVel), int(cur))
	State.Set(pos, int(z), int(y), int(x), int(WavePos), int(cur))
}

// Wave1DKernel is the kernel for computing the Wave1D equations.
func Wave1DKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	ppos := State.Value(int(z), int(y), int(x), int(WavePos), int(prv))
	pvel := State.Value(int(z), int(y), int(x), int(WaveVel), int(prv))
	force := Laplacian1D(x, y, z, int32(WavePos), prv, ppos)
	vel := pvel + Params[0].CSq*force
	pos := ppos + vel

	if Params[0].Energy.IsTrue() {
		midVel := 0.5 * (pvel + vel)
		kinetic := Params[0].Inv2CSq * midVel * midVel
		potential := PotentialEnergy1D(x, y, z, int32(WavePos), prv, ppos)

		State.Set(kinetic, int(z), int(y), int(x), int(WaveKinetic), int(cur))
		State.Set(potential, int(z), int(y), int(x), int(WavePotential), int(cur))
		State.Set(kinetic+potential, int(z), int(y), int(x), int(WaveEnergy), int(cur))
	}
	State.Set(force, int(z), int(y), int(x), int(WaveForce), int(cur))
	State.Set(vel, int(z), int(y), int(x), int(WaveVel), int(cur))
	State.Set(pos, int(z), int(y), int(x), int(WavePos), int(cur))
}

//gosl:end

func (ws WaveStates) SetVarSettings(vs *VarSettings) {
	// todo: can set per variable here
}

func (ss *Sim) WaveConfig() {
	ParamsShouldDisplay = WaveShouldDisplay
	ss.StateVars = WaveStatesN
	ss.ViewInit(func(view *View) {
		view.SetVar(WavePos, -1)
		if ss.Config.Equation == Wave1D {
			view.SetMode(Bars, -1)
		}
	})
}

// WaveShouldDisplay determines which Parameters fields to display.
var WaveShouldDisplay = []string{"Edges", "Energy", "C"}

// Wave1DViewAll configures the View to display Pos and Vel, Cur and Prev
func Wave1DViewAll(view *View) {
	view.Settings.NPanels = PanelsFour
	view.Settings.Camera = 2
	view.SetVarMinMax(WavePos, -0.8, 0.8)
	view.Settings.Height = 0.8
	view.SetCurPrev(Previous, 1)
	view.Panels[2].Var = WaveVel
	view.SetCurPrev(Previous, 3)
	view.Panels[3].Var = WaveVel
}

func (ss *Sim) WaveStats() {
	ss.AddStat(ss.StatStep())
	ss.AddStat(ss.StatSum(WaveKinetic))
	ss.AddStat(ss.StatSum(WavePotential))
	ss.AddStat(ss.StatSum(WaveEnergy))
}
