// Code generated by "goal build"; DO NOT EDIT.
//line wave.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

//gosl:start

// WaveStates are the state variables for Wave equations.
type WaveStates int32 //enums:enum -trim-prefix=Wave

const (
	// WavePos is the position (height) wave state variable.
	WavePos WaveStates = iota

	// WaveVel is the velocity of wave state variable.
	WaveVel

	// WaveForce is the net force computed from neighbors.
	WaveForce

	// WaveKinetic is the kinetic energy.
	WaveKinetic

	// WavePotential is the potential energy.
	WavePotential

	// WaveEnergy is the total kinetic + potential energy.
	WaveEnergy
)

func (ws WaveStates) SetVarSettings(vs *VarSettings) {
	// todo: can set per variable here
}

// Wave3DKernel is the kernel for computing the Wave3D equations.
func Wave3DKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()
	ppos := State.Value(int(z), int(y), int(x), int(WavePos), int(prv))
	pvel := State.Value(int(z), int(y), int(x), int(WaveVel), int(prv))
	force := Laplacian26(x, y, z, int32(WavePos), prv, ppos)
	vel := pvel + Params[0].Units.CSq*force
	pos := ppos + vel

	if Params[0].DoEnergy.IsTrue() {
		midVel := 0.5 * (pvel + vel)
		kinetic := Params[0].Units.Inv2CSq * midVel * midVel
		potential := PotentialEnergy26(x, y, z, int32(WavePos), prv, ppos)

		State.Set(kinetic, int(z), int(y), int(x), int(WaveKinetic), int(cur))
		State.Set(potential, int(z), int(y), int(x), int(WavePotential), int(cur))
		State.Set(kinetic+potential, int(z), int(y), int(x), int(WaveEnergy), int(cur))
	}
	State.Set(force, int(z), int(y), int(x), int(WaveForce), int(cur))
	State.Set(vel, int(z), int(y), int(x), int(WaveVel), int(cur))
	State.Set(pos, int(z), int(y), int(x), int(WavePos), int(cur))
}

//gosl:end

func (ss *Sim) WaveConfig() {
	ss.StateVars = WaveStatesN
}
