// Code generated by "goal build"; DO NOT EDIT.
//line weyl.goal:1
// Copyright (c) 2026, The WaveReality Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package wavesim

import (
	"cogentcore.org/core/base/metadata"
	"cogentcore.org/core/math32"
	"cogentcore.org/lab/plot"
)

//gosl:start

// WeylStates are the state variables for the chiral equation: a left-handed
// and a right-handed 2-spinor, each with two complex components. There are no
// velocity variables -- the equation is FIRST order in time, so the value is
// the whole state.
type WeylStates EMStates //enums:enum -trim-prefix=Weyl

const (
	// WeylL1a is the left-handed spinor, component 1, real part.
	WeylL1a WeylStates = WeylStates(EMStatesN) + iota

	// WeylL1b is the left-handed spinor, component 1, imaginary part.
	WeylL1b

	// WeylL2a is the left-handed spinor, component 2, real part.
	WeylL2a

	// WeylL2b is the left-handed spinor, component 2, imaginary part.
	WeylL2b

	// WeylR1a is the right-handed spinor, component 1, real part.
	WeylR1a

	// WeylR1b is the right-handed spinor, component 1, imaginary part.
	WeylR1b

	// WeylR2a is the right-handed spinor, component 2, real part.
	WeylR2a

	// WeylR2b is the right-handed spinor, component 2, imaginary part.
	WeylR2b

	// WeylLMag is |psi_L|^2.
	WeylLMag

	// WeylRMag is |psi_R|^2. The conserved total is this plus WeylLMag.
	WeylRMag
)

// WeylKernel is the chiral (Weyl) form of the Dirac equation, as two
// first-order 2-spinors rather than one second-order one:
//
//	d_t psi_L = +c (sigma.grad) psi_L - i (m c^2 / hbar) psi_R
//	d_t psi_R = -c (sigma.grad) psi_R - i (m c^2 / hbar) psi_L
//
// At m = 0 the two halves come apart completely, and each is a massless wave
// moving at exactly c with one fixed helicity: spin against momentum for L,
// along it for R. A neutrino is one of these on its own. The mass term is the
// ONLY thing joining them, and all it does is turn each into the other at
// m c^2 / hbar. That is what an electron is here -- two lightspeed waves
// trading places, so the average motion comes out slower than c, and the rest
// mass is the frequency of the trade.
//
// Keeping L and R as separate fields is the point. The second-order Dirac
// equation eliminates one of them, which needs both to share a covariant
// derivative and a constant mass -- neither survives the electroweak theory,
// where only L feels the weak force and the mass is the Higgs field.
//
// The integration is NOT Visscher's. That scheme splits a complex field into
// real and imaginary parts driven by each other, which works because
// Schrodinger's H is real in the position basis. Here sigma.grad carries
// sigma_y, which is imaginary, so d_t(real) depends on the real parts too and
// there is nothing to stagger. What this is instead is the three-level
// leapfrog for a first-order system, which the two state buffers already hold:
// cur is two steps back before it is written, prv is one, so
//
//	u(t+1) = u(t-1) + 2 dt (d_t u)(t)
//
// falls out with no extra storage. Second-order accurate and norm-preserving
// for an antisymmetric right-hand side, which this is.
//
// Stability wants sqrt(c^2 khat^2 + (m c^2 / hbar)^2) < 1 for the steepest khat
// the gradient stencil can see, so C has to be well under its usual limit:
// WeylConfig sets it.
//
// 3D only. sigma.grad mixes the three axes into each other, so a 1D version
// would not be this equation with a dimension removed -- it would be a
// different one.
func WeylKernel(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	var x, y, z int32
	ok := ctx.StateCoords(i, &x, &y, &z)
	if !ok {
		return
	}
	cur := ctx.CurState
	prv := ctx.PrevState()

	// the three-level leapfrog: cur still holds u(t-1) until we write it
	ol1a := State.Value(int(z), int(y), int(x), int(WeylL1a), int(cur))
	ol1b := State.Value(int(z), int(y), int(x), int(WeylL1b), int(cur))
	ol2a := State.Value(int(z), int(y), int(x), int(WeylL2a), int(cur))
	ol2b := State.Value(int(z), int(y), int(x), int(WeylL2b), int(cur))
	or1a := State.Value(int(z), int(y), int(x), int(WeylR1a), int(cur))
	or1b := State.Value(int(z), int(y), int(x), int(WeylR1b), int(cur))
	or2a := State.Value(int(z), int(y), int(x), int(WeylR2a), int(cur))
	or2b := State.Value(int(z), int(y), int(x), int(WeylR2b), int(cur))

	// u(t), which the right-hand side is evaluated at
	nl1a := State.Value(int(z), int(y), int(x), int(WeylL1a), int(prv))
	nl1b := State.Value(int(z), int(y), int(x), int(WeylL1b), int(prv))
	nl2a := State.Value(int(z), int(y), int(x), int(WeylL2a), int(prv))
	nl2b := State.Value(int(z), int(y), int(x), int(WeylL2b), int(prv))
	nr1a := State.Value(int(z), int(y), int(x), int(WeylR1a), int(prv))
	nr1b := State.Value(int(z), int(y), int(x), int(WeylR1b), int(prv))
	nr2a := State.Value(int(z), int(y), int(x), int(WeylR2a), int(prv))
	nr2b := State.Value(int(z), int(y), int(x), int(WeylR2b), int(prv))

	gl1a := Gradient10(x, y, z, int32(WeylL1a), prv)
	gl1b := Gradient10(x, y, z, int32(WeylL1b), prv)
	gl2a := Gradient10(x, y, z, int32(WeylL2a), prv)
	gl2b := Gradient10(x, y, z, int32(WeylL2b), prv)
	gr1a := Gradient10(x, y, z, int32(WeylR1a), prv)
	gr1b := Gradient10(x, y, z, int32(WeylR1b), prv)
	gr2a := Gradient10(x, y, z, int32(WeylR2a), prv)
	gr2b := Gradient10(x, y, z, int32(WeylR2b), prv)

	// sigma.grad on a 2-spinor, written out in real components:
	//
	//	(sigma.grad psi)_1 = d_z psi_1 + (d_x - i d_y) psi_2
	//	(sigma.grad psi)_2 = (d_x + i d_y) psi_1 - d_z psi_2
	//
	// The d_y terms are where sigma_y puts real and imaginary into each
	// other, and are why this cannot be staggered the way Schrodinger is.
	sl1a := gl1a.Z + gl2a.X + gl2b.Y
	sl1b := gl1b.Z + gl2b.X - gl2a.Y
	sl2a := gl1a.X - gl1b.Y - gl2a.Z
	sl2b := gl1b.X + gl1a.Y - gl2b.Z
	sr1a := gr1a.Z + gr2a.X + gr2b.Y
	sr1b := gr1b.Z + gr2b.X - gr2a.Y
	sr2a := gr1a.X - gr1b.Y - gr2a.Z
	sr2b := gr1b.X + gr1a.Y - gr2b.Z

	cc := Params[0].C
	om := Params[0].Omega0 // m c^2 / hbar: the rate L and R turn into each other

	// -i M psi takes (a, b) to (M b, -M a), which is the whole mass term
	dl1a := cc*sl1a + om*nr1b
	dl1b := cc*sl1b - om*nr1a
	dl2a := cc*sl2a + om*nr2b
	dl2b := cc*sl2b - om*nr2a
	dr1a := -cc*sr1a + om*nl1b
	dr1b := -cc*sr1b - om*nl1a
	dr2a := -cc*sr2a + om*nl2b
	dr2b := -cc*sr2b - om*nl2a

	// minimal coupling, grad -> grad - i (q/hbar c) A and the A0 energy shift:
	//
	//	d_t psi_L += i (q/hbar) [A0 + sigma.A] psi_L
	//	d_t psi_R += i (q/hbar) [A0 - sigma.A] psi_R
	//
	// sigma.A has the identical component structure to sigma.grad above, with
	// the potential in place of the derivative, and carries the same sign as
	// it does for each chirality -- both are halves of one sigma.D.
	//
	// Cheaper than the second-order version in two ways that are not
	// accidents. There is no (qA)^2 term, which only exists because squaring
	// the operator makes one. And there is no Boris push: in the second-order
	// equation A0 multiplies the VELOCITY, so it rotates it and has to be
	// applied exactly, while here it is one more term in the right-hand side.
	//
	// Params.WeylQ is the charge, and 0 is a neutrino. Nothing here derives
	// that -- see the WeylQ doc for where it does become a result.
	//
	// Keep |q A0 / hbar| well under the free omega. A constant A0 is pure
	// gauge and ought to change nothing, and on this lattice it very nearly
	// does: a couple of percent at A0 of 0.1 against a free omega of 0.36.
	// What is left is the scheme's own arcsin, which makes a shift in
	// frequency not quite a shift in frequency. Push A0 toward 1 and the
	// arcsin saturates and the wave stops making sense.
	if Params[0].EM.IsTrue() && Params[0].WeylQ != 0 {
		eoh := Params[0].WeylQ * Params[0].E / Params[0].Hbar
		a0 := State.Value(int(z), int(y), int(x), int(A0s), int(prv))
		ax := State.Value(int(z), int(y), int(x), int(AXs), int(prv))
		ay := State.Value(int(z), int(y), int(x), int(AYs), int(prv))
		az := State.Value(int(z), int(y), int(x), int(AZs), int(prv))
		// sigma.A on each spinor, same component pattern as sigma.grad
		ql1a := a0*nl1a + (az*nl1a + ax*nl2a + ay*nl2b)
		ql1b := a0*nl1b + (az*nl1b + ax*nl2b - ay*nl2a)
		ql2a := a0*nl2a + (ax*nl1a - ay*nl1b - az*nl2a)
		ql2b := a0*nl2b + (ax*nl1b + ay*nl1a - az*nl2b)
		qr1a := a0*nr1a - (az*nr1a + ax*nr2a + ay*nr2b)
		qr1b := a0*nr1b - (az*nr1b + ax*nr2b - ay*nr2a)
		qr2a := a0*nr2a - (ax*nr1a - ay*nr1b - az*nr2a)
		qr2b := a0*nr2b - (ax*nr1b + ay*nr1a - az*nr2b)
		// multiplying by i takes (a, b) to (-b, a)
		dl1a -= eoh * ql1b
		dl1b += eoh * ql1a
		dl2a -= eoh * ql2b
		dl2b += eoh * ql2a
		dr1a -= eoh * qr1b
		dr1b += eoh * qr1a
		dr2a -= eoh * qr2b
		dr2b += eoh * qr2a
	}

	l1a := ol1a + 2*dl1a
	l1b := ol1b + 2*dl1b
	l2a := ol2a + 2*dl2a
	l2b := ol2b + 2*dl2b
	r1a := or1a + 2*dr1a
	r1b := or1b + 2*dr1b
	r2a := or2a + 2*dr2a
	r2b := or2b + 2*dr2b

	State.Set(l1a, int(z), int(y), int(x), int(WeylL1a), int(cur))
	State.Set(l1b, int(z), int(y), int(x), int(WeylL1b), int(cur))
	State.Set(l2a, int(z), int(y), int(x), int(WeylL2a), int(cur))
	State.Set(l2b, int(z), int(y), int(x), int(WeylL2b), int(cur))
	State.Set(r1a, int(z), int(y), int(x), int(WeylR1a), int(cur))
	State.Set(r1b, int(z), int(y), int(x), int(WeylR1b), int(cur))
	State.Set(r2a, int(z), int(y), int(x), int(WeylR2a), int(cur))
	State.Set(r2b, int(z), int(y), int(x), int(WeylR2b), int(cur))

	// the STAGGERED magnitude u(t).u(t+1), not |u(t+1)|^2: a three-level
	// leapfrog conserves the product of adjacent levels exactly, the same way
	// Visscher's scheme does, and squaring one level alone ripples instead.
	State.Set(nl1a*l1a+nl1b*l1b+nl2a*l2a+nl2b*l2b, int(z), int(y), int(x), int(WeylLMag), int(cur))
	State.Set(nr1a*r1a+nr1b*r1b+nr2a*r2a+nr2b*r2b, int(z), int(y), int(x), int(WeylRMag), int(cur))
}

//gosl:end

func (ss *Sim) WeylConfig() {
	ParamsShouldDisplay = WeylShouldDisplay
	ss.StateVars = WeylStatesN
	ss.initFuncs = WeylConfigs
	ss.InitFunc = NeutrinoPacket
	ss.WeylStats()
	// a first-order leapfrog needs sqrt(c^2 khat^2 + om^2) < 1, and khat for
	// the 10-point gradient runs past 1, so C sits well under the second-order
	// limit of sqrt(3)/2. Mass is set per config, not here.
	ss.Params.C = WeylC
	ss.Params.Edges = EdgesWrap
	ss.Params.ThreeD.SetBool(true) // the kernel has no 1D path: see WeylKernel
	ss.Params.Update()
	ss.ViewInit(func(view *View) {
		view.SetVar(WeylLMag, -1)
	})
}

// WeylViewAll configures the View to display Weyl values
func WeylViewAll(view *View) {
	view.Settings.NPanels = PanelsFour
	view.Settings.Camera = 2
	view.Settings.Height = 0.8
	view.Panels[0].Var = WeylL1a
	view.Panels[1].Var = WeylL1b
	view.Panels[2].Var = WeylR1a
	view.Panels[3].Var = WeylR1b
}

// WeylC is the speed of light WeylConfig sets: the first-order leapfrog is
// tighter than the second-order one the other equations use.
const WeylC float32 = 0.35

// WeylMass is the electron mass the AT REST configs set, light enough that the
// L-R trade takes a watchable 50 steps: the period is pi hbar / m c^2.
const WeylMass float32 = 0.5

// WeylPacketMass is the heavier mass ElectronPacket sets, because the two
// demands pull opposite ways. Visibly slower than light needs m c^2 to be
// comparable to the momentum c khat, which at the default wavelength means
// about this; a watchable flip needs the mass SMALL, since the period goes as
// 1/m. A packet this heavy zitters about four times faster than it crosses a
// wavelength, which is the honest picture -- the trade really is that quick.
const WeylPacketMass float32 = 2

var WeylShouldDisplay = []string{"Edges", "C", "Hbar", "Mass", "EM", "WeylQ", "E", "Wavelength", "PacketWidth", "Amplitude"}

// WeylStats tracks the two chiralities separately, which is the whole point.
func (ss *Sim) WeylStats() {
	ss.AddStat(ss.StatStep())
	ss.AddStat(ss.StatSum(WeylLMag))
	ss.AddStat(ss.StatSum(WeylRMag))
	// both chiralities: for the neutrino only L moves, and for an electron the
	// two must track each other, since they are halves of one particle
	ss.AddStat(ss.StatGroupVelMag(math32.X, WeylLMag, WeylRMag))
	ss.AddStat(ss.StatWeylHelicity(math32.X))
}

// StatWeylHelicity records the spin of each chirality along dim, normalized by
// its own magnitude. For a wave travelling along dim that IS the helicity,
// sigma . khat, and it must sit at -1 for the left-handed half and +1 for the
// right-handed one.
//
// Spin lives in the two components, which are the sigma_z basis: 1 is spin up
// along Z and 2 is spin down. So for motion along Z the helicity is simply
// WHICH component is filled, and for motion along X it is the relative SIGN of
// the two, since (1,-1)/sqrt2 is spin along -X and (1,1)/sqrt2 along +X.
//
// The equation is what locks them together. Its only spatial term is
// sigma.grad, so a positive-energy left-handed solution is forced to have
// sigma . khat = -1; a spinor pointing any other way is not one wave but two,
// and splits. That is why reversing a neutrino's spin reverses where it goes.
//
// Helicity is conserved and chirality is not, so on a massive packet these
// stay pinned while the L and R magnitudes trade.
func (ss *Sim) StatWeylHelicity(dim math32.Dims) func(init bool) {
	names := []string{"HelicityL", "HelicityR"}
	return func(init bool) {
		if init {
			for _, nm := range names {
				tsr := ss.Stats.Float64(nm)
				tsr.SetNumRows(0)
				plot.SetFirstStyler(tsr, func(s *plot.Style) {
					s.On = true
					s.Range.SetMin(-1.1).SetMax(1.1)
				})
				metadata.SetDoc(tsr, "Spin along "+dim.String()+" per unit magnitude: the helicity of a wave going that way")
			}
			return
		}
		ctx := GetCtx(0)
		cur := ctx.CurState
		sz := ss.Config.Size
		var num, den [2]float64
		var c math32.Vector3i
		for c.Z = range sz.Z {
			for c.Y = range sz.Y {
				for c.X = range sz.X {
					f := c.AddScalar(1)
					for h, base := range []WeylStates{WeylL1a, WeylR1a} {
						b := int(base.Int64())
						a1 := float64(State.Value(int(f.Z), int(f.Y), int(f.X), int(b), int(cur)))
						b1 := float64(State.Value(int(f.Z), int(f.Y), int(f.X), int(b+1), int(cur)))
						a2 := float64(State.Value(int(f.Z), int(f.Y), int(f.X), int(b+2), int(cur)))
						b2 := float64(State.Value(int(f.Z), int(f.Y), int(f.X), int(b+3), int(cur)))
						sp := 0.0
						switch dim {
						case math32.X:
							sp = 2 * (a1*a2 + b1*b2)
						case math32.Y:
							sp = 2 * (a1*b2 - b1*a2)
						default:
							sp = (a1*a1 + b1*b1) - (a2*a2 + b2*b2)
						}
						num[h] += sp
						den[h] += a1*a1 + b1*b1 + a2*a2 + b2*b2
					}
				}
			}
		}
		for h, nm := range names {
			v := 0.0
			if den[h] > 0 {
				v = num[h] / den[h]
			}
			ss.Stats.Float64(nm).AppendRowFloat(v)
		}
	}
}

// WeylDispersion returns the lattice frequency and group velocity of a wave of
// the given wavelength running along an axis:
//
//	omega = arcsin(sqrt(c^2 sin^2 k + om0^2))
//
// The sin k is the gradient stencil's response to a plane wave and the arcsin
// is the three-level leapfrog's own, and together they match the measured
// period to five digits. Both corrections matter: at wavelength 8 the naive
// c k overstates the frequency by 13%.
func (ss *Sim) WeylDispersion(wavelength float32) (float32, float32) {
	k := TwoPi / wavelength
	c := ss.Params.C
	o0 := ss.Params.Omega0
	sk := math32.Sin(k)
	ss2 := c*c*sk*sk + o0*o0
	rs := math32.Sqrt(ss2)
	if rs <= 0 {
		return 0, 0
	}
	return math32.Asin(rs), c * c * sk * math32.Cos(k) / (rs * math32.Sqrt(1-ss2))
}

// WeylSlab fills one chirality with a gaussian slab at rest: flat across the
// two transverse axes, no phase, spin along Z. For the configs that are not
// meant to move but should still look like something.
func (ss *Sim) WeylSlab(side WeylStates, dim math32.Dims, amp float32) {
	c1 := int(side.Int64())
	ctx := GetCtx(0)
	cur := ctx.CurState
	prv := ctx.PrevState()
	ctr := CenterF(math32.Vec3(-1, -1, -1))
	wd := ss.Config.PacketWidth
	sz := ss.Config.Size
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				g := (CoordToFloat(c).Dim(dim) - ctr.Dim(dim)) / wd
				v := amp * math32.FastExp(-g*g)
				State.SetAdd(v, int(f.Z), int(f.Y), int(f.X), int(c1), int(cur))
				State.SetAdd(v, int(f.Z), int(f.Y), int(f.X), int(c1), int(prv))
			}
		}
	}
}

// WeylPacket puts a moving packet of one chirality into the state: a gaussian
// envelope times exp(i k.x), on the spinor with sigma.khat = helicity, so it
// is a single frequency and travels rigidly.
//
// Helicity, not chirality, is what the spinor encodes. A massless L wave can
// only have helicity -1 and an R wave +1, which is why reversing a neutrino's
// spin reverses its direction. A MASSIVE particle has both chiralities at one
// helicity, in the ratio (omega - c khat) / (m c^2 / hbar), so ElectronPacket
// calls this twice with the same helicity and different amplitudes.
//
// The envelope is a SLAB: gaussian along the direction of travel, flat across
// the other two. That is not just for looks. A round blob carries transverse
// momentum, so it is not a helicity eigenstate, it spreads sideways, and its
// centroid crawls instead of moving at the group velocity. A slab has k purely
// along one axis, travels rigidly, and reads on screen as bands sweeping
// across rather than a dot that may or may not be drifting.
//
// Both time levels are set. The three-level leapfrog reads its own past, and a
// wave given no past goes both ways at once: the earlier one has its envelope
// pulled back by one step of GROUP velocity and its phase advanced by one step
// of omega, which are the same thing only when the wave is massless.
func (ss *Sim) WeylPacket(side WeylStates, dim math32.Dims, helicity, amp float32) {
	c1 := int(side.Int64())
	// the spinor with sigma.khat = helicity, for khat along +dim
	s1, s2 := float32(1)/math32.Sqrt2, helicity/math32.Sqrt2 // +X: sigma_x
	if dim == math32.Z {                                     // +Z: sigma_z is already diagonal
		s1, s2 = 0, 1
		if helicity > 0 {
			s1, s2 = 1, 0
		}
	}
	wl := ss.Config.Wavelength
	wd := ss.Config.PacketWidth
	om, vg := ss.WeylDispersion(wl)
	k := TwoPi / wl
	// the LOCAL potential belongs in the phase advance too, as it does in
	// [Sim.ChargedRest]: a wave at rest in a potential turns at a rate shifted
	// by q A0 / hbar, and a past written without it is a past of the wrong
	// wave -- which shows up as an admixture of the other energy sign,
	// dragging the packet backwards in proportion to A0.
	eoh := float32(0)
	if ss.Params.EM.IsTrue() {
		eoh = ss.Params.WeylQ * ss.Params.E / ss.Params.Hbar
	}
	ctx := GetCtx(0)
	cur := ctx.CurState
	prv := ctx.PrevState()
	ctr := CenterF(math32.Vec3(-1, -1, -1))
	sz := ss.Config.Size
	var c math32.Vector3i
	for c.Z = range sz.Z {
		for c.Y = range sz.Y {
			for c.X = range sz.X {
				f := c.AddScalar(1)
				d := CoordToFloat(c).Dim(dim) - ctr.Dim(dim)
				g := d / wd
				e := (d + vg) / wd // where the envelope was one step ago
				en := amp * math32.FastExp(-g*g)
				eo := amp * math32.FastExp(-e*e)
				ph := k * d
				na, nb := en*math32.Cos(ph), en*math32.Sin(ph)
				po := om + eoh*State.Value(int(f.Z), int(f.Y), int(f.X), int(A0s), int(prv))
				oa, ob := eo*math32.Cos(ph+po), eo*math32.Sin(ph+po)
				State.SetAdd(s1*na, int(f.Z), int(f.Y), int(f.X), int(c1), int(prv))
				State.SetAdd(s1*nb, int(f.Z), int(f.Y), int(f.X), int(c1+1), int(prv))
				State.SetAdd(s2*na, int(f.Z), int(f.Y), int(f.X), int(c1+2), int(prv))
				State.SetAdd(s2*nb, int(f.Z), int(f.Y), int(f.X), int(c1+3), int(prv))
				State.SetAdd(s1*oa, int(f.Z), int(f.Y), int(f.X), int(c1), int(cur))
				State.SetAdd(s1*ob, int(f.Z), int(f.Y), int(f.X), int(c1+1), int(cur))
				State.SetAdd(s2*oa, int(f.Z), int(f.Y), int(f.X), int(c1+2), int(cur))
				State.SetAdd(s2*ob, int(f.Z), int(f.Y), int(f.X), int(c1+3), int(cur))
			}
		}
	}
}

// NeutrinoPacket is a massless left-handed wave and nothing else. With Mass at
// zero there is no term anywhere that can put anything into the right-handed
// half, so it stays exactly empty forever: that is what it means for the
// neutrino to have only one handedness. It travels at c, since a massless wave
// has nothing to slow it.
func NeutrinoPacket(ss *Sim) {
	ss.Params.Mass = 0
	ss.Params.Update()
	ss.WeylPacket(WeylL1a, math32.X, -1, ss.Config.Amplitude)
}

// ElectronPacket is the same wave given a mass, and the comparison to make
// against NeutrinoPacket: identical wavelength, identical box, and it travels
// visibly SLOWER. Both halves are there and both move together, because they
// are halves of one particle.
//
// That is the whole picture made quantitative. The two halves each still go at
// c; what the mass does is turn each into the other, and a thing that keeps
// reversing gets down the box more slowly than one that does not. The heavier
// it is, the more often it turns, and the slower it goes -- raise Mass and
// watch the packet fall behind.
//
// The two amplitudes are not equal once it is moving: a momentum eigenstate
// has them in the ratio (omega - c khat) / (m c^2 / hbar), which goes to 1 at
// rest and to 0 at high momentum, where the particle becomes effectively
// massless and one chirality takes over.
//
// Both halves are seen going the SAME way, and that is right: they are two
// components of one particle with one momentum, not two particles. The
// opposite streaming is in the transport terms, which carry L at +c and R at
// -c for this helicity -- but the mass term refills each from the other faster
// than either can get away, so what moves is the pair, at
//
//	v = c (|psi_L|^2 - |psi_R|^2) / (|psi_L|^2 + |psi_R|^2)
//
// the intensity-weighted average of the two streams. The mass does not slow
// anything down; it tilts the balance between a right-going stream and a
// left-going one.
//
// Nor does this one visibly zitter. A positive-energy momentum eigenstate has
// one frequency, so the ratio just sits there -- only the few percent of the
// other energy sign that the initialization leaves behind ripples it, at the
// expected pi hbar / m c^2. ElectronChiralFlip is the zitter demo, and it is
// built from an equal mix of both signs, which is why it swings all the way.
// Nothing moves transversely in either: Z holds to five digits.
func ElectronPacket(ss *Sim) {
	p := ss.Params
	p.Mass = WeylPacketMass
	p.Update()
	om, _ := ss.WeylDispersion(ss.Config.Wavelength)
	ck := p.C * math32.Sin(TwoPi/ss.Config.Wavelength)
	rr := (om - ck) / p.Omega0 // right-handed share of a positive-energy state
	a := ss.Config.Amplitude
	ss.WeylPacket(WeylL1a, math32.X, -1, a)
	ss.WeylPacket(WeylR1a, math32.X, -1, a*rr)
}

// ElectronAtRest is the two halves in equal measure, which is what a massive
// particle at rest IS: chirality is not helicity, and at zero momentum the
// electron is half left and half right at every instant. Both magnitudes sit
// flat while the phases turn at the rest mass frequency.
func ElectronAtRest(ss *Sim) {
	ss.Params.Mass = WeylMass
	ss.Params.Update()
	a := ss.Config.Amplitude
	ss.WeylSlab(WeylL1a, math32.X, a)
	ss.WeylSlab(WeylR1a, math32.X, a)
}

// ElectronChiralFlip starts the whole electron in the LEFT half and lets the
// mass term do the rest. It converts entirely into the right half and back:
//
//	|psi_L|^2 = cos^2(m c^2 t / hbar),  |psi_R|^2 = sin^2(m c^2 t / hbar)
//
// so each swings over a period of pi hbar / m c^2 while the sum stays flat.
// Watch the band vanish from one panel and appear in the other. This is
// zitterbewegung, and it is the clearest statement of what mass is: not a
// property the wave has, but the rate at which two massless waves turn into
// one another. Set Mass to zero and the trade stops dead -- a neutrino.
func ElectronChiralFlip(ss *Sim) {
	ss.Params.Mass = WeylMass
	ss.Params.Update()
	ss.WeylSlab(WeylL1a, math32.X, ss.Config.Amplitude)
}

// WeylFieldE is the electric field ElectronInField sets, as the slope of A0
// per cube at the center. Small: it has to push the packet noticeably over a
// few dozen steps while |q A0 / hbar| stays well under the free omega, or the
// arcsin in the scheme starts distorting things by more than the field does.
const WeylFieldE float32 = 0.008

// ElectronInField is the same moving electron in a uniform electric field, and
// the place to see what charge does here. The field pushes against its motion,
// so it loses momentum and visibly slows -- about 17% over 60 steps.
//
// The field points this way rather than the other because the lattice is not
// symmetric about it. Slowing lowers k, and the group velocity falls steeply
// there; speeding up raises k toward pi/2, where the gradient stencil's
// response turns over and the velocity barely moves. The same force is far
// easier to see as a brake than as an accelerator.
//
// Now set Params.WeylQ to 0 and run it again: the packet sails straight
// through as though the field were not there. That is a neutrino, and it is
// worth being clear about what has just been shown. Nothing in this equation
// DERIVED the neutrality -- WeylQ is a number that was typed in. The wave does
// not care which value it gets.
//
// Neutrality becomes a result only with the electroweak structure, where
// Q = T^3 + Y and the photon is the mix of B and W^3 that the doublet's upper
// component cannot see. There the neutrino has no choice.
func ElectronInField(ss *Sim) {
	p := ss.Params
	p.EM.SetBool(true)
	p.SelfField.SetBool(false) // the field is external and must stay as set
	p.Edges = EdgesWrap
	p.Update()
	// A sine over exactly one box length, not a ramp. The field has to be
	// PERIODIC: Weyl has no damping kernel, so EdgesDamp runs nothing at all
	// and wrapping is the only edge that works -- and a linear ramp wrapped
	// round puts its whole drop across the boundary cells. One period of a
	// sine meets itself, and its gradient is near-uniform across the middle
	// where the packet lives, falling off toward the ends.
	//
	// Field FIRST: WeylPacket reads A0 to get its own past right.
	l := float32(ss.Config.Size.X)
	ss.Sine(A0s, math32.X, l, 0, -WeylFieldE*l/TwoPi, 0)
	ElectronPacket(ss)
}

var WeylConfigs = []InitFunc{
	InitFunc{Name: "Neutrino Packet", Doc: "A massless left-handed wave travelling at exactly c, with the right-handed half staying exactly empty", Func: NeutrinoPacket, Current: true},
	InitFunc{Name: "Electron Packet", Doc: "The same wave with a mass: both halves, moving together, and visibly slower than the neutrino", Func: ElectronPacket},
	InitFunc{Name: "Electron At Rest", Doc: "Both halves in equal measure, which is what a massive particle at rest is: half left and half right", Func: ElectronAtRest},
	InitFunc{Name: "Electron Chiral Flip", Doc: "The whole electron started left-handed: the mass turns it entirely into the right-handed one and back", Func: ElectronChiralFlip},
	InitFunc{Name: "Electron In Field", Doc: "A charged packet in a uniform electric field: it picks up momentum, and with WeylQ at 0 it is a neutrino and ignores the field", Func: ElectronInField},
}
